### ISSUE TITLE
Even after installing annoy I am getting the error : ImportError: Annoy has not been installed,

### ISSUE THREAD

**Issue by shaktisd** [RaRe-Technologies/gensim#1007]
python annoy.py
Traceback (most recent call last):
  File "annoy.py", line 3, in <module>
    from gensim.similarities.index import AnnoyIndexer
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.2-py2.7-linux-x86_64.egg/gensim/similarities/index.py", line 13, in <module>
    raise ImportError("Annoy has not been installed, if you wish to use the annoy indexer, please run `pip install annoy`")
ImportError: Annoy has not been installed, if you wish to use the annoy indexer, please run `pip install annoy`
$ sudo pip install annoy
Requirement already satisfied: annoy in /usr/local/lib/python2.7/dist-packages

$ pip freeze | grep annoy
annoy==1.8.0
$ pip freeze | grep gensim
gensim==0.13.2

**Comment by shaktisd** [comment]
My mistake I was having a file named annoy.py , renaming the file solved the problem.
