### ISSUE TITLE
cannot import Dictionary from gensim.corpora

### ISSUE THREAD

**Issue by markroxor** [RaRe-Technologies/gensim#1058]
while importing `Dictionary` via `from gensim.corpora import Dictionary` in python 2.7 I get the following error -  

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.3-py2.7-linux-x86_64.egg/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.3-py2.7-linux-x86_64.egg/gensim/models/__init__.py", line 7, in <module>
    from .coherencemodel import CoherenceModel
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.3-py2.7-linux-x86_64.egg/gensim/models/coherencemodel.py", line 30, in <module>
    from gensim.models.wrappers import LdaVowpalWabbit, LdaMallet
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.3-py2.7-linux-x86_64.egg/gensim/models/wrappers/__init__.py", line 8, in <module>
    from .wordrank import Wordrank
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.3-py2.7-linux-x86_64.egg/gensim/models/wrappers/wordrank.py", line 41, in <module>
    import subprocess32 as subprocess
ImportError: No module named subprocess32

I am using posix interface.
The issue is with the wordrank wrapper.

**Comment by markroxor** [comment]
I messed up the installation. Closing this.

**Comment by piskvorky** [comment]
How did you mess it up?

Please provide some context/fix, in case other people google up this issue in the future.

**Comment by markroxor** [comment]
I installed tensorflow with gpu support via pip. I wasn't able to import gensim at all after that. I quickly terminated the aws instance and started afresh, it was working fine then.

**Comment by piskvorky** [comment]
Hmm, I don't see the connection. We certainly don't want TensorFlow to be an anti-dependency for gensim.

@tmylk @gojomo any ideas?

**Comment by markroxor** [comment]
Anyways the issue traced back to the wordrank wrapper. but it has been removed in recent commits. I think this issue won't arise again.

**Comment by tmylk** [comment]
Confirm that @markroxor has diagnosed this issue correctly. No action needed.

**Comment by piskvorky** [comment]
So what was the actual issue?

**Comment by tmylk** [comment]
The issue was that `subprocess32` library was not being imported in Python 2.6 in setup.py. This issue was stopping the develop build. It will not arise again because PRs with failed builds will not be merged to develop.
