### ISSUE TITLE
OSX Python3.5 test failure loading pre-KeyedVectors

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1060]
See [build log](https://travis-ci.org/MacPython/gensim-wheels/jobs/186640404)

```
======================================================================
ERROR: Test loading pre-KeyedVectors word2vec model
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/gensim-wheels/venv/lib/python3.5/site-packages/gensim/test/test_word2vec.py", line 203, in testLoadPreKeyedVectorModel
    model = word2vec.Word2Vec.load(datapath(model_file))
  File "/Users/travis/build/MacPython/gensim-wheels/venv/lib/python3.5/site-packages/gensim/models/word2vec.py", line 1439, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/Users/travis/build/MacPython/gensim-wheels/venv/lib/python3.5/site-packages/gensim/utils.py", line 251, in load
    obj = unpickle(fname)
  File "/Users/travis/build/MacPython/gensim-wheels/venv/lib/python3.5/site-packages/gensim/utils.py", line 916, in unpickle
    return _pickle.load(f, encoding='latin1')
ImportError: No module named 'UserList'
-------------------- >> begin captured logging << --------------------
gensim.utils: INFO: loading Word2Vec object from /Users/travis/build/MacPython/gensim-wheels/venv/lib/python3.5/site-packages/gensim/test/test_data/word2vec_pre_kv_py3
--------------------- >> end captured logging << ---------------------
```

**Comment by tmylk** [comment]
Ping @anmol01gulati

**Comment by piskvorky** [comment]
Is this `unpickle` broken in general, or just for this specific Word2Vec scenario?

What is `UserList`?

**Comment by anmol01gulati** [comment]
I found this to be a pickle issue with distinct python versions. Similar [issue](https://github.com/mps-youtube/mps-youtube/issues/366) in mps-youtube.

On searching deeper, It's an issue with pickle, it creates incorrect pickle between different Python 3.x versions. So, it works fine loading py3 pickled files in py2 and vice-versa, but fails in between py 3.x versions. See: [https://bugs.python.org/issue26013](https://bugs.python.org/issue26013).
So, it fails to load pickle file in py 3.4 that was created in py 3.5 

This didn't come up earlier in LdaModels I guess because, it breaks if they include a collections.OrderedDict.

They talk about a patch that allows to load such broken pickles though. 
  
`import _compact_pickle
_compact_pickle.IMPORT_MAPPING.update({
    'UserDict': 'collections',
    'UserList': 'collections',
    'UserString': 'collections',
    'whichdb': 'dbm',
    'StringIO':  'io',
    'cStringIO': 'io',
})`
I could open a new PR and implement this patch for this issue. What do you think?

**Comment by tmylk** [comment]
We do support python 3.4. A PR with that fix will be very welcome.

**Comment by piskvorky** [comment]
Thanks for investigating @anmol01gulati .

I'm not so sure we want to work around internal pickle issues to that level of detail.

The Python issue you linked to says this is already fixed in python 3.5.2 -- is a gensim-level fix really needed?

**Comment by tmylk** [comment]
@anmol01gulati The 3.5.2 build is [running](https://travis-ci.org/MacPython/gensim-wheels/jobs/189195464)

**Comment by anmol01gulati** [comment]
Well, I think, it won't be right to have a fix for pickle inside gensim itself, it sounds a hack basically. We'd like to shift to some other pickling library if that was the case.
t seems, they've solved this issue in Python version 3.5.2. So, let's see if the latest build passes, then it'd be fine.
