### ISSUE TITLE
Model saving with gzip gives TypeError in Python 2

### ISSUE THREAD

**Issue by fnielsen** [RaRe-Technologies/gensim#1219]
Latest pip-version model saving with gzip gives TypeError in Python 2. It works (as far as I can determine) in Python 3.5.2.
```
from gensim.models import Word2Vec
w2v = Word2Vec(['asdfasdfasdfsadf'.split() * 10])
w2v.save('word2vec.pkl.gz')
```
I was expecting that the model would be saved in a file 'word2vec.pkl.gz'. This happens with Python3 but with Python 2 I get:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 1264, in save
    super(Word2Vec, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 497, in save
    pickle_protocol=pickle_protocol)
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 369, in _smart_save
    pickle(self, fname, protocol=pickle_protocol)
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 919, in pickle
    with smart_open(fname, 'wb') as fout:  # 'b' for binary, needed on Windows
  File "/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py", line 138, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode)
  File "/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py", line 642, in file_smart_open
    return compression_wrapper(open(fname, mode), fname, mode)
  File "/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py", line 630, in compression_wrapper
    return make_closing(GzipFile)(file_obj, mode)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
TypeError: coercing to Unicode: need string or buffer, file found
```
Version information:
```
>>> import platform; print(platform.platform())
Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
>>> import sys; print("Python", sys.version)
('Python', '2.7.12 (default, Nov 19 2016, 06:48:10) \n[GCC 5.4.0 20160609]')
>>> import numpy; print("NumPy", numpy.__version__)
('NumPy', '1.12.0')
>>> import scipy; print("SciPy", scipy.__version__)
('SciPy', '0.19.0')
>>> import gensim; print("gensim", gensim.__version__)
('gensim', '1.0.1')
```

**Comment by tmylk** [comment]
Hi, please update smart_open to 1.5.1. It's fixed there

**Comment by fnielsen** [comment]
I can confirm that smart_open upgrade make it work. Thanks!
