### ISSUE TITLE
File not found error in wordrank wrapper

### ISSUE THREAD

**Issue by shashankg7** [RaRe-Technologies/gensim#1279]
Hi,

When I try running the wordrank wrapper on a sample corpus, I get the following error:

>>> from gensim.models.wrappers import Wordrank
>>> Wordrank.train('./wordrank', './tweets_crawled.txt', '../models/wordrank_model')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/wrappers/wordrank.py", line 105, in train
    utils.check_output(w, args=command, stdin=r)
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 1167, in check_output
    process = subprocess.Popen(stdout=stdout, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

All the files are present, I doubled checked. Not sure what the error is.

**Comment by tmylk** [comment]
Hi, do you get the same result when running the command from the command line?
If yes, then it is probably to do with user permissions.
The command is printed after "Prepare training data using glove code " in the INFO log

**Comment by tmylk** [comment]
Closing as abandoned.
