### ISSUE TITLE
Error installing gensim on windows : ImportError: cannot import name 'add_newdocs'

### ISSUE THREAD

**Issue by sridharmalepati** [RaRe-Technologies/gensim#1290]
Hi,

Am trying to install gensim on windows 10 under anaconda, am getting the following error:
I did try all the options, pip and easy install. None of them is working.

```
(D:\install\Anaconda3) C:\Users\sridh>easy_install --upgrade gensim
Searching for gensim
Reading https://pypi.python.org/simple/gensim/
Downloading https://pypi.python.org/packages/63/fb/cf179ba76171489d9097bbc679b6375c0213b99203d90ffa52a373bb8167/gensim-2.0.0.tar.gz#md5=aa0f16fa3c063eafa2ac5270527ff07c
Best match: gensim 2.0.0
Processing gensim-2.0.0.tar.gz
Writing C:\Users\sridh\AppData\Local\Temp\easy_install-6v4pobwx\gensim-2.0.0\setup.cfg
Running gensim-2.0.0\setup.py -q bdist_egg --dist-dir C:\Users\sridh\AppData\Local\Temp\easy_install-6v4pobwx\gensim-2.0.0\egg-dist-tmp-y22srw14
Traceback (most recent call last):
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 156, in save_modules
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 197, in setup_context
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 246, in run_setup
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 276, in run
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 245, in runner
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 47, in _execfile
  File "C:\Users\sridh\AppData\Local\Temp\easy_install-6v4pobwx\gensim-2.0.0\setup.py", line 294, in <module>
  File "D:\install\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\install\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\install\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\bdist_egg.py", line 152, in run
  File "D:\install\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\install\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 195, in run
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 222, in find_sources
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 306, in run
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 335, in add_defaults
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\sdist.py", line 171, in add_defaults
  File "D:\install\Anaconda3\lib\distutils\cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "D:\install\Anaconda3\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "C:\Users\sridh\AppData\Local\Temp\easy_install-6v4pobwx\gensim-2.0.0\setup.py", line 100, in finalize_options
  File "D:\install\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
ImportError: cannot import name 'add_newdocs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\install\Anaconda3\Scripts\easy_install-script.py", line 5, in <module>
    sys.exit(setuptools.command.easy_install.main())
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\easy_install.py", line 2274, in main
  File "D:\install\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\install\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\install\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\easy_install.py", line 409, in run
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\easy_install.py", line 664, in easy_install
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\easy_install.py", line 694, in install_item
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\easy_install.py", line 875, in install_eggs
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\easy_install.py", line 1114, in build_and_install
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\easy_install.py", line 1100, in run_setup
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 249, in run_setup
  File "D:\install\Anaconda3\lib\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 197, in setup_context
  File "D:\install\Anaconda3\lib\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 168, in save_modules
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 143, in resume
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 156, in save_modules
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 197, in setup_context
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 246, in run_setup
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 276, in run
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 245, in runner
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\sandbox.py", line 47, in _execfile
  File "C:\Users\sridh\AppData\Local\Temp\easy_install-6v4pobwx\gensim-2.0.0\setup.py", line 294, in <module>
  File "D:\install\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\install\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\install\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\bdist_egg.py", line 152, in run
  File "D:\install\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\install\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 195, in run
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 222, in find_sources
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 306, in run
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 335, in add_defaults
  File "D:\install\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\sdist.py", line 171, in add_defaults
  File "D:\install\Anaconda3\lib\distutils\cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "D:\install\Anaconda3\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "C:\Users\sridh\AppData\Local\Temp\easy_install-6v4pobwx\gensim-2.0.0\setup.py", line 100, in finalize_options
  File "D:\install\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
ImportError: cannot import name 'add_newdocs'
```

Regards
Sridhar

**Comment by gojomo** [comment]
The exception actually appears to be happening in a `numpy`-related step – but maybe that's a side-effect of the attempted `easy_install` – which is very strongly deprecated in favor of using `pip`.

Can you try starting with a fresh conda/anaconda environment, be sure to uninstall gensim (if present), then simply use `pip install gensim', and see if that works, or gets a similar error?

**Comment by sridharmalepati** [comment]
Thanks @gojomo for your response !!...

Infact i had tried this already...it says installed...but when i do a "import gensim" i get a error again :-(
See below. Just to show you I re-ran it. See two screen shots below!
```

(D:\install\Anaconda3) C:\Users\sridh>pip install gensim
Requirement already satisfied: gensim in d:\install\anaconda3\lib\site-packages
Requirement already satisfied: numpy>=1.3 in d:\install\anaconda3\lib\site-packages (from gensim)
Requirement already satisfied: smart-open>=1.2.1 in d:\install\anaconda3\lib\site-packages (from gensim)
Requirement already satisfied: six>=1.5.0 in d:\install\anaconda3\lib\site-packages (from gensim)
Requirement already satisfied: scipy>=0.7.0 in d:\install\anaconda3\lib\site-packages (from gensim)
Requirement already satisfied: boto>=2.32 in d:\install\anaconda3\lib\site-packages (from smart-open>=1.2.1->gensim)
Requirement already satisfied: bz2file in d:\install\anaconda3\lib\site-packages (from smart-open>=1.2.1->gensim)
Requirement already satisfied: requests in d:\install\anaconda3\lib\site-packages (from smart-open>=1.2.1->gensim)

**But here i get error when i try to import it** 

In [1]: import gensim
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ec15f3ffe0f1> in <module>()
----> 1 import gensim

D:\install\Anaconda3\lib\site-packages\gensim\__init__.py in <module>()
      4 """
      5
----> 6 from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
      7 import logging
      8

D:\install\Anaconda3\lib\site-packages\gensim\parsing\__init__.py in <module>()
      5 # bring model classes directly into package namespace, to save some typing
      6 from .porter import PorterStemmer
----> 7 from .preprocessing import *

D:\install\Anaconda3\lib\site-packages\gensim\parsing\preprocessing.py in <module>()
      8 import glob
      9
---> 10 from gensim import utils
     11 from gensim.parsing.porter import PorterStemmer
     12

D:\install\Anaconda3\lib\site-packages\gensim\utils.py in <module>()
     38 import subprocess
     39
---> 40 import numpy as np
     41 import numbers
     42 import scipy.sparse

D:\install\Anaconda3\lib\site-packages\numpy\__init__.py in <module>()
    140         return loader(*packages, **options)
    141
--> 142     from . import add_newdocs
    143     __all__ = ['add_newdocs',
    144                'ModuleDeprecationWarning',

ImportError: cannot import name 'add_newdoc
```s'

**Comment by gojomo** [comment]
It again seems like a problem with the numpy installation. 

Are you using a fresh, independent (ana)conda environment? (That may not be the case; it looks like packages are being used from a sitewide `site-packages` instead of a specific conda environment. An isolated conda environment to control what is installed for a specific project is often a good idea.) 

Have you tried uninstalling and reinstalling numpy?

Others who have encountered a similar numpy-related error seem to have eventually fixed their problem by reinstalling, or avoiding conflicts in where Python packages are being discovered. See http://stackoverflow.com/questions/22465066/importerror-cannot-import-name-add-newdocs

**Comment by sridharmalepati** [comment]
Thanks @gojomo , its working now!

I uninstalled numy and gensim and then installed numpy and gensim and it works now!

```
In [1]: import numpy

In [2]: import gensim
D:\install\Anaconda3\lib\site-packages\gensim\utils.py:860: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Slow version of gensim.models.doc2vec is being used

```
Regards
Sridhar
