### ISSUE TITLE
CoherenceModel save fails if texts or corpus is generator

### ISSUE THREAD

**Issue by macks22** [RaRe-Technologies/gensim#1386]
#### Description
The `CoherenceModel` fails to save when `texts` or `corpus` is a generator object. This is particularly common for the texts, since that is often produced from the `get_texts` method.

My initial take on a fix: require the user to pass something compatible with the interface of `gensim.corpora.textcorpus.TextCorpus`. This can replace the arguments `texts` and `dictionary`. Then the `corpus` argument could either be a gensim-wide-compatible corpus (iterable produces bags of words) or a `TextCorpus`-compatible corpus (has `get_texts` method and `dictionary` instance). The initializer would need to identify which type of corpus it is, which seems easily doable.

#### Steps/Code/Corpus to Reproduce
Add this test to `test_coherencemodel.py`:
```
    def testPersistenceWithTextsGenerator(self):
        fname = testfile()
        gen_texts = (text for text in texts)
        model = CoherenceModel(topics=self.topics1, texts=gen_texts, dictionary=dictionary,
                               coherence='c_v')
        model.save(fname)
        model2 = CoherenceModel.load(fname)
        self.assertTrue(model.get_coherence() == model2.get_coherence())
```

#### Expected Results
Test should pass, saving and loading model correctly.

#### Actual Results
```
FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/Users/vru959/anaconda2/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/vru959/workshop/gensim/gensim/test/test_coherencemodel.py", line 223, in testPersistenceWithTextsGenerator
    model.save(fname)
  File "/Users/vru959/workshop/gensim/gensim/utils.py", line 499, in save
    pickle_protocol=pickle_protocol)
  File "/Users/vru959/workshop/gensim/gensim/utils.py", line 371, in _smart_save
    pickle(self, fname, protocol=pickle_protocol)
  File "/Users/vru959/workshop/gensim/gensim/utils.py", line 925, in pickle
    _pickle.dump(obj, fout, protocol=protocol)
TypeError: can't pickle generator objects
```

#### Versions
```
Darwin-16.6.0-x86_64-i386-64bit
('Python', '2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]')
('NumPy', '1.12.1')
('SciPy', '0.19.0')
('gensim', '2.1.0')
('FAST_VERSION', 1)
```

**Comment by menshikh-iv** [comment]
Thanks @macks22, unfortunately, generators can not be serialized. But I do not really understand what for I should serialize `CoherenceModel`?

**Comment by macks22** [comment]
At the moment, it's not important, but if #1349 gets merged, the cached accumulator is worth serializing to avoid accumulating word occurrences over an entire corpus again.
