### ISSUE TITLE
Virtual Core Distribution Issue Error When Importing/Assigning Very Large Word2Vec Encodings

### ISSUE THREAD

**Issue by justinkterry** [RaRe-Technologies/gensim#1486]
#### Description
 
On fully updated Ubuntu 16.04.2 LTS, I created a word2vec model object using the .vec file of a 8GB fasttext encoding (I know it's not best practices, but it was good enough for what I was trying to do) in ipython to do a few quick similarities look ups. On a whim, I went to my system monitor utility to watch my ram being consumed during the import (I have 32GB or RAM, this is not an issue with that), and saw this: http://i.imgur.com/LsR37sc.png . My CPU is an intel i7 7700k (with well documented stability and no overclocking, issue isn't there either). For some reason, one virtual core is used at 100% while the others stay nearly idle randomly switching between different ones. I repeated this across reboots, new kernels, etc. The encoding was built off the the English file .vec from here: https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md .

#### Code to Reproduce
import gensim
path='/home/station/Documents/wiki.en/wiki.en.vec'
model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=False) 

#### Expected Results
Distributing load across all virtual cores

#### Actual Results
See above, code ran didn't print anything so I can't give you that.

#### Versions
Everythings up to date according to pip3 as of 15 minutes ago and my systems up to date according to apt as of an hour ago. Your code:

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)

Linux-4.8.0-58-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
NumPy 1.13.1
SciPy 0.19.1
gensim 2.2.0
FAST_VERSION 1

If you want me to test anything with this due to developer machine ram limits or something, please let me know and I'd be happy to help.

**Comment by justinkterry** [comment]
Occurs on 4 core without multithreading as well. http://i.imgur.com/FshrgaA.png. Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz. Same set up otherwise.

**Comment by gojomo** [comment]
Loading vectors from a single text-format file is a single-threaded operation, so seeing only one core active during the operation is expected - not a bug. Further, there's not much to be parallelized about that particular operation - it's mostly dependent on IO to the single volume holding the file, with minimal calculation. (Other FastText formats, where a vector is constructed from its constituent char-n-gram vectors, are a bit more cpu-intensive so *might* remotely gain from parallelization, but still probably not worth the code complexity.)

**Comment by justinkterry** [comment]
Watching resources seemed to show it was majorly limited by CPU for my
wierd case, would you like me to send performance metrics and if so what
kind? Also why isn't that operation distributable across multiple cores?
You may be entirely right, but it isn't obvious to me why that's the case.

**Comment by gojomo** [comment]
You can look at the source code for `load_word2vec_format()` - it has to read a single text file in order, assigning read values into the pre-allocated array. There's no preexisting index, so there's no way to seek to deep points in the file and know exactly which array slot the nearby entries should go into. Having multiple threads/processes contend for reading the same file would (for many kinds of volumes, like spinning disks) just increase each's IO waits. So it's not a great candidate for parallelization. 

Reading 8GB+ into RAM can take some time, and if it seems CPU bound on your machine that may be an interesting thing for you to get to the bottom of but probably doesn't involve the library's pretty straightforward IO-reading choices.

**Comment by justinkterry** [comment]
1) The drive I'm reading the 8GB file off is capable of sustained >150MB/s (yes MB not Mb) in transfer day to day tests, which means that it should take less than a minute to load into ram, but instead it's taking ~10 minutes. I'm not crazy that that means something strange is going on, right?
2) Provided that you agree somethings amiss, could you please tell me where load_word2vec_format() is defined I'd like to look at it? I searched in the github repo, did a grep search on the package and looked in the obvious .py files but didn't find it.

**Comment by piskvorky** [comment]
Yes, 10 minutes to load a file seems weird. The code here is [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/keyedvectors.py#L165).

It's not optimized much -- the loading is usually fast, plus people who need performance use the native gensim save/load which allows direct I/O memory mapping via `mmap`. Still, it'd be great if you could profile where the time goes in your case ([Python line profiler](https://github.com/rkern/line_profiler)) and let us know. Maybe there's some low-hanging CPU hog?

**Comment by justinkterry** [comment]
Thanks a ton for looking at this, I went to profile it and things I don't understand happened. I edited the script to be this:

```
import gensim
@profile
def fun():
    path='/home/station/Documents/wiki.en/wiki.en.vec'
    model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=False) 
    words=model.wv.most_similar(positive=['cs','method','syntax','string','function','list','dictionary','datatype'],topn=10000)
    out=[]
    for i in range(len(words)):
        out.append(words[i][0])
    return out
```
Then this happened in bash

```
station@Station:~/Documents$ kernprof -l googlify.py
Wrote profile results to googlify.py.lprof
station@Station:~/Documents$ cat googlify.py.lprof
��_�_line_profiler��	LineStats���)��}�(�timings�}��
                                                      googlify.py�K�fun���]�s�unit�G>�������ub.station@Station:~/Documents$ ^C

```

And the lprof file isn't readable in gedit either and I can't find whats going on in the line_profiler documentation. Please forgive my ignorance, but could you please tell me what I did wrong? Also the test ran in a fraction of the time than if I had just run it in python normally (a few seconds), which is another good sign that I've done something fairly wrong.

**Comment by piskvorky** [comment]
@justinkterry have a look at the README docs, https://github.com/rkern/line_profiler#line-profiler

**Comment by justinkterry** [comment]
I actually had already read through the readme, but I reread it and got the readout to work; the short run time was because of an error interrupt. The issue is that the `@profile` causes a runtime error, even though according to the readme I'm doing it right:

```
import gensim
@profile
def fun():
    path='/home/station/Documents/wiki.en/wiki.en.vec'
    model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=False) 
    words=model.wv.most_similar(positive=['cs','method','syntax','string','function','list','dictionary','datatype'],topn=10000)
    out=[]
    for i in range(len(words)):
        out.append(words[i][0])
    return out
```
Output
```
Traceback (most recent call last):
  File "/usr/local/bin/kernprof", line 11, in <module>
    load_entry_point('line-profiler==2.0', 'console_scripts', 'kernprof')()
  File "/usr/local/lib/python3.5/dist-packages/kernprof.py", line 224, in main
    prof.runctx('execfile_(%r, globals())' % (script_file,), ns, ns)
  File "/usr/lib/python3.5/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/kernprof.py", line 35, in execfile
    exec_(compile(f.read(), filename, 'exec'), globals, locals)
  File "googlify.py", line 2, in <module>
    @profile
NameError: name 'profile' is not defined
```
Readme excerpt telling me to do that: 

> kernprof will create an instance of LineProfiler and insert it into the __builtins__ namespace with the name profile. It has been written to be used as a decorator, so in your script, you decorate the functions you want to profile with @profile.
> 
> ```
> @profile
> def slow_function(a, b, c):
>     ...
> ```

What am I doing wrong here?

**Comment by piskvorky** [comment]
Hmm, OK. That's a more difficult one :)

I don't know, but my guess would be something wrong with the installation environment. Can you try some super simple example -- just a single module, no imports (no gensim), only one function decorated with `@profile`? And if that doesn't work, that means there's some mismatch between where `kernprof` was installed vs where Python is vs site-packages.

By the way, the best practice in Python is to use separate [virtual environments](https://virtualenv.pypa.io/en/stable/) (each with its own Python and dependencies), rather than a global `/use/local` install.

**Comment by justinkterry** [comment]
So the `@profile` gives a linting error in syder, so I'm pretty sure I've somehow done something rather creatively wrong. Would you mind downloading the .vec from my link and loading it yourself if you have enough RAM?

**Comment by piskvorky** [comment]
I don't know what syder is, but we're aiming at the smallest number of moving pieces possible, to get to the bottom of this.

Did you try decorating the minimal example I wrote about (no imports)?

**Comment by gojomo** [comment]
I suggest you time the load separately from the most-similar search. Also, the 1st most-similar search will trigger a one-time calculation- and memory-intensive creation of the unit-normed vectors – so it's a less interesting (one-time-longer) timing than the 2nd and subsequent most-similar searches.

**Comment by justinkterry** [comment]
@piskvorky It fails with a simple script as well:

```
station@Station:~/Documents$ cat test.py
@profile
def fun():
	run=True
	x, y = 0, 1
	while run:
		x, y = y, x + y
		if y>100:
			run=False
	return y
station@Station:~/Documents$ kernprof --view test.py
Wrote profile results to test.py.prof
         10 function calls (9 primitive calls) in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 kernprof.py:33(execfile)
        1    0.000    0.000    0.000    0.000 test.py:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.compile}
      2/1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {built-in method builtins.globals}
        1    0.000    0.000    0.000    0.000 {built-in method io.open}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'read' of '_io.BufferedReader' objects}


Traceback (most recent call last):
  File "/usr/local/bin/kernprof", line 11, in <module>
    load_entry_point('line-profiler==2.0', 'console_scripts', 'kernprof')()
  File "/usr/local/lib/python3.5/dist-packages/kernprof.py", line 224, in main
    prof.runctx('execfile_(%r, globals())' % (script_file,), ns, ns)
  File "/usr/lib/python3.5/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/kernprof.py", line 35, in execfile
    exec_(compile(f.read(), filename, 'exec'), globals, locals)
  File "test.py", line 1, in <module>
    @profile
NameError: name 'profile' is not defined
```

I've been looking through the documentation and

**Comment by justinkterry** [comment]
Wrong button. 

@piskvorky Spyder is an IDE that automatically uses pylint, in otherwords it means something is wrong at the system level. A simple no import test script wouldn't work either, I'm going to work on it more and come back here.

@piskvorky I reproduced it with the load only and I just forgot to use that code when testing it. Thanks for catching that.

**Comment by piskvorky** [comment]
My guess it's something to do with Spyder. As in, you installed the profiler into some Python environment, but Spyder uses another environment, so it doesn't see the profiler.

Can you try from the command line (avoiding Spyder for now)?

**Comment by justinkterry** [comment]
It doesn't work via the command line either, I thought I'd said that.

**Comment by piskvorky** [comment]
I don't think you did :)

Can you post the exact output of `pip freeze`, `which pip` and `which python`? And then the exact output of `python test.py`. All from the same shell (successive commands). Cheers.

**Comment by justinkterry** [comment]
Here's my attempt at trouble shooting, it was suggested to be a likely bug in kernprof or a failure in their documentation:
https://www.reddit.com/r/learnpython/comments/6qtmc2/line_profiler_library_not_working_with_python3_on/
Here's a current attempt at everything I can think of to try at once in one long bash instance, including everything you wanted:

https://pastebin.com/m3XdhCJE

kernprof appears to not currently be well maintained based on current github activity, which may explain the problem (I'm not this bad, I promise). Python has two built in profilers, cProfile, cProfile appears to be the right one to use for this (and the only one the computer I'm currently at could run). Here's the profiling done with cProfile:

```
justin@Justin:~/Documents$ cat gensimprofiler.py
import cProfile
import gensim
path='/home/justin/Documents/wiki.en/wiki.en.vec'
cProfile.run('model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=False)')
justin@Justin:~/Documents$ python3 gensimprofiler.py
         27713112 function calls in 607.580 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  607.580  607.580 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 <string>:12(__new__)
        2    0.000    0.000    0.000    0.000 __init__.py:1269(info)
        2    0.000    0.000    0.000    0.000 __init__.py:1501(getEffectiveLevel)
        2    0.000    0.000    0.000    0.000 __init__.py:1515(isEnabledFor)
        1    0.000    0.000    0.000    0.000 genericpath.py:111(_splitext)
        1    0.000    0.000    0.000    0.000 keyedvectors.py:114(__init__)
        1  473.538  473.538  607.580  607.580 keyedvectors.py:164(load_word2vec_format)
  2519370   71.358    0.000   76.979    0.000 keyedvectors.py:214(add_word)
  2519370    2.819    0.000    4.789    0.000 keyedvectors.py:97(__init__)
        1    0.000    0.000    0.000    0.000 parse.py:100(_coerce_args)
        1    0.000    0.000    0.000    0.000 parse.py:321(urlsplit)
        1    0.000    0.000    0.000    0.000 parse.py:89(_noop)
        1    0.000    0.000    0.000    0.000 posixpath.py:115(splitext)
        1    0.000    0.000    0.000    0.000 posixpath.py:221(expanduser)
        1    0.000    0.000    0.000    0.000 smart_open_lib.py:236(__init__)
        1    0.000    0.000    0.000    0.000 smart_open_lib.py:611(compression_wrapper)
        1    0.000    0.000    0.000    0.000 smart_open_lib.py:638(file_smart_open)
        1    0.000    0.000    0.000    0.000 smart_open_lib.py:66(smart_open)
  2519371    7.194    0.000    7.942    0.000 utils.py:231(any2unicode)
        1    0.000    0.000    0.000    0.000 {built-in method __new__ of type object at 0xa3ddc0}
        1    0.000    0.000  607.580  607.580 {built-in method builtins.exec}
  2519376    0.748    0.000    0.748    0.000 {built-in method builtins.isinstance}
  5038743    0.857    0.000    0.857    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {built-in method io.open}
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.zeros}
  2519370    0.418    0.000    0.418    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'find' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {method 'get' of 'dict' objects}
  2519371   12.995    0.000   12.995    0.000 {method 'readline' of '_io.BufferedReader' objects}
        2    0.000    0.000    0.000    0.000 {method 'rfind' of 'str' objects}
  2519370    1.292    0.000    1.292    0.000 {method 'rstrip' of 'bytes' objects}
  2519371   34.392    0.000   34.392    0.000 {method 'split' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {method 'startswith' of 'str' objects}
  2519370    1.970    0.000    1.970    0.000 {method 'update' of 'dict' objects}
```
Does that work?
