### ISSUE TITLE
FastText.load_fasttext_format fails if no .vec

### ISSUE THREAD

**Issue by bittlingmayer** [RaRe-Technologies/gensim#1497]
#### Steps/Code/Corpus to Reproduce

1. Train or download a fastText .bin file, eg `en.wiki.bin`

2. Call either`FastText.load_fasttext_format('example.bin')`, or  `FastText.load_fasttext_format('example')` assuming there is an `example.bin` but no neighbouring `example.vec`

#### Expected Results

The model loads, as suggested by the documentation (https://radimrehurek.com/gensim/models/wrappers/fasttext.html#gensim.models.wrappers.fasttext.FastText.load_fasttext_format) and current code (https://github.com/RaRe-Technologies/gensim/search?utf8=%E2%9C%93&q=if+not+model_file.endswith%28%27.bin%27%29%3A&type=).

#### Actual Results

When calling with `'example.bin'`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../gensim/models/wrappers/fasttext.py", line 240, in load_fasttext_format
    model.wv = cls.load_word2vec_format('%s.vec' % model_file, encoding=encoding)
  File ".../gensim/models/wrappers/fasttext.py", line 224, in load_word2vec_format
    return FastTextKeyedVectors.load_word2vec_format(*args, **kwargs)
  File ".../gensim/models/keyedvectors.py", line 205, in load_word2vec_format
    with utils.smart_open(fname) as fin:
  File ".../smart_open/smart_open_lib.py", line 140, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode)
  File ".../smart_open/smart_open_lib.py", line 644, in file_smart_open
    return compression_wrapper(open(fname, mode), fname, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'example.bin.vec'
```
That is, it does not expect to be called with `.bin`.

When calling with `'example'`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../gensim/models/wrappers/fasttext.py", line 240, in load_fasttext_format
    model.wv = cls.load_word2vec_format('%s.vec' % model_file, encoding=encoding)
  File ".../gensim/models/wrappers/fasttext.py", line 224, in load_word2vec_format
    return FastTextKeyedVectors.load_word2vec_format(*args, **kwargs)
  File ".../gensim/models/keyedvectors.py", line 205, in load_word2vec_format
    with utils.smart_open(fname) as fin:
  File ".../smart_open/smart_open_lib.py", line 140, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode)
  File ".../smart_open/smart_open_lib.py", line 644, in file_smart_open
    return compression_wrapper(open(fname, mode), fname, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'example.vec'
```

#### Versions

```
>>> import platform; print(platform.platform())
Darwin-16.6.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.13.1
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 0.19.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 2.2.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 0
```

**Comment by bittlingmayer** [comment]
Fixed in `develop` branch (`pip install https://github.com/RaRe-Technologies/gensim/archive/develop.zip`) but not in `master`.

**Comment by menshikh-iv** [comment]
In next release, this behavior will be fixed ([PR with fix](https://github.com/RaRe-Technologies/gensim/commit/e1d89c2308c01bddc741d3ca2499fe30843e038c))

**Comment by monajalal** [comment]
@bittlingmayer do you know how I can fix this?

```
$ python vector_test.py 
Traceback (most recent call last):
  File "vector_test.py", line 5, in <module>
    en_model = KeyedVectors.load_word2vec_format('wiki.en/wiki.en.vec')
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 1438, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/gensim/models/utils_any2vec.py", line 171, in _load_word2vec_format
    with utils.smart_open(fname) as fin:
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 181, in smart_open
    fobj = _shortcut_open(uri, mode, **kw)
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 301, in _shortcut_open
    return open(parsed_uri.uri_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'wiki.en/wiki.en.vec'
```

**Comment by bittlingmayer** [comment]
@monajalal Is the .vec actually there?

**Comment by menshikh-iv** [comment]
@monajalal I guess specify a full path (looks like `smart_open` cannot find your file)
