### ISSUE TITLE
IndexError in new version

### ISSUE THREAD

**Issue by relwell** [RaRe-Technologies/gensim#166]
Here's the traceback:

...
Traceback (most recent call last):
  File "/home/ubuntu/data-science-toolkit/wikia_dstk/lda/wiki_lda_server.py", line 158, in get_model_from_args
    distributed=True)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.8.9-py2.7.egg/gensim/models/ldamodel.py", line 303, in **init**
    self.update(corpus)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.8.9-py2.7.egg/gensim/models/ldamodel.py", line 531, in update
    self.log_perplexity(chunk, total_docs=lencorpus)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.8.9-py2.7.egg/gensim/models/ldamodel.py", line 451, in log_perplexity
    perwordbound = self.bound(chunk, subsample_ratio=subsample_ratio) / (subsample_ratio \* corpus_words)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.8.9-py2.7.egg/gensim/models/ldamodel.py", line 618, in bound
    gammad, _ = self.inference([doc])
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.8.9-py2.7.egg/gensim/models/ldamodel.py", line 363, in inference
    expElogbetad = self.expElogbeta[:, ids]
IndexError: index 700 is out of bounds for axis 1 with size 700
...

**Comment by gauravkoradiya** [comment]
```
Traceback (most recent call last):
  File "D:/Projects/docs_handler/email_data_experiment.py", line 38, in <module>
    lda = LdaModel(corpus=corpus, num_topics=5, id2word=id2word,iterations=5,chunksize=100000,eval_every=0,update_every=2)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 521, in __init__
    self.update(corpus, chunks_as_numpy=use_numpy)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 983, in update
    gammat = self.do_estep(chunk, other)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 744, in do_estep
    gamma, sstats = self.inference(chunk, collect_sstats=True)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 681, in inference
    expElogbetad = self.expElogbeta[:, ids]
IndexError: index 5000000 is out of bounds for axis 1 with size 5000000

```

Here same error i am getting. This is because of i have vocabulary size is 50,00,000 and have feature sie of MM corpus is 90,00,000. How to resolve it ?
