### ISSUE TITLE
assert left > 0 failing in models.LdaMulticore with large chunksize

### ISSUE THREAD

**Issue by TC-Rudel** [RaRe-Technologies/gensim#1680]
#### Description
I am getting an assertionError when running models.LdaMulticore with large values for chunksize

#### Steps/Code/Corpus to Reproduce
Run the following code on the [gutenberg corpus](https://drive.google.com/file/d/0B2MmJrCi88c3MklYaGw0SzB5dms/view?usp=sharing) (2GB zipped download from google drive)

Dictionary is attached
[dictionary.zip](https://github.com/RaRe-Technologies/gensim/files/1433354/dictionary.zip)

```
import gensim.corpora.dictionary as gsdict
from gensim import corpora, models
import logging

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

my_dictionary = gsdict.Dictionary.load('clean_vcompact_dictionary.pickle')

my_LD_corpus = corpora.MmCorpus("E:/Clean_Corpus/Full_Corpus_LD.mm")

if __name__ == "__main__":
    LDA_model = models.LdaMulticore(my_LD_corpus,num_topics=2000,id2word=my_dictionary,workers=2,
                                    chunksize=7000,decay=1.0,iterations=500,eta=0.01)
    LDA_model.save("repro.pickle")
```

#### Expected Results
LDA model is trained

#### Actual Results

assert left >0 fails.  Trace below:
```
C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\gensim\utils.py:862: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
2017-11-01 00:16:07,433 : INFO : loading Dictionary object from clean_vcompact_dictionary.pickle
2017-11-01 00:16:07,464 : INFO : loaded clean_vcompact_dictionary.pickle
2017-11-01 00:16:07,909 : INFO : loaded corpus index from E:/Clean_Corpus/Full_Corpus_LD.mm.index
2017-11-01 00:16:07,909 : INFO : initializing corpus reader from E:/Clean_Corpus/Full_Corpus_LD.mm
2017-11-01 00:16:07,909 : INFO : accepted corpus with 3443509 documents, 66457 features, 612903679 non-zero entries
2017-11-01 00:16:07,912 : INFO : using symmetric alpha at 0.0005
2017-11-01 00:16:07,914 : INFO : using serial LDA version on this node
2017-11-01 00:28:16,241 : INFO : running online LDA training, 2000 topics, 1 passes over the supplied corpus of 3443509 documents, updating every 20000 documents, evaluating every ~200000 documents, iterating 500x with a convergence threshold of 0.001000
2017-11-01 00:28:16,246 : INFO : training LDA model using 2 processes
C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\gensim\utils.py:862: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\gensim\utils.py:862: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
2017-11-01 00:28:17,035 : INFO : loading Dictionary object from clean_vcompact_dictionary.pickle
2017-11-01 00:28:17,036 : INFO : loading Dictionary object from clean_vcompact_dictionary.pickle
2017-11-01 00:28:17,070 : INFO : loaded clean_vcompact_dictionary.pickle
2017-11-01 00:28:17,079 : INFO : loaded clean_vcompact_dictionary.pickle
2017-11-01 00:28:17,606 : INFO : loaded corpus index from E:/Clean_Corpus/Full_Corpus_LD.mm.index
2017-11-01 00:28:17,606 : INFO : initializing corpus reader from E:/Clean_Corpus/Full_Corpus_LD.mm
2017-11-01 00:28:17,607 : INFO : accepted corpus with 3443509 documents, 66457 features, 612903679 non-zero entries
2017-11-01 00:28:17,621 : INFO : loaded corpus index from E:/Clean_Corpus/Full_Corpus_LD.mm.index
2017-11-01 00:28:17,621 : INFO : initializing corpus reader from E:/Clean_Corpus/Full_Corpus_LD.mm
2017-11-01 00:28:17,621 : INFO : accepted corpus with 3443509 documents, 66457 features, 612903679 non-zero entries
2017-11-01 00:28:19,786 : INFO : PROGRESS: pass 0, dispatched chunk #0 = documents up to #10000/3443509, outstanding queue size 1
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\multiprocessing\pool.py", line 103, in worker
    initializer(*initargs)
  File "C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\gensim\models\ldamulticore.py", line 279, in worker_e_step
    chunk_no, chunk, worker_lda = input_queue.get()
  File "C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
  File "C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\multiprocessing\connection.py", line 318, in _recv_bytes
    return self._get_more_data(ov, maxsize)
  File "C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\multiprocessing\connection.py", line 337, in _get_more_data
    assert left > 0
AssertionError
```

#### Versions
Windows-10-10.0.14393-SP0
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
NumPy 1.13.3
SciPy 1.0.0
C:\Winpython\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\gensim\utils.py:862: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
gensim 3.0.1
FAST_VERSION 0

**Comment by piskvorky** [comment]
Thanks for detailed report @TC-Rudel .

Other users have reported an issue with multiprocessing (Python's built-in module) in connection with LDA too. @menshikh-iv I can't seem to find the link -- can you link to that issue/PR here?

This seems serious and recurring. Let's fix ASAP.

**Comment by menshikh-iv** [comment]
I don't think that this is connected (because problems looks very different), but I'll link it here #1588 and #1136

**Comment by menshikh-iv** [comment]
I don't reproduced this problem, but recieve another errors
```
(lda-bug) ivan@P50:~/lda_bug$ python lda_b.py 
2017-11-01 17:58:24,398 : INFO : loading Dictionary object from clean_vcompact_dictionary.pickle
2017-11-01 17:58:24,427 : INFO : loaded clean_vcompact_dictionary.pickle
66457
2017-11-01 17:58:24,773 : INFO : loaded corpus index from Full_Corpus_LD.mm.index
2017-11-01 17:58:24,773 : INFO : initializing corpus reader from Full_Corpus_LD.mm
2017-11-01 17:58:24,773 : INFO : accepted corpus with 3443509 documents, 66457 features, 612903679 non-zero entries
2017-11-01 17:58:24,775 : INFO : using symmetric alpha at 0.0005
2017-11-01 17:58:24,777 : INFO : using serial LDA version on this node
2017-11-01 18:23:49,671 : INFO : running online LDA training, 2000 topics, 1 passes over the supplied corpus of 3443509 documents, updating every 20000 documents, evaluating every ~200000 documents, iterating 500x with a convergence threshold of 0.001000
2017-11-01 18:23:49,674 : INFO : training LDA model using 2 processes
2017-11-01 18:23:53,262 : INFO : PROGRESS: pass 0, dispatched chunk #0 = documents up to #10000/3443509, outstanding queue size 1
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
2017-11-01 18:23:59,806 : INFO : PROGRESS: pass 0, dispatched chunk #1 = documents up to #20000/3443509, outstanding queue size 2
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
2017-11-01 18:24:06,634 : INFO : PROGRESS: pass 0, dispatched chunk #2 = documents up to #30000/3443509, outstanding queue size 3
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
2017-11-01 18:24:13,214 : INFO : PROGRESS: pass 0, dispatched chunk #3 = documents up to #40000/3443509, outstanding queue size 4
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

```
Looks like a problem with serialization (python limits).

**Comment by menshikh-iv** [comment]
@TC-Rudel try to reduce `chunksize` (to avoid the problem with serialization) and `num_topics` (to reduce memory usage & speed up computations).

**Comment by menshikh-iv** [comment]
I benchmarked this code and see several problems
1. `scipy.special.psi` - "hottest" and slowest part, need to make more efficient implementation than in scipy
2. CPU overutilization (because numpy sometimes used OpenMPI, that makes many threads and we can see this situation), look to htop, `load average=13` with `workers=2`.

![screenshot from 2017-11-01 22-36-46](https://user-images.githubusercontent.com/15094669/32290756-d6c27a28-bf5c-11e7-9a2f-bf5d4e2a8152.png)

with flag `OMP_NUM_THREADS=1` this looks better
![screenshot from 2017-11-01 23-14-09](https://user-images.githubusercontent.com/15094669/32290842-232c1c16-bf5d-11e7-8419-b0e49782ce54.png)

 Also, I attach two profile dumps (with 30-40 minutes of running code from issue), without/with OMP option.

[lda_OMP.zip](https://github.com/RaRe-Technologies/gensim/files/1435265/lda_OMP.zip)
[lda_without_OMP.zip](https://github.com/RaRe-Technologies/gensim/files/1435266/lda_without_OMP.zip)

**Comment by johann-petrak** [comment]
I tried to train using LdaMulticore and got this error several times on the console before terminating:
```
Traceback (most recent call last):
  File "/home/johann/software/anaconda3/lib/python3.6/multiprocessing/queues.py", line 247, in _feed
    send_bytes(obj)
  File "/home/johann/software/anaconda3/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/johann/software/anaconda3/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```
It does not indicate the location inside the gensim code where this happens. 

My chunk size is 100, my dictionary has 2000094 entries, and I was trying to train 200 topics. 

I think even if this cannot be fixed, it should be possible to calculate in advance whether or not whatever data is going to get transferred will fit or not. So I assume the problem here is the size of the LDA model that needs to get transferred which is probably proportional to (2000094 * 200). 

My suggestion would be to calculate dictsize * ntopics * SIZEPERWROD + WHATEVEROTHEROVERHEAD before even starting the training and raise an error if that exceeds the limit.

**Comment by piskvorky** [comment]
I like that idea @johann-petrak . There's a known limitation to how multiprocessing sends data around (pickle, I think), which causes this error. But IIRC data limits are different for different Python versions / platforms, so that check may not be completely trivial.

It maybe easier to try to send the data and catch the error ex-post, than anticipate the formulas and limits in advance.

Hmm, now that I think about it, isn't that what's already happening now? So maybe all we need is a better error message?

**Comment by johann-petrak** [comment]
The example error message in my previous comment shows how this seems to get handled now:
* there seems to be a trace back message from the multiprocessing library
* there seems to be no exception that bubbles up into gensim code or gensim ignores it (no gensim trace back info is shown)
* therefore, processing continues, possibly with missing data

The error is raised because the struct library wants to first send a header that contains the size of the buffer to be sent as an integer, encoded as "!i" which means 4 byte big-endian encoding. 

I am not sure yet where exactly the data gets actually sent, but maybe the easiest would be to just check for  `len(buf) <= 2147483647` there and raise an exception with a helpful error message?

**Comment by piskvorky** [comment]
Aha. A silent failure is definitely not good. I thought we're failing with an exception (which would be OK).

I'd prefer to figure out why we're swallowing up the exception, and fix that. That sounds better to me than adding a check (which might still fail to capture other "swallowed" exceptions, leaving other errors unchecked).

**Comment by johann-petrak** [comment]
OK, I think this happens when sending the tuple `(chunk_no, chunk, self)` to the Queue instance: 
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/ldamulticore.py#L293

In the concrete run, the shape of self.state.sstats was (500, 2000094) so it is ntopics times vocabsize.
Numpy knows that the size of that array is 4000188000 so clearly this must fail. 

I have no idea why the exception does not bubble up there, but I also think it would make sense to 
use `self.state.sstats.nbytes` to check the size of the sstats array and maybe also check the size of chunk  as soon as we know them and raise and exception which would give feedback to the user much faster than having to wait until this actually fails (even if we get the exception to bubble up). 

The actual size of what gets put on the queue is whatever the pickler creates from the tuple, so it includes all the other fields of self as well. But checking a rough estimate would probably already help to prevent many cases where this fails (waiting for the tuple to get pickled already takes quite a while). 

So my suggestion would be to check if we can do this:
* as soon as we know the shape of self.state.sstats, use self.state.sstats.nbytes to check if we can possibly get this on the queue, if not raise an exception (this could probably happen very soon)
* at each iteration before sending over the queue check if self.state.sstats.nbytes plus the size of the chunk can be put on the queue and raise an exception if not
* the previous two checks will handle most cases except the border line cases where the additional integer and the other fields in self and LsaState just get the size over 2G. In that case the exception will happen inside Queue and we should figure out how to make it bubble up

**Comment by piskvorky** [comment]
The suggestion sounds good. Thanks for investigating.

What is the actual limit for pickle? Is it platform-dependent? Python-version dependent?

**Comment by johann-petrak** [comment]
I dont know about pickle limitations, but the problem here is not a pickle limitation but a limitation of pyro4: the code int the multiprocessing library creates a header for the queue element which contains the length of the data sent formatted as big endian 4 byte integer, so because of this there is the 2G limit.

**Comment by johann-petrak** [comment]
Sorry, not really pyro's fault: multiprocessing made the decision to format the length of the data as pyro4 serialization "!i" -- this restricts the data to 2G. 
I do not know why they made that design decision, maybe there are good reasons for that. 
But as it looks, I think we have to live with the restriction that one cannot send more than 2G in a single put() over a multiprocessing Queue if we use multiprocessing's Queue implementation.

This is the relevant code in multiprocessing's connection.py file:
` ` ` 
    def _send_bytes(self, buf):
        n = len(buf)
        # For wire compatibility with 3.2 and lower
        header = struct.pack("!i", n)
        if n > 16384:
            # The payload is large so Nagle's algorithm won't be triggered
            # and we'd better avoid the cost of concatenation.
            self._send(header)
            self._send(buf)
        else:
            # Issue #20540: concatenate before sending, to avoid delays due
            # to Nagle's algorithm on a TCP socket.
            # Also note we want to avoid sending a 0-length buffer separately,
            # to avoid "broken pipe" errors if the other end closed the pipe.
            self._send(header + buf)
` ` `

The  `  n = len(buf)`  command determines the length of the result of pickling what should get put on the queue, and then ` header = struct.pack("!i", n)`  tries to represent this as a pyro4 4 byte big-endian integer, which is impossible if n >= 2G. So the result of pickling the object to get queued must never be >= 2G. I do not think there is a way around that, except maybe implementing our own queue and whatever else that would entail.
