### ISSUE TITLE
Doc2Vec training hangs

### ISSUE THREAD

**Issue by tarun-t** [RaRe-Technologies/gensim#1701]
#### Description

Hi, I tried training a model, with 
```
from gensim.models import Doc2Vec

model = Doc2Vec(min_count=1, window=10, size=100, sample=1e-4, negative=5, workers=7)
model.build_vocab(tagged_docs)
model.train(tagged_docs, total_examples=model.corpus_count, epochs=10)
```
but I'm getting the following exception (after which Python hangs):

#### Actual Results

```
01:03:25 PM INFO gensim.models.doc2vec:collecting all words and their counts
01:03:25 PM INFO gensim.models.doc2vec:PROGRESS: at example #0, processed 0 words (0/s), 0 word types, 0 tags
01:03:26 PM INFO gensim.models.doc2vec:PROGRESS: at example #10000, processed 3433858 words (6104765/s), 76029 word types, 10000 tags
01:03:26 PM INFO gensim.models.doc2vec:PROGRESS: at example #20000, processed 6635183 words (5692429/s), 103582 word types, 20000 tags
01:03:27 PM INFO gensim.models.doc2vec:PROGRESS: at example #30000, processed 10021476 words (5520268/s), 126018 word types, 30000 tags
01:03:28 PM INFO gensim.models.doc2vec:PROGRESS: at example #40000, processed 13649301 words (5489036/s), 145348 word types, 40000 tags
01:03:28 PM INFO gensim.models.doc2vec:collected 157200 word types and 47050 unique tags from a corpus of 47050 examples and 16232493 words
01:03:28 PM INFO gensim.models.word2vec:Loading a fresh vocabulary
01:03:29 PM INFO gensim.models.word2vec:min_count=1 retains 157200 unique words (100% of original 157200, drops 0)
01:03:29 PM INFO gensim.models.word2vec:min_count=1 leaves 16232493 word corpus (100% of original 16232493, drops 0)
01:03:29 PM INFO gensim.models.word2vec:deleting the raw counts dictionary of 157200 items
01:03:29 PM INFO gensim.models.word2vec:sample=0.0001 downsamples 686 most-common words
01:03:29 PM INFO gensim.models.word2vec:downsampling leaves estimated 13004737 word corpus (80.1% of prior 16232493)
01:03:29 PM INFO gensim.models.word2vec:estimated required memory for 157200 words and 100 dimensions: 223180000 bytes
01:03:30 PM INFO gensim.models.word2vec:resetting layer weights
01:03:31 PM INFO gensim.models.word2vec:training model with 7 workers on 157200 vocabulary and 100 features, using sg=0 hs=0 sample=0.0001 negative=5 window=10
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tarun/.local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 884, in job_producer
    for sent_idx, sentence in enumerate(sentences):
  File "/home/tarun/.local/lib/python2.7/site-packages/gensim/utils.py", line 692, in __iter__
    for document in self.corpus:
TypeError: 'NoneType' object is not iterable
```
#### Versions

('Python', '2.7.6 (default, Oct 26 2016, 20:30:19) \n[GCC 4.8.4]')
('NumPy', '1.13.1')
('SciPy', '0.19.1')
('gensim', '2.3.0')
('cython', '0.27.3')

Thanks for the help in advance.

**Comment by menshikh-iv** [comment]
Thanks for report @tarun-t, can you share your `tagged_docs` (needed to reproduce your error)?

**Comment by menshikh-iv** [comment]
@tarun-t :+1:
