### ISSUE TITLE
"IndexError: Index is out of bounds" for any corpus.

### ISSUE THREAD

**Issue by apanimesh061** [RaRe-Technologies/gensim#171]
I have a corpus that has around 8000 tokens. I was successful in making a dictionary and a Market Matrix corpus but I always get an IndexError irrespective of size of the corpus. I tried it on a corpus of 30000 tokens, 1000 tokens as well as 8000 tokens but I still shows this error!

lda = gensim.models.ldamodel.LdaModel(corpus=mm, id2word=dictionary, num_topics=50, update_every=0, chunksize=19188, passes=200)

The complete Traceback:

Traceback (most recent call last):
  File "C:\Requirements\modelDeTopics.py", line 53, in <module>
    lda = gensim.models.ldamodel.LdaModel(corpus=mm, id2word=dictionary, num_topics=50, update_every=0, chunksize=19188, passes=200)
  File "C:\Requirements\Python27\lib\site-packages\gensim\models\ldamodel.py", line 303, in **init**
    self.update(corpus)
  File "C:\Requirements\Python27\lib\site-packages\gensim\models\ldamodel.py", line 532, in update
    self.log_perplexity(chunk, total_docs=lencorpus)
  File "C:\Requirements\Python27\lib\site-packages\gensim\models\ldamodel.py", line 451, in log_perplexity
    perwordbound = self.bound(chunk, subsample_ratio=subsample_ratio) / (subsample_ratio \* corpus_words)
  File "C:\Requirements\Python27\lib\site-packages\gensim\models\ldamodel.py", line 619, in bound
    gammad, _ = self.inference([doc])
  File "C:\Requirements\Python27\lib\site-packages\gensim\models\ldamodel.py", line 363, in inference
    expElogbetad = self.expElogbeta[:, ids]
IndexError: index 9 is out of bounds for axis 1 with size 9

**Comment by yick2232** [comment]
I met the same question.  My guess is the num_topics is small, you can try let num_topics large.

**Comment by tesslo** [comment]
Take out the `num_topics` parameter and let the module determine the number of features

**Comment by gauravkoradiya** [comment]
num_topic should  small than vocab length.
