### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by Hambath** [RaRe-Technologies/gensim#1844]
Key lines:
Mallet_Loc = r"/Users/myself/mallet-2.0.7"
lda = gensim.models.wrappers.LdaMallet(Mallet_Loc,corpus, num_topics=Nos_Topics, id2word = dictionary)

gives the following error

Traceback (most recent call last):
  File "/Users/myself/Documents/JH_LDA Processing Gensim Mallet v3.py", line 91, in <module>
    lda = gensim.models.wrappers.LdaMallet(Mallet_Loc,corpus, num_topics=Nos_Topics, id2word = dictionary)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gensim/models/wrappers/ldamallet.py", line 98, in __init__
    self.train(corpus)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gensim/models/wrappers/ldamallet.py", line 156, in train
    self.convert_input(corpus, infer=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gensim/models/wrappers/ldamallet.py", line 153, in convert_input
    check_output(args=cmd, shell=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gensim/utils.py", line 1174, in check_output
    raise error
subprocess.CalledProcessError: Command '/Users/jamiehamilton/mallet-2.0.7 import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /var/folders/hl/vxz79b3d7qd_ktk3dxs6gt680000gn/T/750b51_corpus.txt --output /var/folders/hl/vxz79b3d7qd_ktk3dxs6gt680000gn/T/750b51_corpus.mallet' returned non-zero exit status 126.

Cant find reference to similar - any ideas?

All the best
Jamie

import platform; print(platform.platform())
Darwin-14.5.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.13.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 0.19.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.0.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 0
>>>

**Comment by menshikh-iv** [comment]
This looks like a `Mallet` bug (gensim, in this case, is "transparent proxy").
Can you run this command manually?

**Comment by Hambath** [comment]
Many thanks for this. I am afraid that I can run Mallet directly successfully.
All the best
Jamie

**Comment by Hambath** [comment]
Ivan, hi!

If its any help here’s the rudimentary code I’m using and the log:

# LDA Processing v3.py
# Version using Mallet rather than Gensim's own LDA version

import os
import csv
from nltk.tokenize import RegexpTokenizer
from stop_words import get_stop_words
from nltk.stem.snowball import SnowballStemmer
from gensim import corpora, models, utils
from gensim.models import wrappers
import gensim
import lxml.html
from bs4 import BeautifulSoup
import codecs
import logging

logging.basicConfig(format="%(asctime)s : %(levelname)s : %(message)s", level=logging.INFO)
tokenizer = RegexpTokenizer(r'\w+')

# create English stop words list
en_stop = get_stop_words('en')

# Create p_stemmer of class PorterStemmer
p_stemmer = SnowballStemmer("english")

# List of files to process

Base_Dir = "/Users/jamiehamilton/Documents/OneDrive/Research/AnnualReports/Reports/Complete/LDA180116/CORPUS1B"
File_List_Loc= os.path.join(Base_Dir,"File_List.csv")
File_Save_Loc= os.path.join(Base_Dir,"SAVE_LDA")
File_Topic_Loc=os.path.join(Base_Dir,"TOPICS_LDA")
File_Dist_Loc= os.path.join(Base_Dir,"DIST_LDA.CSV")
File_Stemmed_Loc=os.path.join(Base_Dir,"STEMMED_LDA.TXT")
Mallet_Loc = r"/Users/jamiehamilton/mallet-2.0.7"

# Create File List from all the text files in the directory

File_List_CSV = open(File_List_Loc, "w")
writer = csv.writer(File_List_CSV)
for file in os.listdir(Base_Dir):
    filename = os.fsdecode(file)
    fullname = [os.path.join(Base_Dir,filename)]
    if filename.endswith(".txt"):
        writer.writerow(fullname)

File_List_CSV.close()
Nos_Topics = 150
Nos_Iteration = 200
texts = []
file_paths = [os.path.join(Base_Dir,fname) for fname in os.listdir(Base_Dir) if fname.endswith(".txt")]
documents = [codecs.open(file_path, 'r', encoding="utf8", errors='ignore').read() for file_path in file_paths ]

N = 0
for doc in documents:

    N=N+1

    # clean and tokenize document string
    raw = doc.lower()

    # tokenise the text as a bag of words
    tokens = tokenizer.tokenize(raw)

    # remove short words from tokens
    tokens = [i for i in tokens if len(i)>2]

    # remove stop words from tokens
    stopped_tokens = [i for i in tokens if not i in en_stop]

    # stem tokens
    stemmed_tokens = [p_stemmer.stem(i) for i in stopped_tokens]

    # add tokens to list
    texts.append(stemmed_tokens)

print(str(N) + " files included into list of files for processing")
File_List_CSV.close()

# turn our tokenized documents into a id <-> term dictionary
dictionary = corpora.Dictionary(texts)

# convert tokenized documents into a document-term matrix
corpus = [dictionary.doc2bow(text) for text in texts]

# generate LDA model
lda = gensim.models.wrappers.LdaMallet(Mallet_Loc, corpus, num_topics=Nos_Topics, id2word = dictionary)

File_Dist = open(File_Dist_Loc,"wt", newline='', encoding='utf-8')
File_Dist_CSV = csv.writer(File_Dist, delimiter = ',')
Output = lda.print_topics(num_topics=-1, num_words=20)
Output = bytes(str(Output), 'utf-8').decode('utf-8','ignore')
OutputRow = Output.split(')')

# First print out the topics
for Outrow in OutputRow:
    File_Dist_CSV.writerow([Outrow])

# And then the topics by documents (texts)
for n in range(N):
    File_Dist_CSV.writerow([n,lda[corpus[n]]])

File_Dist.close()

ma# Distribution of words - set up list and make a tally across the corpus and save to file as well

DIST = [0]*len(dictionary)
for i in range(len(corpus)):
    for j in range(len(corpus[i])):
        DIST[corpus[i][j][0]]=DIST[corpus[i][j][0]]+corpus[i][j][1]

temp = open(File_Stemmed_Loc,"w")
for i in range(len(DIST)):
    Word = dictionary[i].encode('utf-8','ignore')
    j= temp.write(str(i)+' , '+str(Word)+' , '+str(DIST[i])+'\n')

temp.close()

# Save the model

lda.save(File_Save_Loc)

and log:

242 files included into list of files for processing
2018-01-18 17:25:09,461 : INFO : adding document #0 to Dictionary(0 unique tokens: [])
2018-01-18 17:25:09,715 : INFO : built Dictionary(4237 unique tokens: ['sharehold', 'first', 'annual', 'report', 'sinc']...) from 242 documents (total 76413 corpus positions)
2018-01-18 17:25:09,903 : INFO : serializing temporary corpus to /var/folders/hl/vxz79b3d7qd_ktk3dxs6gt680000gn/T/73a936_corpus.txt
2018-01-18 17:25:10,154 : INFO : converting temporary corpus to MALLET format with /Users/jamiehamilton/mallet-2.0.7 import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /var/folders/hl/vxz79b3d7qd_ktk3dxs6gt680000gn/T/73a936_corpus.txt --output /var/folders/hl/vxz79b3d7qd_ktk3dxs6gt680000gn/T/73a936_corpus.mallet
Traceback (most recent call last):
  File "/Users/jamiehamilton/Documents/JH_LDA Processing Gensim Mallet v4.py", line 86, in <module>
    lda = gensim.models.wrappers.LdaMallet(Mallet_Loc, corpus, num_topics=Nos_Topics, id2word = dictionary)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gensim/models/wrappers/ldamallet.py", line 98, in __init__
    self.train(corpus)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gensim/models/wrappers/ldamallet.py", line 156, in train
    self.convert_input(corpus, infer=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gensim/models/wrappers/ldamallet.py", line 153, in convert_input
    check_output(args=cmd, shell=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gensim/utils.py", line 1174, in check_output
    raise error
subprocess.CalledProcessError: Command '/Users/jamiehamilton/mallet-2.0.7 import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /var/folders/hl/vxz79b3d7qd_ktk3dxs6gt680000gn/T/73a936_corpus.txt --output /var/folders/hl/vxz79b3d7qd_ktk3dxs6gt680000gn/T/73a936_corpus.mallet' returned non-zero exit status 126.

All the best – and hoping you can help …..

Jamie

**Comment by menshikh-iv** [comment]
> Many thanks for this. I am afraid that I can run Mallet directly successfully.

Aha, this sounds suspicious, thanks for the report @Hambath!

**Comment by Hambath** [comment]
Ivan,

I’ve sorted it. The reference to the Mallet programme was lacking a fullstop in the directory name. All my fault.

Many thanks for your kind attention.

Best regards

Jamie

**Comment by piskvorky** [comment]
We really should be producing a better error message for such (common, easy to test) scenarios.

**Comment by menshikh-iv** [comment]
@piskvorky in general I agree, good errors messages are important, but in the current case, we can't improve anything: if `Mallet` (or any binary from `wrappers`) failed silently - we can't know what's a reason.

**Comment by piskvorky** [comment]
The way I understood it, @Hambath was passing an incorrect executable path. We could definitely check that easily.

@Hambath what does `The reference to the Mallet programme was lacking a fullstop in the directory name.` mean exactly? Did you pass an incorrect path to the Mallet executable?

**Comment by menshikh-iv** [comment]
@piskvorky we already have an issue with checking the path/permissions to executable - #1485.

**Comment by bbiney1** [comment]
Hi, apologies for being repetitive, it feels like I'm close to getting mallet to work via python. I can only get mallet to work via the command line right now.

I have python 3 on a windows 10 computer and this error is leaving me in a position in which i can only use mallet via command line. I am using the git bash command line as opposed to command prompt though. 
`from gensim.models.wrappers import LdaMallet
from pathlib import Path
home = str(Path.home()) # '~' is to make it so that this symbol points to my home path, and my home path is on /c/users/biney/. The folder mallet_unzipped is located there as well.
MALLET_BINARY_PATH = home + "/mallet_unzipped/mallet-2.0.8/bin/mallet"` # this is in accordance with documentation: https://radimrehurek.com/gensim/models/wrappers/ldamallet.html
`Lda_mallet = LdaMallet(MALLET_BINARY_PATH, corpus=doc_term_matrix, id2word=doc_dict, iterations=30)`

Originally I had MALLET_BINARY_PATH set to "~/mallet_unzipped/mallet-2.0.8/bin/mallet" and was getting the error in this question. i soon found another error message that said "~ is unrecognized," then I changed the MALLET_BINARY_PATH variable to what you see now.

I am now getting a different error message for my code: 

`Traceback (most recent call last):
  File "text_mining.py", line 622, in <module>
    main()
  File "text_mining.py", line 557, in main
    mallet_LDA_implementation(name_of_lda="mallet_lda_no_filter_t10", create_dic
t=False, remove_low_freq=False)
  File "text_mining.py", line 454, in mallet_LDA_implementation
    Lda_mallet = LdaMallet(MALLET_BINARY_PATH, corpus=doc_term_matrix, id2word=d
oc_dict, iterations=30)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 126, in __init__
    self.train(corpus)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 279, in train
    self.word_topics = self.load_word_topics()
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 337, in load_word_topics
    with utils.smart_open(self.fstate()) as fin:
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 231, in smart_open
    binary, filename = _open_binary_stream(uri, binary_mode, **kw)
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 318, in _open_binary_stream
    fobj = io.open(parsed_uri.uri_path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\biney\\AppDa
ta\\Local\\Temp\\b63494_state.mallet.gz`

the directory that's being brought to question (...appdata/local/temp/) seems to be used by mallet automatically everytime I run my python prog or use mallet via command line. an input and output file are always put there, and they usually have a title like b63494. I think all of that might be normal behavior, perhaps the way that mallet automatically stores objects.
But not a single bit of my code works with the appdata folder, and I'm not sure what this object is. 
Then there's also the question of "why are there two slashes throughout the url? that's not what I wanted...." 

So really I have the same problem described by OP, but a different error: FileNotFoundError. Could anyone tell me what this actually means/what the b63494 file might be? And is there anything I can do right now to fix this?

**Comment by menshikh-iv** [comment]
@bbiney1 some files in `C:\\Users\\biney\\AppData\\Local\\Temp\\` produced by Mallet, after - we need to read it from gensim, please do several things
1. Enable log to INFO level and put the log here
2. After an exception `No such file or directory: ...` check manually is this file exist (or not), write result here

double slash happens because windows use `\` for path delimiting +  "escaping" reasons, see an example
```python
>>> "\"
  File "<stdin>", line 1
    "\"
      ^
SyntaxError: EOL while scanning string literal
>>> "\\"
'\\'
>>> print("\\")
\
>>> 

```

**Comment by iamyevyev** [comment]
So I think I am having a similar issue to Hambath and it would've been just great if he actually outlined what he changed in order to fix it instead of 'oh my fault I fixed it'.

Here is where I am at with this 



---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-50-dc35c1ce9e35> in <module>()
      3 
      4 path_to_mallet_binary = 'C:\\Users\\c17999\\Desktop\\zResearch\\1Projects In Progress\\Sensors Project\\mallet-2.0.8\\bin\\mallet'
----> 5 model = LdaMallet(path_to_mallet_binary, corpus=corpus, num_topics=40, id2word=id2word)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in __init__(self, mallet_path, corpus, num_topics, alpha, id2word, workers, prefix, optimize_interval, iterations, topic_threshold)
    124         self.iterations = iterations
    125         if corpus is not None:
--> 126             self.train(corpus)
    127 
    128     def finferencer(self):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in train(self, corpus)
    265 
    266         """
--> 267         self.convert_input(corpus, infer=False)
    268         cmd = self.mallet_path + ' train-topics --input %s --num-topics %s  --alpha %s --optimize-interval %s '\
    269             '--num-threads %s --output-state %s --output-doc-topics %s --output-topic-keys %s '\

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in convert_input(self, corpus, infer, serialize_corpus)
    254             cmd = cmd % (self.fcorpustxt(), self.fcorpusmallet())
    255         logger.info("converting temporary corpus to MALLET format with %s", cmd)
--> 256         check_output(args=cmd, shell=True)
    257 
    258     def train(self, corpus):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\utils.py in check_output(stdout, *popenargs, **kwargs)
   1830             error = subprocess.CalledProcessError(retcode, cmd)
   1831             error.output = output
-> 1832             raise error
   1833         return output
   1834     except KeyboardInterrupt:

CalledProcessError: Command 'C:\Users\c17999\Desktop\zResearch\1Projects In Progress\Sensors Project\mallet-2.0.8\bin\mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\c17999\AppData\Local\Temp\1c0da0_corpus.txt --output C:\Users\c17999\AppData\Local\Temp\1c0da0_corpus.mallet' returned non-zero exit status 1.

...

???

**Comment by iamyevyev** [comment]
I believe this one is similar to Hambath's... but can't figure out how to fix it


import os
os.environ.update({'MALLET_HOME':r'C:/Users/c17999/Desktop/zResearch/1Projects In Progress/Sensors Project/mallet-2.0.8/'})

mallet_path = 'C:\\Users\\c17999\\Desktop\\zResearch\\1Projects In Progress\\Sensors Project\\mallet-2.0.8\\bin\\mallet' # update this path

ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=40, id2word=id2word)



results in 


CalledProcessError                        Traceback (most recent call last)
<ipython-input-54-eba836272a0b> in <module>()
      4 mallet_path = 'C:\\Users\\c17999\\Desktop\\zResearch\\1Projects In Progress\\Sensors Project\\mallet-2.0.8\\bin\\mallet' # update this path
      5 
----> 6 ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=40, id2word=id2word)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in __init__(self, mallet_path, corpus, num_topics, alpha, id2word, workers, prefix, optimize_interval, iterations, topic_threshold)
    124         self.iterations = iterations
    125         if corpus is not None:
--> 126             self.train(corpus)
    127 
    128     def finferencer(self):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in train(self, corpus)
    265 
    266         """
--> 267         self.convert_input(corpus, infer=False)
    268         cmd = self.mallet_path + ' train-topics --input %s --num-topics %s  --alpha %s --optimize-interval %s '\
    269             '--num-threads %s --output-state %s --output-doc-topics %s --output-topic-keys %s '\

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in convert_input(self, corpus, infer, serialize_corpus)
    254             cmd = cmd % (self.fcorpustxt(), self.fcorpusmallet())
    255         logger.info("converting temporary corpus to MALLET format with %s", cmd)
--> 256         check_output(args=cmd, shell=True)
    257 
    258     def train(self, corpus):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\utils.py in check_output(stdout, *popenargs, **kwargs)
   1830             error = subprocess.CalledProcessError(retcode, cmd)
   1831             error.output = output
-> 1832             raise error
   1833         return output
   1834     except KeyboardInterrupt:

CalledProcessError: Command 'C:\Users\c17999\Desktop\zResearch\1Projects In Progress\Sensors Project\mallet-2.0.8\bin\mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\c17999\AppData\Local\Temp\f61a16_corpus.txt --output C:\Users\c17999\AppData\Local\Temp\f61a16_corpus.mallet' returned non-zero exit status 1.

**Comment by Jcvizon06** [comment]
Me too same CalledProcessError

**Comment by paulmattheww** [comment]
Same error here.  I also tried all of the advice on this and the related forums, but appear to be at the end of the road.  I'm in a JupyterLab instance on GCP...

```
import os

os.environ.update({'MALLET_HOME': r'/home/jupyter/new_mallet/mallet-2.0.8/'})

mallet_path = "\\home\\jupyter\\new_mallet\\mallet-2.0.8\\bin\\mallet" # update this path
ldamallet = LdaMallet(mallet_path, corpus=corpus, num_topics=25, id2word=id2word)

pp(ldamallet.show_topics(formatted=False))
```

**Comment by AlexM30** [comment]
Same issue as @iamyevyev @Jcvizon06   @paulmattheww , have even tried all possible solutions from this thread and others.. nothing seems to work...

**Comment by mpenkov** [comment]
It looks like there have been multiple attempts to hijack this issue. The original issue is marked as closed because it was caused by [user error](https://github.com/RaRe-Technologies/gensim/issues/1844#issuecomment-358912945):

> Ivan, I’ve sorted it. The reference to the Mallet programme was lacking a fullstop in the directory name. All my fault.

@alexM30 If you are having a similar problem, please open a new ticket, and be sure to fill out the template.
