### ISSUE TITLE
Running word2vec2tensor produces UnicodeDecodeError

### ISSUE THREAD

**Issue by alexbrandsen** [RaRe-Technologies/gensim#1847]
Hi,

When I run 

`python -m gensim.scripts.word2vec2tensor --input dans-word2vec.model --output tsv`

It returns the following error:

`2018-01-19 17:02:50,687 : MainThread : INFO : running /home/brandsena/exp/lib/python3.4/site-packages/gensim/scripts/word2vec2tensor.py --input dans-word2vec.model --output tsv
2018-01-19 17:02:50,709 : MainThread : INFO : loading projection weights from dans-word2vec.model
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/brandsena/exp/lib/python3.4/site-packages/gensim/scripts/word2vec2tensor.py", line 83, in <module>
    word2vec2tensor(args.input, args.output, args.binary)
  File "/home/brandsena/exp/lib/python3.4/site-packages/gensim/scripts/word2vec2tensor.py", line 55, in word2vec2tensor
    model = gensim.models.KeyedVectors.load_word2vec_format(word2vec_model_path, binary=binary)
  File "/home/brandsena/exp/lib/python3.4/site-packages/gensim/models/keyedvectors.py", line 196, in load_word2vec_format
    header = utils.to_unicode(fin.readline(), encoding=encoding)
  File "/home/brandsena/exp/lib/python3.4/site-packages/gensim/utils.py", line 243, in any2unicode
    return unicode(text, encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

I'm not sure what's going on or how to fix this..

Thanks,

Alex.

**Comment by menshikh-iv** [comment]
@alexbrandsen please share your `dans-word2vec.model`

**Comment by alexbrandsen** [comment]
[dans-word2vec.model.zip](https://github.com/RaRe-Technologies/gensim/files/1651382/dans-word2vec.model.zip)

Sorry, thought I uploaded it with the original message, but something must have gone wrong.. Thanks for looking into this!

**Comment by menshikh-iv** [comment]
@alexandercbooth how you produce this file? Probably there were more files (`dans-word2vec.model.*`), can you provide it too?

**Comment by alexbrandsen** [comment]
Ah ok, thanks for the information!
