### ISSUE TITLE
EOFError while on make_wiki

### ISSUE THREAD

**Issue by psukys** [RaRe-Technologies/gensim#1862]
#### Description
Midway running `gensim.scripts.make_wiki` on latest WikiPedia article dump, EOFError was spit out, which stopped the processing.

```
2018-01-28 15:45:35,500 : INFO : resulting dictionary: Dictionary(2000000 unique tokens: [u'tripolitan', u'ftdna', u'padanagan', u'soestdijk', u'farmobil']...)
2018-01-28 15:45:35,573 : INFO : adding document #4180000 to Dictionary(2000000 unique tokens: [u'tripolitan', u'ftdna', u'padanagan', u'soestdijk', u'farmobil']...)
Process InputQueue-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/psukys/.local/lib/python2.7/site-packages/gensim/utils.py", line 845, in run
    wrapped_chunk = [list(chunk)]
  File "/home/psukys/.local/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 361, in <genexpr>
    ((text, self.lemmatize, title, pageid, tokenization_params)
  File "/home/psukys/.local/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 221, in extract_pages
    for elem in elems:
  File "/home/psukys/.local/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 206, in <genexpr>
    elems = (elem for _, elem in iterparse(f, events=("end",)))
  File "<string>", line 100, in next
EOFError: compressed file ended before the logical end-of-stream was detected
```

#### Steps/Code/Corpus to Reproduce
Run on [latest](https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2) (21-Jan-2018 21:27         14705396388)
```
python -m gensim.script.make_wiki
```

**Comment by menshikh-iv** [comment]
@psukys thanks for report, what's gensim/python version you used?

**Comment by psukys** [comment]
@menshikh-iv I used:

- Python 2.7.14 (On Fedora 27 OS)
- gensim 3.2.0 (Installed via *pip*)

**Comment by menshikh-iv** [comment]
@psukys I'll try to reproduce it (I wait while the Wiki downloaded).

**Comment by psukys** [comment]
@menshikh-iv do mind that it failed after quite some time (after around 4 million documents).

**Comment by psukys** [comment]
the *archive integrity* check is taking longer than expected (at this point probably hours 🐳 )

I am as well trying to do the same on Azure's Ubuntu 16.04 VM and it surpassed the document location that occurred originally in this issue. The only difference is that this VM uses Python 2.7.12, but I highly doubt that this is the issue. Eitherway I will update when the training is over.

**Comment by menshikh-iv** [comment]
@psukys I tested it, all works fine, probably your file is broken.

FYI: 
- file size: `14705396388`
- md5sum: `466f01f50eba19e899ab4a212291a7d7`
