### ISSUE TITLE
Doesn't work word2vectensor.py

### ISSUE THREAD

**Issue by Shikugawa** [RaRe-Technologies/gensim#1872]
#### Description
TODO: change commented example
Used word2vectensor.py to generate tensor and metadata files

#### Steps/Code/Corpus to Reproduce

python word2vec2tensor.py -i trained_tensor.w2v -o texts_plot

#### Actual Results

2018-02-02 11:52:23,501 : MainThread : INFO : running word2vec2tensor.py -i trained_tensor.w2v -o texts_plot
2018-02-02 11:52:23,504 : MainThread : INFO : loading projection weights from trained_tensor.w2v
2018-02-02 11:53:04,497 : MainThread : INFO : loaded (73935, 400) matrix from trained_tensor.w2v
Traceback (most recent call last):
  File "word2vec2tensor.py", line 75, in <module>
    word2vec2tensor(args.input, args.output, args.binary)
  File "word2vec2tensor.py", line 53, in word2vec2tensor
    file_metadata.write(gensim.utils.to_utf8(word) + gensim.utils.to_utf8('\n'))
TypeError: write() argument must be str, not bytes

#### Versions

>>> import platform; print(platform.platform())
Darwin-15.6.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 21 2017, 18:29:43)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.13.1
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 0.19.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.1.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1

**Comment by menshikh-iv** [comment]
@Shikugawa why you close this?

related issue - #1847
