### ISSUE TITLE
Missing Attributes when loading old model in gensim 3.3 (retro-compatibility issue)

### ISSUE THREAD

**Issue by madewild** [RaRe-Technologies/gensim#1898]
#### Description
AttributeError breaking retro-compatibility of old (0.10.3) trained model

#### Steps/Code/Corpus to Reproduce
```
from gensim.models import word2vec

model = word2vec.Word2Vec.load(path_to_model)
```

#### Expected Results
Model loaded

#### Actual Results
```
Traceback (most recent call last):
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/models/word2vec.py", line 975, in load
    return super(Word2Vec, cls).load(*args, **kwargs)
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 629, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 278, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/utils.py", line 396, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/utils.py", line 461, in _load_specials
    setattr(self, attrib, None)
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/utils.py", line 1368, in new_func1
    return func(*args, **kwargs)
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 450, in cum_table
    self.vocabulary.cum_table = value
AttributeError: 'Word2Vec' object has no attribute 'vocabulary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/models/word2vec.py", line 979, in load
    return load_old_word2vec(*args, **kwargs)
  File "/home/max/virtualenvs/experts-python3/lib/python3.5/site-packages/gensim/models/deprecated/word2vec.py", line 195, in load_old_word2vec
    new_model.min_alpha_yet_reached = old_model.min_alpha_yet_reached
AttributeError: 'Word2Vec' object has no attribute 'min_alpha_yet_reached'
```

#### Versions
```
>>> import platform; print(platform.platform())
Linux-4.9.0-4-amd64-x86_64-with-debian-9.3
>>> import sys; print("Python", sys.version)
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.0
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.0.0
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.3.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```

**Comment by menshikh-iv** [comment]
Hello, thanks for report, this is really strange, we definitely handle this case in our tests
https://github.com/RaRe-Technologies/gensim/blob/1afaacc8017ff2b51e8677b8b36cd3b9671b20be/gensim/test/test_word2vec.py#L734-L755

Can you share your model with us please (needed for reproducing the problem) and specify the version, when you save this model (more concretely, what is `x` in `2.x`?)

**Comment by madewild** [comment]
Unfortunately, I cannot share this specific model (sensitive information inside) but I will try to find the version it was trained with and provide a model to reproduce the issue (probably tomorrow).

**Comment by madewild** [comment]
After checking with the colleague who trained this model, it appears that he was still using gensim 0.10.3!!! Are you still interested in a faulty model example or is the retro-compatibility not meant to stretch thus far?

**Comment by menshikh-iv** [comment]
@madewild no, we want to support models from previous major version, but not so far away :) Thank you!
