### ISSUE TITLE
_pickle.PicklingError

### ISSUE THREAD

**Issue by ashigirl96** [RaRe-Technologies/gensim#1948]
The gensim test cannot passed.

```python
$python setup.py test
[snip]
test_show_topics (gensim.test.test_ldamodel.TestLdaModel) ... ok
testAlpha (gensim.test.test_ldamodel.TestLdaMulticore) ... Traceback (most recent call last):
  File "/home/reon/.anaconda3/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/reon/.anaconda3/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function __RandomState_ctor at 0x7f067f57b1e0>: it's not the same object as numpy.random.__RandomState_ctor
```

#### Versions

Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0]
NumPy 1.14.1
SciPy 1.0.0
gensim 3.4.0
FAST_VERSION 1

**Comment by p-h** [comment]
How did you fix it?
