### ISSUE TITLE
'Word2VecKeyedVectors' object has no attribute 'vectors'

### ISSUE THREAD

**Issue by lzfelix** [RaRe-Technologies/gensim#1994]
I have a word2vec model which I was able to load into Gensim, normalize and retrieve word vectors with `model.init_sims(replace=True)` and `model[word]` previously. After updating to gensim 3.4.0 I'm receiving the following error messages for these operations:

```
Traceback (most recent call last):
  File "/Users/lzfelix/anaconda3/envs/mirror/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-4a9edd1d9ae5>", line 1, in <module>
    vsm.init_sims()
  File "/Users/lzfelix/anaconda3/envs/mirror/lib/python3.5/site-packages/gensim/models/keyedvectors.py", line 1048, in init_sims
    self.vectors_norm = (self.vectors / sqrt((self.vectors ** 2).sum(-1))[..., newaxis]).astype(REAL)
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'vectors'
```

and 

```
```

**Comment by menshikh-iv** [comment]
Hello @lzfelix, can you say, what's gensim version you used before for training/saving of your model?

**Comment by lzfelix** [comment]
Hi @menshikh-iv, a colleague of mine has trained the model, so I'm not completely sure about the details. I know that it was trained using word2vec C implementation from Google and then I converted it to gensim binary format using gensim 3.1.0.

**Comment by menshikh-iv** [comment]
@lzfelix thanks for the info

**Comment by lzfelix** [comment]
@menshikh-iv, sure! Anything that I can help!

**Comment by menshikh-iv** [comment]
related issue #2000

**Comment by lzfelix** [comment]
Thanks a lot, @menshikh-iv, I'll start tracking the other issue, which already has a pull request referencing it. Maybe you can close this issue for now just to keep things in one place.

**Comment by menshikh-iv** [comment]
PR with fix -  #2012, @lzfelix I'll close issues when fix will be merged to `deveop`

**Comment by manneshiva** [comment]
@menshikh-iv This issue may or may not be related to #2012. @lzfelix Can you please outline the steps to reproduce this issue? More specifically, provide the file/similar file that you are trying to load and the code using which you are loading the file. Thanks.

**Comment by lzfelix** [comment]
Hi @manneshiva, after loading a word2vec binary (details on this later), I get the following error message if I try to pre-compute vectors similarity with `model.init_sims(replace=True)` or even retrieve a word-vector with `model[word]`. Namely:

```python
    model = KeyedVectors.load(constants.DEFAULT_WORD2VEC_PATH)
    model.init_sims(replace=True)   # < error happens here
    vector = model['banana']        # < or here if the previous line is not used.
```

**Details on the model:** This binary file was obtained from a model trained with Google's word2vec C code and then converted to Gensim format. Since it's being used for a private project, I might only be able to share the model with you through some private mean, ie: Google Drive link via e-mail.

**Comment by menshikh-iv** [comment]
@lzfelix please sent me a link to `ivan@rare-technologies.com` (don't worry, we will not share your file).

**Comment by lzfelix** [comment]
HI @menshikh-iv, thank you. I have just sent the email.

**Comment by menshikh-iv** [comment]
@lzfelix reproduced, thanks! We'll fix it.

**Comment by lzfelix** [comment]
Great! Thanks a lot.

**Comment by rachhitgarg** [comment]
what if i want to update the model loaded with syntax (gensim.models.KeyedVectors.load_word2vec_format) by new sentences
I tried : showing error

**model.build_vocab(more_sentences, update=True)
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'build_vocab'**

**Comment by menshikh-iv** [comment]
@rachhitgarg `load_word2vec_format` returns only vectors (not full model), you can't continue training, see https://radimrehurek.com/gensim/models/keyedvectors.html

**Comment by nsmetanin** [comment]
Any progress on this bug?

**Comment by lzfelix** [comment]
Not that I am aware of.
