### ISSUE TITLE
load_fasttext_model() -> save() failed with no attribute generate_tokens()

### ISSUE THREAD

**Issue by dsindex** [RaRe-Technologies/gensim#2013]
- i trained a fasttext model(sent2vec) on huge corpus and got 15G model.
  - trained by sent2vec : https://github.com/epfml/sent2vec

- and tried to load the fasttext model and save it using bellow code 
```
#!/usr/bin/env python
#-*- coding: utf8 -*-

import os
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
from optparse import OptionParser

from gensim import models
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
from sparser import Sparser
import reader

# global variable
VERBOSE = 0

def load_wv(wv_path) :
        wv = models.fasttext.FastText.load_fasttext_format(wv_path, encoding='utf-8')
        if VERBOSE : print wv[u'가다']
        return wv

def save_wv(wv, save_path) :
        wv.save(save_path)

if __name__ == '__main__':

        parser = OptionParser()
        parser.add_option("--verbose", action="store_const", const=1, dest="verbose", help="verbose mode")
        parser.add_option("-w", "--wvectors", dest="wv_path", help="word vector(fasttext binary format) path", metavar="WV_PATH")
        parser.add_option("-s", "--save", dest="save_path", help="save(gensim format) path", metavar="SAVE_PATH")
        (options, args) = parser.parse_args()

        if options.verbose : VERBOSE = 1

        wv_path = options.wv_path
        save_path = options.save_path
        if not wv_path or not save_path :
                parser.print_help()
                sys.exit(1)

        wv = load_wv(wv_path)
        save_wv(wv, save_path)
```

- but, i got following errors
```
$ python fasttext2gensim.py -w news_model_morph.bin -s news_model_morph.gensim.bin
2018-04-02 19:12:44,623 : INFO : loading 853067 words for fastText model from news_model_morph.bin
2018-04-02 19:13:13,861 : INFO : loading weights for 853067 words for fastText model from news_model_morph.bin
2018-04-02 19:13:39,057 : INFO : loaded (853067, 700) weight matrix for fastText model from news_model_morph.bin
2018-04-02 19:13:39,057 : INFO : saving FastText object under news_model_morph.gensim.bin, separately None
2018-04-02 19:13:39,058 : INFO : not storing attribute vectors_ngrams_norm
2018-04-02 19:13:39,058 : INFO : storing np array 'vectors' to news_model_morph.gensim.bin.wv.vectors.npy
Traceback (most recent call last):
  File "fasttext2gensim.py", line 44, in <module>
    save_wv(wv, save_path)
  File "fasttext2gensim.py", line 25, in save_wv
    wv.save(save_path)
  File "/usr/lib64/python2.7/site-packages/gensim/models/fasttext.py", line 699, in save
    super(FastText, self).save(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gensim/models/base_any2vec.py", line 281, in save
    super(BaseAny2VecModel, self).save(fname_or_handle, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 691, in save
    self._smart_save(fname_or_handle, separately, sep_limit, ignore, pickle_protocol=pickle_protocol)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 548, in _smart_save
    compress, subname)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 608, in _save_specials
    restores.extend(val._save_specials(cfname, None, sep_limit, ignore, pickle_protocol, compress, subname))
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 620, in _save_specials
    np.save(subname(fname, attrib), np.ascontiguousarray(val))
  File "/data1/users/index.shin/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 511, in save
    pickle_kwargs=pickle_kwargs)
  File "/data1/users/index.shin/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 565, in write_array
    version)
  File "/data1/users/index.shin/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 308, in _write_array_header
    header = asbytes(_filter_header(header))
  File "/data1/users/index.shin/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 459, in _filter_header
    for token in tokenize.generate_tokens(StringIO(string).readline):
AttributeError: 'module' object has no attribute 'generate_tokens'
```

- gensim, numpy version
```
>>> print gensim.__version__
3.4.0
>>> print numpy.__version__
1.14.2
```

- similar issue : https://groups.google.com/forum/#!topic/gensim/hHksTh8NIF4

**Comment by menshikh-iv** [comment]
Hello @dsindex,

can you re-install / downgrade numpy & check that `pattern` package isn't installed on your PC (this doesn't look like a gensim error).

**Comment by dsindex** [comment]
thank you @menshikh-iv 

i installed `pattern` package. but i got the same errors. 
....

after some inspection of the error strings and some related issues, 
```
AttributeError: 'module' object has no attribute 'generate_tokens'

https://stackoverflow.com/questions/43166677/attributeerror-module-object-has-no-attribute-generate-tokens
```

i noticed that i have a python file named `tokenize.py` in working directory.
i thought this file name is also used in `numpy`. 
so changed the name to `tokenizer.py`.

now the situation differ from the previous.  

```
$ python fasttext2gensim.py -w news_model_morph.bin -s news_model_morph.gensim.bin
2018-04-03 11:41:19,686 : INFO : loading 853067 words for fastText model from news_model_morph.bin
2018-04-03 11:41:47,235 : INFO : loading weights for 853067 words for fastText model from news_model_morph.bin
2018-04-03 11:42:13,949 : INFO : loaded (853067, 700) weight matrix for fastText model from news_model_morph.bin
2018-04-03 11:42:13,949 : INFO : saving FastText object under news_model_morph.gensim.bin, separately None
2018-04-03 11:42:13,950 : INFO : not storing attribute vectors_ngrams_norm
2018-04-03 11:42:13,950 : INFO : storing np array 'vectors' to news_model_morph.gensim.bin.wv.vectors.npy
Traceback (most recent call last):
  File "fasttext2gensim.py", line 42, in <module>
    save_wv(wv, save_path)
  File "fasttext2gensim.py", line 23, in save_wv
    wv.save(save_path)
  File "/usr/lib64/python2.7/site-packages/gensim/models/fasttext.py", line 699, in save
    super(FastText, self).save(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gensim/models/base_any2vec.py", line 281, in save
    super(BaseAny2VecModel, self).save(fname_or_handle, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 691, in save
    self._smart_save(fname_or_handle, separately, sep_limit, ignore, pickle_protocol=pickle_protocol)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 548, in _smart_save
    compress, subname)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 608, in _save_specials
    restores.extend(val._save_specials(cfname, None, sep_limit, ignore, pickle_protocol, compress, subname))
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 620, in _save_specials
    np.save(subname(fname, attrib), np.ascontiguousarray(val))
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 511, in save
    pickle_kwargs=pickle_kwargs)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 562, in write_array
    version)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 308, in _write_array_header
    header = asbytes(_filter_header(header))
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 467, in _filter_header
    return tokenize.untokenize(tokens)
  File "/usr/lib64/python2.7/tokenize.py", line 262, in untokenize
    return ut.untokenize(iterable)
  File "/usr/lib64/python2.7/tokenize.py", line 198, in untokenize
    self.add_whitespace(start)
  File "/usr/lib64/python2.7/tokenize.py", line 187, in add_whitespace
    assert row <= self.prev_row
AssertionError
```

**Comment by menshikh-iv** [comment]
@dsindex can you share `news_model_morph.bin` please (upload to any file-sharing service like google-doc and post link here)? I'll try to reproduce your error.

**Comment by dsindex** [comment]
@menshikh-iv 

i don't have enough storage. 
since `news_model_morph.bin` was trained by sent2vec.
you can try pre-trained models :

https://github.com/epfml/sent2vec#downloading-pre-trained-models

**Comment by menshikh-iv** [comment]
@dsindex please check that the error reproduced with concrete file and give me a link (this can be your file, any pre-trained model, it does not matter).

**Comment by dsindex** [comment]
@menshikh-iv 

exactly same error can be reproduced by

sent2vec_wiki_bigrams 16GB (700dim, trained on english wikipedia)

```
$ python fasttext2gensim.py -m wiki_bigrams.bin -s wiki_bigrams.bin.gensim
2018-04-03 19:07:54,222 : INFO : loading 1066988 words for fastText model from wiki_bigrams.bin
2018-04-03 19:08:47,611 : INFO : loading weights for 1066988 words for fastText model from wiki_bigrams.bin
2018-04-03 19:09:37,763 : INFO : loaded (1066988, 700) weight matrix for fastText model from wiki_bigrams.bin
2018-04-03 19:09:37,763 : INFO : saving FastText object under wiki_bigrams.bin.gensim, separately None
2018-04-03 19:09:37,763 : INFO : not storing attribute vectors_ngrams_norm
2018-04-03 19:09:37,764 : INFO : storing np array 'vectors' to wiki_bigrams.bin.gensim.wv.vectors.npy
Traceback (most recent call last):
  File "t.py", line 45, in <module>
    save_model(model, save_path)
  File "t.py", line 26, in save_model
    model.save(save_path)
  File "/usr/lib64/python2.7/site-packages/gensim/models/fasttext.py", line 699, in save
    super(FastText, self).save(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gensim/models/base_any2vec.py", line 281, in save
    super(BaseAny2VecModel, self).save(fname_or_handle, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 691, in save
    self._smart_save(fname_or_handle, separately, sep_limit, ignore, pickle_protocol=pickle_protocol)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 548, in _smart_save
    compress, subname)
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 608, in _save_specials
    restores.extend(val._save_specials(cfname, None, sep_limit, ignore, pickle_protocol, compress, subname))
  File "/usr/lib64/python2.7/site-packages/gensim/utils.py", line 620, in _save_specials
    np.save(subname(fname, attrib), np.ascontiguousarray(val))
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 511, in save
    pickle_kwargs=pickle_kwargs)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 562, in write_array
    version)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 308, in _write_array_header
    header = asbytes(_filter_header(header))
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 467, in _filter_header
    return tokenize.untokenize(tokens)
  File "/usr/lib64/python2.7/tokenize.py", line 262, in untokenize
    return ut.untokenize(iterable)
  File "/usr/lib64/python2.7/tokenize.py", line 198, in untokenize
    self.add_whitespace(start)
  File "/usr/lib64/python2.7/tokenize.py", line 187, in add_whitespace
    assert row <= self.prev_row
AssertionError
```

- code
```
#!/usr/bin/env python
#-*- coding: utf8 -*-

import os
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
from optparse import OptionParser

from gensim import models
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

import reader

# global variable
VERBOSE = 0

def load_model(model_path) :
        model = models.fasttext.FastText.load_fasttext_format(model_path, encoding='utf-8')
        if VERBOSE : print model[u'가다']
        return model

def save_model(model, save_path) :
        # save with native save() of gensim
        model.save(save_path)

if __name__ == '__main__':

        parser = OptionParser()
        parser.add_option("--verbose", action="store_const", const=1, dest="verbose", help="verbose mode")
        parser.add_option("-m", "--model", dest="model_path", help="model(fasttext binary format) path", metavar="MODEL_PATH")
        parser.add_option("-s", "--save", dest="save_path", help="save(google text format) path", metavar="SAVE_PATH")
        (options, args) = parser.parse_args()

        if options.verbose : VERBOSE = 1

        model_path = options.model_path
        save_path = options.save_path
        if not model_path or not save_path :
                parser.print_help()
                sys.exit(1)

        model = load_model(model_path)
        save_model(model, save_path)
```

**Comment by menshikh-iv** [comment]
I can't load dump (for memory reasons), sorry @dsindex.

**Comment by dsindex** [comment]
@menshikh-iv

no problem :)

i just found a related issue.

https://github.com/numpy/numpy/pull/10524

this issue for python 2.7.5 is very likely same as mine. but fixed version of numpy is 1.14.1

and i used numpy 1.14.2

so it make me confused. 

anyway thank you for your kindly answers.

**Comment by menshikh-iv** [comment]
Yes, as expected - this isn't Gensim problem.

I recommend you to create a clean virtual environment, install latest gensim and try again (if fail - try to downgrade numpy version by version), if not help - try to change python (from 2 to 3) and repeat.
