### ISSUE TITLE
"AttributeError: 'Doc2VecTrainables' object has no attribute 'syn1'" when verifying if model.syn1 is callable

### ISSUE THREAD

**Issue by Syncrossus** [RaRe-Technologies/gensim#2056]
Here is a snippet of code that reproduces the issue:
```
from gensim.models.doc2vec import Doc2Vec
model = Doc2Vec(documents=mycorpus, dm=1, dbow_words=0, dm_concat=0, dm_tag_count=1, trim_rule=None)
for method_name in dir(model):
    try:
        callable(getattr(model, method_name))
    except AttributeError as err:
        print(method_name)
        raise err
```

Here's the stack trace:
```
syn1
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "<stdin>", line 3, in <module>
  File "/home/syncrossus/ProgramFiles/anaconda3/lib/python3.6/site-packages/gensim/utils.py", line 1398, in new_func1
    return func(*args, **kwargs)
  File "/home/syncrossus/ProgramFiles/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 360, in syn1
    return self.trainables.syn1
AttributeError: 'Doc2VecTrainables' object has no attribute 'syn1'
```
As we can see from the result of the `print`, it is when callability of `model.syn1` is checked that the issue arises.

**Comment by menshikh-iv** [comment]
Fixed in `3.5.0`
