### ISSUE TITLE
BasedKeyedVectors functions using vocab field sometimes fail when called from Doc2VecKeyedVectors

### ISSUE THREAD

**Issue by cmiram** [RaRe-Technologies/gensim#2099]
#### Description
[Link to original post in mailing list](https://groups.google.com/forum/#!topic/gensim/_udvKsdWZ6M)

To restate here:

When calling functions on a Doc2VecKeyedVectors model that are part of the base class BasedKeyedVectors (which appear to use entity1 and entity2 as their variable names) it throws a KeyError that it doesn't recognize the doc tag. Using the same doc tags on a function like distance which runs within the Doc2VecKeyedVectors class returns the expected result.

#### Steps/Code/Corpus to Reproduce
Relevant code is linked in the description, let me know if you prefer I copy into here as well.

#### Expected Results
Expect the function to recognize the doc tags and perform the relevant calculation.

#### Actual Results
Throws a KeyError.

Traceback (most recent call last):
  File "C:/Users/cmiramontes/Documents/Projects/PyCharm/otb-ml-integration/Server/OTB_ML_Services.py", line 192, in <module>
    main()
  File "C:/Users/cmiramontes/Documents/Projects/PyCharm/otb-ml-integration/Server/OTB_ML_Services.py", line 188, in main
    d2v.rank(sens, e1, e2)
  File "C:\Users\cmiramontes\Documents\Projects\PyCharm\otb-ml-integration\Server\doc2vec_services.py", line 70, in rank
    return model.docvecs.rank(entity1, entity2)
  File "C:\Users\cmiramontes\Documents\Projects\PyCharm\otb-ml-integration\venv\lib\site-packages\gensim\models\keyedvectors.py", line 190, in rank
    return len(self.closer_than(entity1, entity2)) + 1
  File "C:\Users\cmiramontes\Documents\Projects\PyCharm\otb-ml-integration\venv\lib\site-packages\gensim\models\keyedvectors.py", line 183, in closer_than
    e1_index = self.vocab[entity1].index
KeyError: '00359a92-f243-4b59-b998-33ad0d23b0cd'

#### Versions
Windows-7-6.1.7601-SP1
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
NumPy 1.14.3
SciPy 1.1.0
gensim 3.4.0
FAST_VERSION 0

**Comment by piskvorky** [comment]
CC @manneshiva

**Comment by menshikh-iv** [comment]
Thanks for report @cmiram, I add an example for reproducing an issue:

```python
from gensim.test.utils import common_texts
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

corpus = [TaggedDocument(txt, [str(idx)]) for idx, txt in enumerate(common_texts)]
model = Doc2Vec(corpus, min_count=1)

model.docvecs.rank('1', '2')
```
**Expected**: Int value
**Actual:**
```python
KeyError                                  Traceback (most recent call last)
<ipython-input-1-5f319b2c14a8> in <module>()
      7 model = Doc2Vec(corpus, min_count=1)
      8 
----> 9 model.docvecs.rank('1', '2')
     10 

/home/ivan/.virtualenvs/math/local/lib/python2.7/site-packages/gensim/models/keyedvectors.pyc in rank(self, entity1, entity2)
    355     def rank(self, entity1, entity2):
    356         """Rank of the distance of `entity2` from `entity1`, in relation to distances of all entities from `entity1`."""
--> 357         return len(self.closer_than(entity1, entity2)) + 1
    358 
    359 

/home/ivan/.virtualenvs/math/local/lib/python2.7/site-packages/gensim/models/keyedvectors.pyc in closer_than(self, entity1, entity2)
    348         """Get all entities that are closer to `entity1` than `entity2` is to `entity1`."""
    349         all_distances = self.distances(entity1)
--> 350         e1_index = self.vocab[entity1].index
    351         e2_index = self.vocab[entity2].index
    352         closer_node_indices = np.where(all_distances < all_distances[e2_index])[0]

KeyError: '1'

```
