### ISSUE TITLE
Found error in check labels condition while creating corpus using SvmLightCorpus.serialize 

### ISSUE THREAD

**Issue by shiwangi27** [RaRe-Technologies/gensim#2113]
#### Description
Found error in check labels condition while creating corpus using SvmLightCorpus.serialize 

#### Steps/Code/Corpus to Reproduce 

- Use twenty_newsgroups dataset from sklearn.datasets
- tokenize data and create corpus using gensim dictionary.doc2bow 
- create tfidf of the corpus 
- Pass corpus_tfidf and labels in:
 gensim.corpora.SvmLightCorpus.serialize('svm_20_news_groups.train', corpus_tfidf, labels=labels)

Suggestion: 
Change line 117 to :
` label = labels[docno] if labels.any() else 0  # target class is 0 by default`
or 
` label = labels[docno] if labels is not None and len(labels)>0 else 0  # target class is 0 by default`

#### Expected Results
Should save a gensim corpus

#### Actual Results
Traceback (most recent call last):
File "svm.py", line 40, in <module>
    gensim.corpora.SvmLightCorpus.serialize('svm_20_news_groups.train', corpus_tfidf, labels=labels)
File "C:\Users\shiwangisingh\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\corpora\indexedcorpus.py", line 117, in serialize
    offsets = serializer.save_corpus(fname, corpus, id2word, **kwargs)
File "C:\Users\shiwangisingh\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\corpora\svmlightcorpus.py", line 117, in save_corpus
    label = labels[docno] if labels else 0  # target class is 0 by default
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by menshikh-iv** [comment]
@shiwangi27 thanks for the report

Note: if your labels are `list` - it works as expected (here is an issue only with numpy arrays), in the documentation, type mentioned also as `list` (not `numpy.ndarray` or `iterable`).

Code example (that reproduce an error)
```python
import numpy as np
from gensim.corpora import SvmLightCorpus
from gensim.test.utils import common_corpus, get_tmpfile

path = get_tmpfile("svml.corpus")
labels = [1] * len(common_copus)


SvmLightCorpus.serialize(path, common_corpus, labels=labels)  # work
SvmLightCorpus.serialize(path, common_corpus, labels=np.array(labels))  # don't work
```
```python
ValueError                                Traceback (most recent call last)
<ipython-input-10-8dc0d8702910> in <module>()
      8 
      9 SvmLightCorpus.serialize(path, common_corpus, labels=labels)  # work
---> 10 SvmLightCorpus.serialize(path, common_corpus, labels=np.array(labels))  # don't work

/home/ivan/.virtualenvs/math/local/lib/python2.7/site-packages/gensim/corpora/indexedcorpus.pyc in serialize(serializer, fname, corpus, id2word, index_fname, progress_cnt, labels, metadata)
    115             kwargs['labels'] = labels
    116 
--> 117         offsets = serializer.save_corpus(fname, corpus, id2word, **kwargs)
    118 
    119         if offsets is None:

/home/ivan/.virtualenvs/math/local/lib/python2.7/site-packages/gensim/corpora/svmlightcorpus.pyc in save_corpus(fname, corpus, id2word, labels, metadata)
    115         with utils.smart_open(fname, 'wb') as fout:
    116             for docno, doc in enumerate(corpus):
--> 117                 label = labels[docno] if labels else 0  # target class is 0 by default
    118                 offsets.append(fout.tell())
    119                 fout.write(utils.to_utf8(SvmLightCorpus.doc2line(doc, label)))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

As solution, simpler way - convert parameter to list first (or second variant suggested in first post)

**Comment by Naba7** [comment]
@menshikh-iv sir i want to work on this. how to proceed?

**Comment by rsdel2007** [comment]
Fixes this issue in #2319.
