### ISSUE TITLE
Troubles with randint while word2vec training

### ISSUE THREAD

**Issue by theasder** [RaRe-Technologies/gensim#2129]
Hey fellow developers,
I tried hard to fit word2vec on my sentences but on all the threads I received the following:

    Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/root/anaconda3/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "/root/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 164, in _worker_loop
        tally, raw_tally = self._do_train_job(data_iterable, job_parameters, thread_private_mem)
      File "/root/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 771, in _do_train_job
        tally += train_batch_sg(self, sentences, alpha, work, self.compute_loss)
      File "gensim/models/word2vec_inner.pyx", line 533, in gensim.models.word2vec_inner.train_batch_sg
    AttributeError: 'NoneType' object has no attribute 'randint'

I have googled the error, fixed from 

    next_random = (2**24) * model.random.randint(0, 2**24) + model.random.randint(0, 2**24)

to 

    next_random = (2**24) * np.random.randint(0, 2**24) + np.random.randint(0, 2**24)

but it didn't help. Plz, help.

**Comment by menshikh-iv** [comment]
Hello @theasder,  please provide more information
- what's OS, python, gensim, numpy version you use
- the small code example that reproduces your problem (with corpus)

**Comment by menshikh-iv** [comment]
ping @theasder, please provide needed information

**Comment by menshikh-iv** [comment]
Not enough information, can't be reproduced.
