### ISSUE TITLE
object of type 'zip' has no len()

### ISSUE THREAD

**Issue by AndreasMadsen** [RaRe-Technologies/gensim#215]
There seams to be an issue with either `Sparse2Corpus` or `from_corpus`. Here is a simple example:

``` python
import scipy
import gensim

bow = gensim.matutils.Sparse2Corpus(scipy.sparse.rand(10, 100))
dictionary = gensim.corpora.Dictionary.from_corpus(bow)
```

The errror is:

```
Traceback (most recent call last):
  File "experiment.py", line 5, in <module>
    dictionary = gensim.corpora.Dictionary.from_corpus(bow)
  File "/usr/local/lib/python3.4/site-packages/gensim/corpora/dictionary.py", line 356, in from_corpus
    result.num_nnz += len(document)
TypeError: object of type 'zip' has no len()
```

I'm on OS X 10.9.3 using python 3.4.1

**Comment by Kodwings22** [comment]
I had the same error and i found my solution here( https://kodlogs.net/247/object-of-type-zip-has-no-len ). you can visit here . I am sure you will get your solution.
