### ISSUE TITLE
Error calculating topic coherence using c_v

### ISSUE THREAD

**Issue by bbrinx** [RaRe-Technologies/gensim#2168]
#### Source Code
```python
def compute_coherence_values(self, corpus, texts, limit, start=2, step=3):
    coherence_values = []
    model_list = []
    for num_topics in range(start, limit, step):
        model = models.LdaModel(corpus, 
                                num_topics=num_topics, 
                                id2word=self.dictionary, 
                                passes=10,
                                random_state=100,
                                update_every=1,
                                chunksize=100,
                                alpha='auto',
                                per_word_topics=True)
        model_list.append(model)
        coherencemodel = models.CoherenceModel(model=model, texts=texts, dictionary=self.dictionary, coherence='c_v')
        coherence_values.append(coherencemodel.get_coherence())
    return model_list, coherence_values

def coherence_over_topics(self, corpus, cursor):
    tokenized_texts = [self.prepare(article['content']) for article in cursor if article['content']]
    tokenized_texts_filtered = [filter(lambda x: x in self.dictionary.values(), t) for t in tokenized_texts]
    model_list, coherence_values = self.compute_coherence_values(corpus=corpus, texts=tokenized_texts_filtered, start=2, limit=100, step=4)
    return coherence_values
```

#### Expected Results
Expected coherence values

#### Actual Results
```python
2018-08-27 04:19:54,399 : ERROR : worker encountered unexpected exception
Traceback (most recent call last):
  File "/path/env/lib/python3.6/site-packages/gensim/topic_coherence/text_analysis.py", line 561, in run
    self._run()
  File "/path/env/lib/python3.6/site-packages/gensim/topic_coherence/text_analysis.py", line 581, in _run
    self.accumulator.partial_accumulate(docs, self.window_size)
  File "/path/env/lib/python3.6/site-packages/gensim/topic_coherence/text_analysis.py", line 353, in partial_accumulate
    super(WordOccurrenceAccumulator, self).accumulate(texts, window_size)
  File "/path/env/lib/python3.6/site-packages/gensim/topic_coherence/text_analysis.py", line 289, in accumulate
    self.analyze_text(virtual_document, doc_num)
  File "/path/env/lib/python3.6/site-packages/gensim/topic_coherence/text_analysis.py", line 360, in analyze_text
    self._slide_window(window, doc_num)
  File "/path/env/lib/python3.6/site-packages/gensim/topic_coherence/text_analysis.py", line 375, in _slide_window
    self._token_at_edge = window[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

#### Versions
>>> import platform; print(platform.platform())
Darwin-17.7.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.6.5 (default, Apr 25 2018, 14:23:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.5
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.1.0
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.5.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 0

**Comment by menshikh-iv** [comment]
Not enough information, unreproducible
