### ISSUE TITLE
Gensim import error

### ISSUE THREAD

**Issue by ksmnaidu** [RaRe-Technologies/gensim#2169]
Hi,

I have uninstalled and installed gensim on my box to check the version compatibility but, after re-installing, I was not able to import gensim even though it says gensim package is successfully installed.

I am getting the import error like "No module name gensim"

I tried to do a pip uninstall gensim and did a conda install gensim. I even did an upgrade from conda.

Please help.

#### Description
TODO: change commented example

#### Expected Results
Import should be successful

#### Actual Results
Import Error: "No module name gensim" 

Please paste or specifically describe the actual output or traceback. -->

**Comment by menshikh-iv** [comment]
@ksmnaidu check than you use needed pip version (related with used python interpreter). Also, try to install using pip (not conda).

**Comment by gauravkoradiya** [comment]
```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
import gensim
Traceback (most recent call last):
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e70e92d32c6e>", line 1, in <module>
    import gensim
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\corpora\__init__.py", line 14, in <module>
    from .wikicorpus import WikiCorpus  # noqa:F401
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\corpora\wikicorpus.py", line 29, in <module>
    from gensim.scripts import make_wiki
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\scripts\make_wiki.py", line 45, in <module>
    from gensim.corpora import Dictionary, HashDictionary, MmCorpus,WikiCorpus
ImportError: cannot import name 'WikiCorpus'
```
``
how to resolve it?
