### ISSUE TITLE
Create a TF-IDF model from wikipedia

### ISSUE THREAD

**Issue by estathop** [RaRe-Technologies/gensim#2185]
I realized there is an inconsistency when it comes to manipulating datasets from your official source when it comes to your code. For example, at first I tried to use the "text8" which is a sample of wikipedia with `api.load` and everything worked perfect, then I wanted to escalate to a 16GB dump of wikipedia. The code follows:

```
dataset=api.load("text8")
dct = Dictionary(dataset)  # fit dictionary
corpus = [dct.doc2bow(line) for line in dataset]  # convert corpus to BoW format
model = TfidfModel(corpus)  # fit model
######### validate model
vector = model[corpus[0]]  # apply model to the first corpus document
sortvec = sorted(vector,reverse=True, key = lambda x: x[1]) #sort by TF-IDF descending
x = [item[0] for item in sortvec] #take the indices Descending on TF-IDF probability
cnt=0
y={}
##########passing to a dictionary the pairs corresponding to the indices above
for a in x:
    y[cnt] = dct[a];
    cnt+=1
first15pairs = y.values()[:15] #get top 15 words with highest probabilities from dictionary
d = [[s.encode('ascii','ignore')] for s in first15pairs]
print d
```

from this code I train the TF-IDF model with a small dataset and then manipulate it and take the top 15 words with highest frequencies. Everything works fine. When I change the dataset:
`dataset=api.load("wiki-english-20171001")` it downloads the huge dataset in 4 parts, I assume it creates the dct and corpus normally but when it comes to fitting the model it fails. it does nothing and the rest of the variables remain empty. After that I came across with another object called "WikiCorpus" I tried to write code with that as follows: 
```
wiki = WikiCorpus('data/enwiki-20170101-pages-articles-multistream.xml.bz2', lemmatize=False)
tfidf = TfidfModel(wiki)
```
but an error appears. I digged deeper into that error and found out that python 2 and multistream data is not supported (on official website). So my question is, is there an easy way to train the model the way I want it?

**Comment by piskvorky** [comment]
@estathop and what error?

Both when using `api.load` and when using `WikiCorpus`.

Btw you are creating your `corpus` as a list, in memory. This is not recommended! Use streaming to make `corpus` an iterator, avoid in-memory lists.

**Comment by estathop** [comment]
when using the `api.load` it just doesn't do the same as with the "text8" dataset.
On the other hand when using `WikiCoprus` this appears:
```
wiki = WikiCorpus('/home/estathop/gensim-data/wiki-english-20171001/wiki-english-20171001.gz', lemmatize=False)
tfidf = TfidfModel(wiki)
Process InputQueue-4:
Traceback (most recent call last):
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/utils.py", line 1194, in run
    wrapped_chunk = [list(chunk)]
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 590, in <genexpr>
    ((text, self.lemmatize, title, pageid, tokenization_params)
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 349, in extract_pages
    elem = next(elems)
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 343, in <genexpr>
    elems = (elem for _, elem in iterparse(f, events=("end",)))
  File "<string>", line 100, in next
IOError: invalid data stream
Process InputQueue-8:
Traceback (most recent call last):
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/utils.py", line 1194, in run
    wrapped_chunk = [list(chunk)]
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 590, in <genexpr>
    ((text, self.lemmatize, title, pageid, tokenization_params)
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 349, in extract_pages
    elem = next(elems)
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 343, in <genexpr>
    elems = (elem for _, elem in iterparse(f, events=("end",)))
  File "<string>", line 100, in next
IOError: invalid data stream
```
which I guess it means the data downloaded with api.load is not what supposed to be,
Furthermore when trying to pass a dataset directly downloaded from wikipedia dump, this appears:

```
 wiki = WikiCorpus('/home/estathop/Downloads/enwiki-latest-pages-articles-multistream.xml.bz2', lemmatize=False)
tfidf = TfidfModel(wiki)
Process InputQueue-4:
Traceback (most recent call last):
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/utils.py", line 1194, in run
    wrapped_chunk = [list(chunk)]
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 590, in <genexpr>
    ((text, self.lemmatize, title, pageid, tokenization_params)
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 358, in extract_pages
    for elem in elems:
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 343, in <genexpr>
    elems = (elem for _, elem in iterparse(f, events=("end",)))
  File "<string>", line 107, in next
ParseError: no element found: line 45, column 0
Process InputQueue-8:
Traceback (most recent call last):
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/utils.py", line 1194, in run
    wrapped_chunk = [list(chunk)]
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 590, in <genexpr>
    ((text, self.lemmatize, title, pageid, tokenization_params)
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 358, in extract_pages
    for elem in elems:
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gensim/corpora/wikicorpus.py", line 343, in <genexpr>
    elems = (elem for _, elem in iterparse(f, events=("end",)))
  File "<string>", line 107, in next
ParseError: no element found: line 45, column 0
```

I also tried to use other scripts from you I guess to create the wikiCorpus

`python -m gensim.scripts.make_wiki `(with various paths)
but the same errors appear,
I use ubuntu 16.04LTS and python 2.7 and spyder 3

**Comment by menshikh-iv** [comment]
@estathop 

1. `WikiCorpus` class support only `<LANG>wiki-<DATE>-pages-articles.xml.bz2` files (i.e. raw wikipedia dump with markup), `api.load` get you already processed file (without markdown).

2. `api.load()` return **iterable**, this is only one gurantee that you have. This can be sequence of list (as in `text8` case), sequence of dict (as in `wikipedia` case). In your case, you need to convert this dict to list of tokens first (before pass it to `Dictionary` / `TfIdfModel`), see an example  [how to use `api.load("wiki-english-20171001")`](https://github.com/RaRe-Technologies/gensim-data/releases/tag/wiki-english-20171001), you can see examples for other available datasets & models on [releases](https://github.com/RaRe-Technologies/gensim-data/releases) page.

**Comment by estathop** [comment]
@menshikh-iv so I just need to get the `section_text` from below:
```
dataset = api.load("wiki-english-20171001")
for article in dataset:
    for section_title, section_text in zip(article['section_titles'], article['section_texts']):
        print section_text
        #print("Section title: %s" % section_title)
        #print("Section text: %s" % section_text)
    break
```
pre-process it to remove punctuation and capital words and struct a list of unicode (for every entry within the for loop) from it to feed it to `Dictionary` then construct a corpus from it, etc. So that my initial code works, am I correct ?

**Comment by estathop** [comment]
@menshikh-iv and unfortunately you were right about the out of memory issues. I was thinking about a smaller fragment of the dataset. Or else I will have to dig into the article @piskvorky  mentioned above and learn about generators and iterators . TF-IDF is supposed to be a little bit obsolete and I want it as a base for what I am doing. It shouldn't be that difficult to create a model, I wished it was only a couple of lines with gensim. If I was a python guru I wouldn't need the library in the first place

**Comment by menshikh-iv** [comment]
@estathop better to read an article from @piskvorky, this is the really useful thing that can help you with any tasks related to data more than your RAM. Also, gensim is fully iterable-oriented and encourages such use (takes care of your RAM).

**Comment by estathop** [comment]
what I wanted, worked with a different dataset dump from wikipedia, I downloaded another one that was not multistream which is not support by python 2.x

this code works perfectly

```
wiki = WikiCorpus('/home/estathop/Downloads/enwiki-latest-pages-articles.xml.bz2', lemmatize=False)
model2 = TfidfModel (wiki, smartirs='ntc', pivot =10, slope = 0.2) 
```
