### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by ahmednabil950** [RaRe-Technologies/gensim#2216]
```import gensim ```

caused this error all of sudden after upgrading...

zipfile.BadZipFile: File is not a zip file

installed via pip once and via conda forge once and neither of them worked.

any help will be appreciated.

**Comment by menshikh-iv** [comment]
Hello @ahmednabil950 

can you add more information, please
- gensim version
- python version
- os version
- full stack trace (I have no idea how `zipfile.BadZipFile` can be produced after import)

**Comment by ahmednabil950** [comment]
OPS, 
 i guess i found the solution i have been trying to install [pattern](https://www.clips.uantwerpen.be/pages/pattern-en), but its production stopped some how and it is the source of the problem.
I don't know why but removing ```pip uninstall pattern``` solved the problem.
Thanks  @menshikh-iv 
you can close the issue now.

**Comment by menshikh-iv** [comment]
As expected, an issue in `pattern` package (not `gensim`), we have conditional import here, i.e. if you drop pattern - that's OK to gensim. 
Looks like this related with last pattern release. If you want to use pattern, just downgrade `pattern==2.6`.

**Comment by ahmednabil950** [comment]
Thanks @menshikh-iv :+1:

**Comment by JiaxiangBU** [comment]
Thanks @menshikh-iv when I uninstall `pattern`, import error is fixed.

**Comment by JiaxiangBU** [comment]
> As expected, an issue in `pattern` package (not `gensim`), we have conditional import here, i.e. if you drop pattern - that's OK to gensim.
> Looks like this related with last pattern release. If you want to use pattern, just downgrade `pattern==2.6`.

Hi @menshikh-iv I get this error.

```bash
$ pip install pattern==2.6
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001830F4C2C18>, 'Connection to pypi.tuna.tsinghua.edu.cn timed out. (connect timeout=15)')': /simple/pattern/
Collecting pattern==2.6
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bf/50/d09941d53416f2a86676bd0dc341d5968b599a763b73f5d13f51c57b5641/pattern-2.6.zip (24.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\install\miniconda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LIJIAX~1\\AppData\\Local\\Temp\\pip-install-nr9cd7js\\pattern\\setup.py'"'"'; __file__='"'"'C:\\Users\\LIJIAX~1\\AppData\\Local\\Temp\\pip-install-nr9cd7js\\pattern\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\LIJIAX~1\AppData\Local\Temp\pip-pip-egg-info-uqh6r2jr'
         cwd: C:\Users\LIJIAX~1\AppData\Local\Temp\pip-install-nr9cd7js\pattern\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LIJIAX~1\AppData\Local\Temp\pip-install-nr9cd7js\pattern\setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(n)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
```

Here is my session information.

```bash
# packages in environment at D:\install\miniconda:
#
# Name                    Version                   Build  Channel
absl-py                   0.8.1                    pypi_0    pypi
apache-beam               2.19.0                   pypi_0    pypi
appdirs                   1.4.3                    pypi_0    pypi
args                      0.1.0                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
astropy                   4.0                      pypi_0    pypi
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
audioread                 2.1.8                    pypi_0    pypi
autograd                  1.3                      pypi_0    pypi
autograd-gamma            0.4.1                    pypi_0    pypi
avro-python3              1.9.2.1                  pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports-csv             1.0.7                    pypi_0    pypi
backports-tempfile        1.0                      pypi_0    pypi
backports-weakref         1.0.post1                pypi_0    pypi
beautifulsoup4            4.8.2                    pypi_0    pypi
bert-tensorflow           1.0.1                    pypi_0    pypi
black                     19.10b0                  pypi_0    pypi
blackcellmagic            0.0.2                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bleach                    3.1.5                    pypi_0    pypi
blis                      0.4.1                    pypi_0    pypi
bokeh                     1.4.0                    pypi_0    pypi
boto                      2.49.0                   pypi_0    pypi
boto3                     1.9.252                  pypi_0    pypi
botocore                  1.12.252                 pypi_0    pypi
bqplot                    0.11.0                   pypi_0    pypi
brewer2mpl                1.4.1                    pypi_0    pypi
brotlipy                  0.7.0           py37he774522_1000  
bz2file                   0.98                     pypi_0    pypi
bzip2                     1.0.6                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ca-certificates           2020.6.24                     0  
cachetools                3.1.1                    pypi_0    pypi
calmap                    0.0.7                    pypi_0    pypi
catboost                  0.20.2                   pypi_0    pypi
certifi                   2020.6.20                py37_0  
cffi                      1.14.0           py37h7a1dbc1_0  
chardet                   3.0.4                 py37_1003  
cheroot                   8.2.1                    pypi_0    pypi
cherrypy                  18.5.0                   pypi_0    pypi
cli-helpers               1.2.1                    pypi_0    pypi
click                     7.0                      pypi_0    pypi
clint                     0.5.1                    pypi_0    pypi
cloudpickle               1.3.0                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
conda                     4.8.3                    py37_0  
conda-build               3.18.11                  py37_0  
conda-package-handling    1.6.1            py37h62dcd97_0  
configobj                 5.0.6                    pypi_0    pypi
confuse                   1.0.0                    pypi_0    pypi
console_shortcut          0.1.1                         3  
contextlib2               0.5.5                    pypi_0    pypi
coverage                  5.0.2                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              2.9.2            py37h7a1dbc1_0  
cycler                    0.10.0                   pypi_0    pypi
cymem                     2.0.2                    pypi_0    pypi
cython                    0.29.14                  pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
deepctr                   0.7.4                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
dgl                       0.4.1                    pypi_0    pypi
dill                      0.3.1.1                  pypi_0    pypi
dm-sonnet                 1.36                     pypi_0    pypi
doc2vec2cluster           0.0.1                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
dopamine-rl               3.0.1                    pypi_0    pypi
dynamic-topic-modeling    1.1.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
et-xmlfile                1.0.1                    pypi_0    pypi
fanyi                     0.1                      pypi_0    pypi
fastavro                  0.21.24                  pypi_0    pypi
fasteners                 0.15                     pypi_0    pypi
fastprogress              0.1.21                   pypi_0    pypi
fastscript                0.1.2                    pypi_0    pypi
feedparser                5.2.1                    pypi_0    pypi
filelock                  3.0.12                     py_0  
flask                     1.1.1                    pypi_0    pypi
freetype                  2.10.2               hd328e21_0  
funcy                     1.13                     pypi_0    pypi
future                    0.18.1                   pypi_0    pypi
fy                        1.6.0                    pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
gensim                    3.8.3                    pypi_0    pypi
gevent                    1.4.0                    pypi_0    pypi
gin-config                0.3.0                    pypi_0    pypi
giotto-learn              0.1.3                    pypi_0    pypi
glob2                     0.7                        py_0  
google-api-core           1.16.0                   pypi_0    pypi
google-api-python-client  1.7.11                   pypi_0    pypi
google-apitools           0.5.28                   pypi_0    pypi
google-auth               1.8.2                    pypi_0    pypi
google-auth-httplib2      0.0.3                    pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-cloud-bigquery     1.17.1                   pypi_0    pypi
google-cloud-bigtable     1.0.0                    pypi_0    pypi
google-cloud-core         1.3.0                    pypi_0    pypi
google-cloud-datastore    1.7.4                    pypi_0    pypi
google-cloud-pubsub       1.0.2                    pypi_0    pypi
google-pasta              0.1.7                    pypi_0    pypi
google-resumable-media    0.4.1                    pypi_0    pypi
googleapis-common-protos  1.51.0                   pypi_0    pypi
googletrans               2.4.0                    pypi_0    pypi
graphviz                  2.38.0                        4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
greenlet                  0.4.15                   pypi_0    pypi
grpc-google-iam-v1        0.12.3                   pypi_0    pypi
grpcio                    1.24.1                   pypi_0    pypi
gunicorn                  20.0.4                   pypi_0    pypi
gym                       0.16.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdfs                      2.5.8                    pypi_0    pypi
htmlmin                   0.1.12                   pypi_0    pypi
httplib2                  0.12.0                   pypi_0    pypi
huepy                     1.2.1                    pypi_0    pypi
hyperopt                  0.1.2                    pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1  
idna                      2.10                       py_0  
imageio                   2.8.0                    pypi_0    pypi
importlib-metadata        0.23                     pypi_0    pypi
intel-openmp              2020.1                      216  
intervaltree              3.0.2                    pypi_0    pypi
invoke                    1.4.1                    pypi_0    pypi
ipykernel                 5.3.0                    pypi_0    pypi
ipython                   7.16.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
itchat                    1.2.32                   pypi_0    pypi
itsdangerous              1.1.0                    pypi_0    pypi
jaraco-classes            3.1.0                    pypi_0    pypi
jaraco-collections        3.0.0                    pypi_0    pypi
jaraco-functools          3.0.0                    pypi_0    pypi
jaraco-text               3.2.0                    pypi_0    pypi
jdcal                     1.4.1                    pypi_0    pypi
jedi                      0.17.1                   pypi_0    pypi
jieba                     0.39                     pypi_0    pypi
jinja2                    2.11.1                   pypi_0    pypi
jmespath                  0.9.4                    pypi_0    pypi
joblib                    0.14.0                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2  
json-tricks               3.13.5                   pypi_0    pypi
jsonpickle                1.4.1                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.5                    pypi_0    pypi
jupyter-console           6.1.0                    pypi_0    pypi
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
jupyter-latex-envs        1.4.6                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
jupytext                  1.4.2                    pypi_0    pypi
kaggle                    1.5.6                    pypi_0    pypi
keras                     2.3.1                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-bert                0.80.0                   pypi_0    pypi
keras-embed-sim           0.7.0                    pypi_0    pypi
keras-layer-normalization 0.13.0                   pypi_0    pypi
keras-multi-head          0.22.0                   pypi_0    pypi
keras-pos-embd            0.11.0                   pypi_0    pypi
keras-position-wise-feed-forward 0.6.0                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
keras-rectified-adam      0.17.0                   pypi_0    pypi
keras-self-attention      0.41.0                   pypi_0    pypi
keras-transformer         0.31.0                   pypi_0    pypi
kfac                      0.2.0                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libarchive                3.3.3                h0643e63_5  
libiconv                  1.15                 h1df5818_7  
liblief                   0.10.1               ha925a31_0  
libpng                    1.6.37               h2a8f88b_0  
librosa                   0.7.2                    pypi_0    pypi
libtiff                   4.1.0                h56a325e_0  
libxml2                   2.9.10               h464c3ec_1  
lifelines                 0.23.0                   pypi_0    pypi
lightgbm                  2.3.0                    pypi_0    pypi
litecli                   1.2.0                    pypi_0    pypi
llvmlite                  0.31.0                   pypi_0    pypi
lxml                      4.4.1                    pypi_0    pypi
lz4-c                     1.8.1.2              h2fa13f4_0  
lzo                       2.10                 he774522_2  
magenta                   1.2.2                    pypi_0    pypi
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py37he774522_0  
matplotlib                3.2.1                    pypi_0    pypi
menuinst                  1.4.16           py37he774522_0  
mesh-tensorflow           0.1.9                    pypi_0    pypi
mido                      1.2.6                    pypi_0    pypi
mir-eval                  0.5                      pypi_0    pypi
missingno                 0.4.2                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2020.1                      216  
mkl-service               2.3.0            py37hb782905_0  
mkl_fft                   1.1.0            py37h45dec08_0  
mkl_random                1.1.1            py37h47e9c7a_0  
mock                      2.0.0                    pypi_0    pypi
monotonic                 1.5                      pypi_0    pypi
more-itertools            7.2.0                    pypi_0    pypi
mpmath                    1.1.0                    pypi_0    pypi
msys2-conda-epoch         20160418                      1  
murmurhash                1.0.2                    pypi_0    pypi
mysqlclient               1.4.6                    pypi_0    pypi
nbconvert                 5.6.1                    pypi_0    pypi
nbdev                     0.2.7                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
nbinteract                0.2.5                    pypi_0    pypi
networkx                  2.4                      pypi_0    pypi
newscatcher               0.1.0                    pypi_0    pypi
ngboost                   0.1.4                    pypi_0    pypi
ninja                     1.7.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nltk                      3.4.5                    pypi_0    pypi
nni                       1.3                      pypi_0    pypi
node2vec                  0.3.2                    pypi_0    pypi
notebook                  6.0.3                    pypi_0    pypi
notebook-as-pdf           0.2.0                    pypi_0    pypi
notedown                  1.5.1                    pypi_0    pypi
numba                     0.48.0                   pypi_0    pypi
numexpr                   2.7.0                    pypi_0    pypi
numpy                     1.18.1                   pypi_0    pypi
numpy-base                1.18.1           py37hc3f5095_1  
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0  
opencv-python             4.1.0.25                 pypi_0    pypi
openpyxl                  3.0.2                    pypi_0    pypi
openssl                   1.1.1g               he774522_0  
opt-einsum                3.1.0                    pypi_0    pypi
packaging                 19.2                     pypi_0    pypi
pandas                    1.0.3                    pypi_0    pypi
pandoc-attributes         0.1.7                    pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
pangu                     4.0.6.1                  pypi_0    pypi
parso                     0.7.0                    pypi_0    pypi
pathspec                  0.6.0                    pypi_0    pypi
patsy                     0.5.1                    pypi_0    pypi
pbr                       5.4.4                    pypi_0    pypi
pdfkit                    0.6.1                    pypi_0    pypi
pdfminer-six              20200104                 pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.1.2            py37hcc1f983_0  
pip                       20.1.1                   pypi_0    pypi
pkginfo                   1.5.0.1                  py37_0  
plac                      0.9.6                    pypi_0    pypi
plotly                    4.3.0                    pypi_0    pypi
pluggy                    0.13.0                   pypi_0    pypi
pony                      0.7.11                   pypi_0    pypi
portend                   2.6                      pypi_0    pypi
powershell_shortcut       0.0.1                         2  
preshed                   3.0.2                    pypi_0    pypi
pretty-midi               0.2.8                    pypi_0    pypi
prettytable               0.7.2                    pypi_0    pypi
progressbar               2.5                      pypi_0    pypi
prometheus-client         0.8.0                    pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.5                    pypi_0    pypi
protobuf                  3.10.0                   pypi_0    pypi
psutil                    5.7.0            py37he774522_0  
psycopg2                  2.8.4                    pypi_0    pypi
pulp                      1.6.10                   pypi_0    pypi
pure-sasl                 0.6.2                    pypi_0    pypi
py                        1.8.0                    pypi_0    pypi
py-cpuinfo                6.0.0                    pypi_0    pypi
py-lief                   0.10.1           py37ha925a31_0  
pyarrow                   0.15.1                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.7                    pypi_0    pypi
pycosat                   0.6.3            py37he774522_0  
pycparser                 2.20                       py_0  
pycryptodome              3.9.4                    pypi_0    pypi
pydot                     1.4.1                    pypi_0    pypi
pydrive                   1.3.1                    pypi_0    pypi
pydub                     0.23.1                   pypi_0    pypi
pyecharts                 1.6.2                    pypi_0    pypi
pyecharts-snapshot        0.2.0                    pypi_0    pypi
pyee                      6.0.0                    pypi_0    pypi
pygame                    1.9.6                    pypi_0    pypi
pyglet                    1.5.0                    pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pygtrie                   2.3.2                    pypi_0    pypi
pyks                      1.1.3                    pypi_0    pypi
pyldavis                  2.1.2                    pypi_0    pypi
pymongo                   3.10.1                   pypi_0    pypi
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.3.0                    pypi_0    pypi
pypdf2                    1.26.0                   pypi_0    pypi
pypng                     0.0.20                   pypi_0    pypi
pyppeteer                 0.0.25                   pypi_0    pypi
pyqrcode                  1.2.1                    pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
pysentiment               0.2                      pypi_0    pypi
pysocks                   1.7.1                    py37_0  
pytest                    5.2.1                    pypi_0    pypi
python                    3.7.3                h8c8aaf0_1  
python-dateutil           2.8.1                    pypi_0    pypi
python-docx               0.8.10                   pypi_0    pypi
python-gitlab             2.0.1                    pypi_0    pypi
python-graphviz           0.13.2                     py_0  
python-libarchive-c       2.9                        py_0  
python-rtmidi             1.1.2                    pypi_0    pypi
python-slugify            4.0.0                    pypi_0    pypi
pythonwebhdfs             0.2.3                    pypi_0    pypi
pytorch-cpu               1.1.0               py3.7_cpu_1    pytorch
pytz                      2018.7                   pypi_0    pypi
pyvis                     0.1.8.1.1                pypi_0    pypi
pywaffle                  0.4.1                    pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   227              py37he774522_1  
pywinpty                  0.5.7                    pypi_0    pypi
pyyaml                    5.1.2                    pypi_0    pypi
pyzmq                     19.0.1                   pypi_0    pypi
qgrid                     1.3.0                    pypi_0    pypi
qtconsole                 4.7.5                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
regex                     2019.08.19               pypi_0    pypi
requests                  2.24.0                     py_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
ruamel-yaml               0.16.5                   pypi_0    pypi
ruamel-yaml-clib          0.2.0                    pypi_0    pypi
ruamel_yaml               0.15.87          py37he774522_1  
s3transfer                0.2.1                    pypi_0    pypi
sacremoses                0.0.38                   pypi_0    pypi
schema                    0.7.1                    pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scikit-learn              0.21.3                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.9.0                    pypi_0    pypi
semantic-version          2.8.4                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
sentencepiece             0.1.85                   pypi_0    pypi
setuptools                47.3.1                   py37_0  
shap                      0.32.1                   pypi_0    pypi
simpleaudio               1.0.4                    pypi_0    pypi
simplejson                3.17.0                   pypi_0    pypi
six                       1.15.0                     py_0  
sk-video                  1.1.10                   pypi_0    pypi
sklearn-pandas            1.8.0                    pypi_0    pypi
smart-open                1.8.4                    pypi_0    pypi
snownlp                   0.12.3                   pypi_0    pypi
sortedcontainers          2.1.0                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
soupsieve                 2.0.1                      py_0  
sox                       1.3.7                    pypi_0    pypi
spacy                     2.2.1                    pypi_0    pypi
sqlite                    3.32.3               h2a8f88b_0  
sqlparse                  0.2.4                    pypi_0    pypi
srsly                     0.1.0                    pypi_0    pypi
statsmodels               0.10.1                   pypi_0    pypi
sympy                     1.5.1                    pypi_0    pypi
tabulate                  0.8.6                    pypi_0    pypi
tangled-up-in-unicode     0.0.3                    pypi_0    pypi
tempora                   2.0.0                    pypi_0    pypi
tensor2tensor             1.15.4                   pypi_0    pypi
tensorboard               2.0.2                    pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
tensorflow                2.0.0                    pypi_0    pypi
tensorflow-datasets       2.0.0                    pypi_0    pypi
tensorflow-estimator      2.0.1                    pypi_0    pypi
tensorflow-gan            2.0.0                    pypi_0    pypi
tensorflow-hub            0.6.0                    pypi_0    pypi
tensorflow-metadata       0.21.1                   pypi_0    pypi
tensorflow-probability    0.7.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    pypi_0    pypi
terminaltables            3.1.0                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
thinc                     7.1.1                    pypi_0    pypi
thrift                    0.9.3                    pypi_0    pypi
thrift-sasl               0.2.1                    pypi_0    pypi
tk                        8.6.10               he774522_0  
tokenizers                0.5.2                    pypi_0    pypi
toml                      0.10.0                   pypi_0    pypi
tomotopy                  0.8.1                    pypi_0    pypi
toolz                     0.10.0                   pypi_0    pypi
torchvision-cpu           0.3.0             py37_cuNone_1    pytorch
tornado                   6.0.4                    pypi_0    pypi
tqdm                      4.39.0                   pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
traittypes                0.2.1                    pypi_0    pypi
transformers              2.5.1                    pypi_0    pypi
transformers-sklearn      1.0.0                    pypi_0    pypi
tushare                   1.2.48                   pypi_0    pypi
typed-ast                 1.4.0                    pypi_0    pypi
typing                    3.7.4.1                  pypi_0    pypi
typing-extensions         3.7.4.1                  pypi_0    pypi
uritemplate               3.0.0                    pypi_0    pypi
urllib3                   1.25.9                     py_0  
vc                        14.1                 h0510ff6_4  
visual-midi               0.0.3                    pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_2  
wasabi                    0.2.2                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websockets                8.1                      pypi_0    pypi
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
win_inet_pton             1.1.0                    py37_0  
wincertstore              0.2                      py37_0  
wordcloud                 1.6.0                    pypi_0    pypi
wrapt                     1.11.1                   pypi_0    pypi
wxpy                      0.3.9.8                  pypi_0    pypi
xgboost                   0.90                     pypi_0    pypi
xlrd                      1.2.0                    pypi_0    pypi
xlsxwriter                1.2.8                    pypi_0    pypi
xmltodict                 0.12.0                   pypi_0    pypi
xz                        5.2.5                h62dcd97_0  
yaml                      0.2.5                he774522_0  
zc-lockfile               1.4                      pypi_0    pypi
zipp                      0.6.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4  
zstd                      1.3.7                h508b16e_0  
```

**Comment by menshikh-iv** [comment]
@JiaxiangBU pattern 2.6 requires python2

**Comment by JiaxiangBU** [comment]
> @JiaxiangBU pattern 2.6 requires python2

Thanks, thus, this is not an issue with gensim. I am running some demo using pattern. I will go find a demo based on Python 3.
