### ISSUE TITLE
FastText.save() can't pickle _thread.lock

### ISSUE THREAD

**Issue by RXminuS** [RaRe-Technologies/gensim#2368]
#### Description
I can't save the Gensim model because I get an exception. The data is streamed in.

#### Steps/Code/Corpus to Reproduce
https://gist.github.com/RXminuS/aecaf4656bad55b0e3008987f322f34e

#### Expected Results
The model to be saved

#### Actual Results
Exception thrown

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/utils.py", line 692, in save
    _pickle.dump(self, fname_or_handle, protocol=pickle_protocol)
TypeError: file must have a 'write' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/train_gensim.py", line 263, in <module>
    file_friendly_logging=args.file_friendly_logging, force=args.force)
  File "scripts/train_gensim.py", line 179, in main
    start_alpha=0.025, end_alpha=0.0001)
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/models/fasttext.py", line 710, in train
    queue_factor=queue_factor, report_delay=report_delay, callbacks=callbacks)
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 1081, in train
    **kwargs)
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 563, in train
    callback.on_epoch_end(self)
  File "scripts/train_gensim.py", line 108, in on_epoch_end
    f"_model.{self._global_step}.gensim"), separately=[])
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/models/fasttext.py", line 813, in save
    super(FastText, self).save(*args, **kwargs)
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 621, in save
    super(BaseAny2VecModel, self).save(fname_or_handle, **kwargs)
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/utils.py", line 695, in save
    self._smart_save(fname_or_handle, separately, sep_limit, ignore, pickle_protocol=pickle_protocol)
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/utils.py", line 549, in _smart_save
    pickle(self, fname, protocol=pickle_protocol)
  File "/usr/local/anaconda3/envs/donnanlp/lib/python3.7/site-packages/gensim/utils.py", line 1364, in pickle
    _pickle.dump(obj, fout, protocol=protocol)
TypeError: can't pickle _thread.lock objects
```

#### Versions
```
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Darwin-18.2.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.15.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.2.0
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.7.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
>>> 
```

**Comment by menshikh-iv** [comment]
@RXminuS thanks for the report, can you re-write your example (just minimize it)?

CC @mpenkov

**Comment by mpenkov** [comment]
+1 for a more reproducible and smaller example

**Comment by thistlillo** [comment]
error still among us.
