### ISSUE TITLE
Exception when importing gensim

### ISSUE THREAD

**Issue by TamouzeAssi** [RaRe-Technologies/gensim#2393]
I tried to load gensim in my code. Often it works fine. Today, I get the following exception:

```
Traceback (most recent call last):
  File "/project/6008168/tamouze/just.py", line 2, in <module>
    import gensim
  File "/project/6008168/tamouze/Python_directory/ENV2.7_new/lib/python2.7/site-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/project/6008168/tamouze/Python_directory/ENV2.7_new/lib/python2.7/site-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/project/6008168/tamouze/Python_directory/ENV2.7_new/lib/python2.7/site-packages/gensim/parsing/preprocessing.py", line 40, in <module>
    from gensim import utils
  File "/project/6008168/tamouze/Python_directory/ENV2.7_new/lib/python2.7/site-packages/gensim/utils.py", line 44, in <module>
    from smart_open import smart_open
  File "/project/6008168/tamouze/Python_directory/ENV2.7_new/lib/python2.7/site-packages/smart_open/__init__.py", line 1, in <module>
    from .smart_open_lib import *
  File "/project/6008168/tamouze/Python_directory/ENV2.7_new/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 29, in <module>
    import requests
  File "/project/6008168/tamouze/Python_directory/ENV2.7_new/lib/python2.7/site-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/project/6008168/tamouze/Python_directory/ENV2.7_new/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
ImportError: cannot import name to_native_string
```

my code : 
```
from __future__ import print_function
import gensim
from gensim.models.fasttext import FastText as FT_gensim
```
Can you please help in identified why i get this exception?
Im uisng gensim 3.4.0 and python 2.7.14

**Comment by piskvorky** [comment]
Hi, that exception doesn't look like it originates from Gensim (see the stacktrace).

**Comment by TamouzeAssi** [comment]
my just.py is the following:
```
import gensim
from gensim.models.fasttext import FastText as FT_gensim
print("begin")
modelpath = "/project/6008168/tamouze/Python_directory/dataset/wiki.en.bin"
model =  FT_gensim.load_fasttext_format(modelpath)

print (model["of"])
print("end")
```

There is nothing new to my code. Often this code works very good.

**Comment by gojomo** [comment]
See also: https://stackoverflow.com/a/54873809/130288
