### ISSUE TITLE
Error when import gensim

### ISSUE THREAD

**Issue by mabodx** [RaRe-Technologies/gensim#2430]
#### Problem description
Error when `import gensim`

What are you trying to achieve? What is the expected result? What are you seeing instead?
Just want to import gensim

#### Steps/code/corpus to reproduce
I just run the following code
```
import gensim
```
Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

```
Traceback (most recent call last):
  File "Doc2Vec.py", line 7, in <module>
    import gensim
  File "/usr/local/lib/python3.6/dist-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/usr/local/lib/python3.6/dist-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/usr/local/lib/python3.6/dist-packages/gensim/parsing/preprocessing.py", line 42, in <module>
    from gensim import utils
  File "/usr/local/lib/python3.6/dist-packages/gensim/utils.py", line 45, in <module>
    from smart_open import smart_open
  File "/usr/local/lib/python3.6/dist-packages/smart_open/__init__.py", line 1, in <module>
    from .smart_open_lib import *
  File "/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py", line 45, in <module>
    from boto.compat import BytesIO, urlsplit, six
  File "/usr/lib/python3/dist-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/usr/lib/python3/dist-packages/boto/plugin.py", line 92, in load_plugins
    for file in glob.glob(os.path.join(directory, '*.py')):
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

#### Versions
Python 3.6.8

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

```Python 3.6.8 (default, Dec 24 2018, 19:24:27)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-4.13.0-1012-gcp-x86_64-with-Ubuntu-16.04-xenial
>>> import sys; print("Python", sys.version)
Python 3.6.8 (default, Dec 24 2018, 19:24:27)
[GCC 5.4.0 20160609]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.2.1
>>> import gensim; print("gensim", gensim.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/usr/local/lib/python3.6/dist-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/usr/local/lib/python3.6/dist-packages/gensim/parsing/preprocessing.py", line 42, in <module>
    from gensim import utils
  File "/usr/local/lib/python3.6/dist-packages/gensim/utils.py", line 45, in <module>
    from smart_open import smart_open
  File "/usr/local/lib/python3.6/dist-packages/smart_open/__init__.py", line 1, in <module>
    from .smart_open_lib import *
  File "/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py", line 45, in <module>
    from boto.compat import BytesIO, urlsplit, six
  File "/usr/lib/python3/dist-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/usr/lib/python3/dist-packages/boto/plugin.py", line 92, in load_plugins
    for file in glob.glob(os.path.join(directory, '*.py')):
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/usr/local/lib/python3.6/dist-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/usr/local/lib/python3.6/dist-packages/gensim/parsing/preprocessing.py", line 42, in <module>
    from gensim import utils
  File "/usr/local/lib/python3.6/dist-packages/gensim/utils.py", line 45, in <module>
    from smart_open import smart_open
  File "/usr/local/lib/python3.6/dist-packages/smart_open/__init__.py", line 1, in <module>
    from .smart_open_lib import *
  File "/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py", line 46, in <module>
    import boto.s3.key
  File "/usr/lib/python3/dist-packages/boto/s3/key.py", line 33, in <module>
    import boto.utils
  File "/usr/lib/python3/dist-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
AttributeError: module 'boto' has no attribute 'plugin'```

**Comment by mpenkov** [comment]
Please give the output of:

```python
>>> import boto
>>> print(boto.__version__)
```

**Comment by mpenkov** [comment]
@mabodx Ping

**Comment by austinguo550** [comment]
@mpenkov I have the same issue as @mabodx and when I run import boto to print boto version I get the same error `AttributeError: module 'boto' has no attribute 'plugin'`.

Full error traceback: 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-24337e2ac9e5> in <module>
----> 1 import boto
      2 print(boto.__version__)

~/anaconda3/lib/python3.7/site-packages/boto/__init__.py in <module>
   1214     return storage_uri(uri_str)
   1215 
-> 1216 boto.plugin.load_plugins(config)

AttributeError: module 'boto' has no attribute 'plugin'
```

**Comment by mpenkov** [comment]
@austinguo550 That sounds like a problem with boto (not really something gensim can do anything about). There are other ways you can check the version, e.g.:

```pip show boto```

**Comment by mpenkov** [comment]
Closing due to inactivity
