### ISSUE TITLE
eps = DTYPE_TO_EPS[self.dtype]，KeyError: dtype('float32')

### ISSUE THREAD

**Issue by SCismycat** [RaRe-Technologies/gensim#2439]
## Problem description

Hi，There. I was using gensim LDA to train a model in Linux,I has serialized the lda model to my computer.But when I load the model on windows 10, I got this error:
```
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/PycharmProject/LdaProject/lda_predict.py", line 18, in <module>
    lda_topic = model[doc_bow]
  File "C:\Program Files\Anaconda3\lib\site-packages\gensim\models\ldamodel.py", line 1187, in __getitem__
    return self.get_document_topics(bow, eps, self.minimum_phi_value, self.per_word_topics)
  File "C:\Program Files\Anaconda3\lib\site-packages\gensim\models\ldamodel.py", line 1024, in get_document_topics
    gamma, phis = self.inference([bow], collect_sstats=per_word_topics)
  File "C:\Program Files\Anaconda3\lib\site-packages\gensim\models\ldamodel.py", line 513, in inference
    eps = DTYPE_TO_EPS[self.dtype]
KeyError: dtype('float32')
```
However，when I debug to this function,my dtype is "float32" indeed.
Please help me.

### predict new data
```
model = models.LdaModel.load('E:/PycharmProject/ldadata/model/lda_model.pkl',mmap='r')
dictionary = corpora.Dictionary.load("E:/PycharmProject/ldadata/model/id2word.dict")

query = input("input:")
doc_bow = dictionary.doc2bow(jieba.cut(query,cut_all=False))
lda_topic = model[doc_bow]
for index, score in sorted(lda_topic, key=lambda tup: -1*tup[1]):
    print ("Score: {}\t Topic: {}".format(score, lda_topic.print_topic(index, 20)))
```

## Versions

```
Linux version:  centos7
gensim version: 3.3.0
numpy version: 1.15.0
windows :win10
Python version: 3.5.2
```

**Comment by piskvorky** [comment]
Hi, can you format the report better, so it's readable?

**Comment by SCismycat** [comment]
@piskvorky Sorry about my bad report,And when I upgrade the gensim==3.7.1, this error disappered. So I close this issue.thanks!
