### ISSUE TITLE
LsiTransformer is giving a ValueError

### ISSUE THREAD

**Issue by robguinness** [RaRe-Technologies/gensim#2506]
#### Problem description

I'm trying to use the class `gensim.sklearn_api.lsimodel.LsiTransformer` according to the documentation, but it results in a ValueError with the following stack trace:

```
Traceback (most recent call last):
  File "/home/rob/code_projects/gensim_test/test.py", line 14, in <module>
    corpus_lsi_space = lsi_model.fit_transform(tfidf_features)
  File "/home/rob/venv/pex/gensim_test/lib/python3.6/site-packages/sklearn/base.py", line 553, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/rob/venv/pex/gensim_test/lib/python3.6/site-packages/gensim/sklearn_api/lsimodel.py", line 133, in transform
    distribution = [matutils.sparse2full(self.gensim_model[doc], self.num_topics) for doc in docs]
  File "/home/rob/venv/pex/gensim_test/lib/python3.6/site-packages/gensim/sklearn_api/lsimodel.py", line 133, in <listcomp>
    distribution = [matutils.sparse2full(self.gensim_model[doc], self.num_topics) for doc in docs]
  File "/home/rob/venv/pex/gensim_test/lib/python3.6/site-packages/gensim/models/lsimodel.py", line 583, in __getitem__
    vec = matutils.corpus2csc(bow, num_terms=self.num_terms, dtype=self.projection.u.dtype)
  File "/home/rob/venv/pex/gensim_test/lib/python3.6/site-packages/gensim/matutils.py", line 158, in corpus2csc
    doc_indices, doc_data = zip(*doc) if doc else ([], [])
  File "/home/rob/venv/pex/gensim_test/lib/python3.6/site-packages/scipy/sparse/base.py", line 287, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
```

It could be that I'm misunderstanding something or that the documentation is wrong, but I'm pretty sure this is a bug.

#### Steps/code/corpus to reproduce

Here is a minimal example to reproduce the above stack trace:

```python
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.sklearn_api.lsimodel import LsiTransformer


docs = [
    'This is a doc with nothing special',
    'This is another doc with absolutely nothing special',
    'Here we go with another boring doc that has some generic words'
]

vectorizer = TfidfVectorizer()
tfidf_features = vectorizer.fit_transform(docs)
lsi_model = LsiTransformer(num_topics=5)
corpus_lsi_space = lsi_model.fit_transform(tfidf_features)
```

#### Versions

```python
Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
NumPy 1.16.4
SciPy 1.3.0
gensim 3.7.3
FAST_VERSION 1
```

**Comment by mpenkov** [comment]
Thank you for providing sample code. I could reproduce your results.

So, yes, I also think this is a bug.

@piskvorky WDYT?

**Comment by piskvorky** [comment]
No idea, I never used these wrappers.

CCing @chinmayapancholi13 who is the author of this code. Can you add some tests?

**Comment by piskvorky** [comment]
Ping @chinmayapancholi13 how are the wrappers supposed to be used? Is @robguinness 's use-case above correct?

**Comment by svinkapeppa** [comment]
Seems it's neither a bug, nor problem with documentation, but an incorrect use-case.

According to `matutils.corpus2csc` documents that are passed to this function must be in a **_Gensim bag-of-words format_**:
* Desirable format is a `{list of (int, int), iterable of list of (int, int)}`
* After `TfIdfVectorizer` it is a sparse matrix of type '<class 'numpy.float64'>'

Problems:
1. Occurrences are not specified
2. Floats can't be used (first element of the tuple is a key of the word, second - number of occurrences)

**Comment by BrandonKMLee** [comment]
Having the same issue atm.

**Comment by BrandonKMLee** [comment]
```
from gensim.models import lsimodel
ppmi = pd.read_csv("ppmi.csv")
# ppmi.csv is made up of a (int), b (int) and value (positive float) columns
a = csc_matrix((ppmi_v,(lhs, rhs))).tocsc()
model = lsimodel.LsiModel(a, num_topics=64)
```
Result
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-8d2dbba18cce> in <module>
----> 1 model = lsimodel.LsiModel(a, num_topics=64)

C:\tools\Anaconda3\envs\tag_rec\lib\site-packages\gensim\models\lsimodel.py in __init__(self, corpus, num_topics, id2word, chunksize, decay, distributed, onepass, power_iters, extra_samples, dtype)
    405         if self.id2word is None:
    406             logger.warning("no word id mapping provided; initializing from corpus, assuming identity")
--> 407             self.id2word = utils.dict_from_corpus(corpus)
    408             self.num_terms = len(self.id2word)
    409         else:

C:\tools\Anaconda3\envs\tag_rec\lib\site-packages\gensim\utils.py in dict_from_corpus(corpus)
    895 
    896     """
--> 897     num_terms = 1 + get_max_id(corpus)
    898     id2word = FakeDict(num_terms)
    899     return id2word

C:\tools\Anaconda3\envs\tag_rec\lib\site-packages\gensim\utils.py in get_max_id(corpus)
    805     maxid = -1
    806     for document in corpus:
--> 807         if document:
    808             maxid = max(maxid, max(fieldid for fieldid, _ in document))
    809     return maxid

C:\tools\Anaconda3\envs\tag_rec\lib\site-packages\scipy\sparse\base.py in __bool__(self)
    281             return self.nnz != 0
    282         else:
--> 283             raise ValueError("The truth value of an array with more than one "
    284                              "element is ambiguous. Use a.any() or a.all().")
    285     __nonzero__ = __bool__

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
```

**Comment by mpenkov** [comment]
From a superficial examination, it sounds like the check should be `if document is None`. Anyone in this thread interested in investigating and making a PR?

**Comment by piskvorky** [comment]
Didn't we remove `sklearn_api`?

**Comment by piskvorky** [comment]
@BrandonKMLee seems unrelated, you are supplying the wrong input to `gensim.models.LsiModel`. This ticket was about an sklearn wrapper `gensim.sklearn_api.lsimodel.LsiTransformer` (deprecated and removed since).
