### ISSUE TITLE
When creating a dictionary from a corpus with a id => word mapping, the inverse is not created

### ISSUE THREAD

**Issue by Maocx** [RaRe-Technologies/gensim#2558]
#### Problem description

CoherenceModel tries to access Dictionary.id2token when supplied with ids in the topics list. Dictionary.from_corpus initiates the token2id variable, but not the id2token variable.

A workaround is calling the dictionary as this will check and find that the id2token variable is not of equal length to token2id.

#### Steps/code/corpus to reproduce

``` python
from gensim.corpora import Dictionary as GensimDictionary
from gensim.models import CoherenceModel
from gensim.test.utils import common_corpus, common_dictionary, common_texts

common_dictionary[1]  # have it generate id2token (workaround)
id2word = common_dictionary.id2token
gensim_dict = GensimDictionary.from_corpus(common_corpus, id2word=id2word)
cm = CoherenceModel(topics=[[0, "system"], ["human", "interface"]], texts=common_texts, dictionary=gensim_dict,
                    coherence='c_v')
```

Output:
```
2019-07-19 16:21:31,074 : INFO : 'pattern' package not found; tag filters are not available for English
2019-07-19 16:21:31,078 : INFO : adding document #0 to Dictionary(0 unique tokens: [])
2019-07-19 16:21:31,078 : INFO : built Dictionary(12 unique tokens: ['computer', 'human', 'interface', 'response', 'survey']...) from 9 documents (total 29 corpus positions)
2019-07-19 16:21:31,741 : INFO : adding document #0 to Dictionary(0 unique tokens: [])
2019-07-19 16:21:31,741 : INFO : built Dictionary(12 unique tokens: ['computer', 'human', 'interface', 'response', 'survey']...) from 9 documents (total 29 corpus positions)
Traceback (most recent call last):
  File "C:\Workdir\programs\miniconda\envs\processing3.6\lib\site-packages\gensim\models\coherencemodel.py", line 445, in _ensure_elements_are_ids
    return np.array([self.dictionary.token2id[token] for token in topic])
  File "C:\Workdir\programs\miniconda\envs\processing3.6\lib\site-packages\gensim\models\coherencemodel.py", line 445, in <listcomp>
    return np.array([self.dictionary.token2id[token] for token in topic])
KeyError: 0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "gensim_failure.py", line 22, in <module>
    coherence='c_v')
  File "C:\Workdir\programs\miniconda\envs\processing3.6\lib\site-packages\gensim\models\coherencemodel.py", line 212, in __init__
    self.topics = topics
  File "C:\Workdir\programs\miniconda\envs\processing3.6\lib\site-packages\gensim\models\coherencemodel.py", line 427, in topics
    topic_token_ids = self._ensure_elements_are_ids(topic)
  File "C:\Workdir\programs\miniconda\envs\processing3.6\lib\site-packages\gensim\models\coherencemodel.py", line 448, in _ensure_elements_are_ids
    return np.array([self.dictionary.token2id[token] for token in topic])
  File "C:\Workdir\programs\miniconda\envs\processing3.6\lib\site-packages\gensim\models\coherencemodel.py", line 448, in <listcomp>
    return np.array([self.dictionary.token2id[token] for token in topic])
  File "C:\Workdir\programs\miniconda\envs\processing3.6\lib\site-packages\gensim\models\coherencemodel.py", line 447, in <genexpr>
    topic = (self.dictionary.id2token[_id] for _id in topic)
KeyError: 0
```

#### Versions

Please provide the output of:

```
Windows-10-10.0.17134-SP0
Python 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]
NumPy 1.15.4
SciPy 1.2.0
gensim 3.7.0
FAST_VERSION 0
```

**Comment by piskvorky** [comment]
Thanks for reporting!

@mpenkov I wonder if we should drop that whole `token2id` vs `id2token` caching thing. It adds complexity in order to save RAM, but I don't know if that optimization is still relevant any more. Machines have more resources now, and clean and predictable interfaces are more important than optimization tricks.
