### ISSUE TITLE
loading a vocab file doesn't seem to support unicode_errors

### ISSUE THREAD

**Issue by wmtzk** [RaRe-Technologies/gensim#2569]
#### Problem description

Hi, thank you for providing gensim, which is an amzing lib, for us!

When I tried to read a vocab file generated by native word2vec command, I got an error.
```python
>>> model = gensim.models.KeyedVectors.load_word2vec_format("test_model",unicode_errors='replace',fvocab='test_vocab')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/gensim-3.8.0-py3.7-linux-x86_64.egg/gensim/models/keyedvectors.py", line 1498, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/gensim-3.8.0-py3.7-linux-x86_64.egg/gensim/models/utils_any2vec.py", line 338, in _load_word2vec_format
    word, count = utils.to_unicode(line).strip().split()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/gensim-3.8.0-py3.7-linux-x86_64.egg/gensim/utils.py", line 359, in any2unicode
    return unicode(text, encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 9-10: invalid continuation byte
```

The cause seems that there is no option to work around when some decoding errors happens in the vocab file loading process.

In Python3.x, unicode is replaced with str at the top of utils_any2vec.py.

The default option of str(), built-in function, is
```python
class str(object=b'', encoding='utf-8', errors='strict')
```

So, I propose to make a room to cover some decoding errors for loading a vocab file :)

#### Steps/code/corpus to reproduce

1. Install Anaconda on Ubuntu18.04.
```bash
curl -LO https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh
bash Anaconda3-2019.07-Linux-x86_64.sh
```
2 Clone 'gensim'
```bash
git clone https://github.com/RaRe-Technologies/gensim.git
```
3. Install gensim
```bash
cd gensim/
python setup.py install
```
4. Run the following script with test files.
```python
import gensim
model = gensim.models.KeyedVectors.load_word2vec_format("test_model",unicode_errors='replace',fvocab='test_vocab')
```
5. You will get an error like this.
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/gensim-3.8.0-py3.7-linux-x86_64.egg/gensim/models/keyedvectors.py", line 1498, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/gensim-3.8.0-py3.7-linux-x86_64.egg/gensim/models/utils_any2vec.py", line 338, in _load_word2vec_format
    word, count = utils.to_unicode(line).strip().split()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/gensim-3.8.0-py3.7-linux-x86_64.egg/gensim/utils.py", line 359, in any2unicode
    return unicode(text, encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 9-10: invalid continuation byte
```

*Note: These are not generated by word2vec command. these files are for reproducing this error.*

#### Versions

Ubuntu 18.04

```python
>>> import platform; print(platform.platform())
Linux-4.15.0-1044-aws-x86_64-with-debian-buster-sid
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.0
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.0
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.8.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1

```

[testdata.zip](https://github.com/RaRe-Technologies/gensim/files/3475521/testdata.zip)

**Comment by gojomo** [comment]
I suspect because the `fvocab` option is less-used/less-tested, it hasn't been made as unicode-flexible as the other paths.

**Comment by wmtzk** [comment]
Yes. Actually, I had a chance to use that, and found that.
Anyway, I hope this fix helps "RaRe" person :)
