### ISSUE TITLE
Bug: old versions of gensim suddenly requires Python 3.5

### ISSUE THREAD

**Issue by hakanw** [RaRe-Technologies/gensim#2577]
#### Problem description

Just trying to install gensim 2.3.0 in my production environment and suddenly it has changed an requires python 3.5 so the deploy fails.

See this output from our CircleCI environment which now suddenly fails (with no changes over the summer):

```
...
Collecting gensim==2.3.0 (from -r requirements.txt (line 115))
  Downloading https://files.pythonhosted.org/packages/bc/ed/fbbb2cc3f37a39cc4ff8e5f667374478fb852b384840aa7feb9608144290/gensim-2.3.0.tar.gz (17.2MB)

     |##                              | 1.2MB 42.0MB/s eta 0:00:01           |     |##     |####         |######################        |########################        | 13.1MB 42.0MB/s et     |########     |############################    | 1     |############################### | 16.7MB 42.0MB/s eta 0:00:01
     |################################| 17.2MB 42.0MB/s 
    ERROR: Command errored out with exit status 1:
     command: /opt/circleci/python/2.7.11/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Kgi7w5/gensim/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Kgi7w5/gensim/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-Kgi7w5/gensim/
    Complete output (55 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Kgi7w5/gensim/setup.py", line 302, in <module>
        include_package_data=True,
      File "/opt/circleci/python/2.7.11/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
        run_setup(setup_script, args)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
        raise
      File "/opt/circleci/python/2.7.11/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/opt/circleci/python/2.7.11/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
        saved_exc.resume()
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
        compat.reraise(type, exc, self._tb)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/opt/circleci/python/2.7.11/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-Cu6y0r/numpy-1.17.0/setup.py", line 31, in <module>
        class custom_build_ext(build_ext):
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exited with code 1
```

**Comment by hakanw** [comment]
So a proposed change would be to freeze the numpy requirement to 1.16.4 for all versions of gensim that support Python 2.7, because right now that support is broken out in the wild – even for the existing packages.

**Comment by piskvorky** [comment]
That's exactly what Gensim does already, freezing the numpy version:
https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L235

What exactly is the issue? CC @mpenkov

**Comment by hakanw** [comment]
Ah okay, we've frozen our requirements.txt to use gensim 2.3.0 where this setup.py fix does not exist. Of course we can try to bump it to 2.8.0 instead

**Comment by hakanw** [comment]
I don't know if this is a bug you care about, but this means older gensim deployments pre-2.8.0 in the wild have started to fail (on CI environments), that's what I wanted to report.

**Comment by piskvorky** [comment]
Sure, thanks for reporting.

I'm not sure how to fix this on our end. We can't fix the old versions, and it's already been fixed in newer versions. What do you suggest?

**Comment by mpenkov** [comment]
Closing, there is already a workaround, and there isn't much more we can do here.
