### ISSUE TITLE
"OverflowError: value too large to convert to int" when training word2vec on a large corpus

### ISSUE THREAD

**Issue by miweru** [RaRe-Technologies/gensim#2578]
Hi,
i am trying to train word2vec on on a large corpus (>500GB) and the newest gensim version (3.8.0) and an error occurs on every Thread:

`Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/michael/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/michael/miniconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/michael/miniconda3/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 175, in _worker_loop_corpusfile
    total_examples=total_examples, total_words=total_words, **kwargs)
  File "/home/michael/miniconda3/lib/python3.7/site-packages/gensim/models/word2vec.py", line 794, in _do_train_epoch
    total_examples, total_words, work, neu1, self.compute_loss)
  File "gensim/models/word2vec_corpusfile.pyx", line 379, in gensim.models.word2vec_corpusfile.train_epoch_cbow
OverflowError: value too large to convert to int`

My command for training the Model is:
`Word2Vec(corpus_file="encc_tokenized", size = 1024, window = 8, workers = 16)`

Thank you for help

**Comment by piskvorky** [comment]
CC @persiyanov – is this expected?

**Comment by piskvorky** [comment]
Looking at the code, it's indeed using `int` for all sort of counter that should be large: `expected_examples`, `effective_words`, `effective_sentences`, `total_sentences`, indexes… This will need fixing :(

Or was there some reason to using only `int`s @persiyanov ?

**Comment by miweru** [comment]
The same problem occurs also with FastText:
`Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/michael/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/michael/miniconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/michael/miniconda3/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 175, in _worker_loop_corpusfile
    total_examples=total_examples, total_words=total_words, **kwargs)
  File "/home/michael/miniconda3/lib/python3.7/site-packages/gensim/models/fasttext.py", line 805, in _do_train_epoch
    total_examples, total_words, work, neu1)
  File "gensim/models/fasttext_corpusfile.pyx", line 215, in gensim.models.fasttext_corpusfile.train_epoch_cbow
OverflowError: value too large to convert to int`

**Comment by mpenkov** [comment]
@persiyanov Ping on this.

**Comment by piskvorky** [comment]
Another instance of 32 vs 64 bit integers causing trouble for users:

https://groups.google.com/forum/#!topic/gensim/XbH5Sr6RBcI

Not sure if it's the exact same instance as in this ticket… perhaps we need to promote counters from 32 bit to 64 bit more consistently, everywhere.

**Comment by persiyanov** [comment]
@mpenkov @piskvorky My apologies for the late response.

No, I don't think there was a deliberate choice of using `int` instead of `long long` and I believe it's safe to just to replace all `int` with `long long` types in all corpus-file-related Cython code. 

Do you need a hand on this? I can devote some time next week to fix it.

**Comment by piskvorky** [comment]
Definitely. If you could grep / review all the *2vec code for such 32=>64 bit fixes, that would be awesome. Thanks!

**Comment by Xiaoxiong-Liu** [comment]
@piskvorky 
is this fixed in version 3.8?
I get the same error when trainning when training word2vec on a large corpus.
thx.

**Comment by piskvorky** [comment]
@Xiaoxiong-Liu yes, a fix should have been a part of 4.0.0beta.

Let me know if this still appears after you upgrade: `pip install --pre --upgrade gensim`.
