### ISSUE TITLE
Any bugs on FastText.build_vocab ??

### ISSUE THREAD

**Issue by marcusau** [RaRe-Technologies/gensim#2588]
Hi all,

   I cannot update the training of my gensim fasttext model with the command : model.build_vocab

   I think the key is "AttributeError: 'FastText' object has no attribute 'syn1neg'" 

  Please give me some suggestion. Thanks a lot

    ### Load the pre-trained model, not pretrained vector to make sure that i can train the model 
    print('load fasttext pretrain model ')
    pretrained_model=FastText_gensim.load(pretrained_model_file)

    ### Load the tokens of articles i wanna update and convert the tokens into list of list
    sent=token_df['token'].values.tolist()   

    ##### use the ".build_vocab" of  pretrain model and state "update = True"
    pretrained_model.build_vocab(sent,update=True)

    Traceback (most recent call last):
    File "C:/Users/marcus/PycharmProjects/DIVA_CWS/FastText_pretrain.py", line 313, in <module>
    pretrained_model.build_vocab(sent,update=True)
    File "C:\Users\marcus\Desktop\DIVA_CWS\lib\site-packages\gensim\models\deprecated\word2vec.py", line 712, in build_vocab
    self.finalize_vocab(update=update)  # build tables & arrays
    File "C:\Users\marcus\Desktop\DIVA_CWS\lib\site-packages\gensim\models\deprecated\word2vec.py", line 953, in finalize_vocab
    self.update_weights()
    File "C:\Users\marcus\Desktop\DIVA_CWS\lib\site-packages\gensim\models\deprecated\word2vec.py", line 1373, in update_weights
    self.syn1neg = vstack([self.syn1neg, zeros((gained_vocab, self.layer1_size), dtype=REAL)])
    AttributeError: 'FastText' object has no attribute 'syn1neg'

**Comment by piskvorky** [comment]
@marcusau please fill in the issue template fully, otherwise we'll have to close this.

**Comment by marcusau** [comment]
what kind of issue template i have to fill additionally? Please instruct

**Comment by piskvorky** [comment]
The one that came up when you clicked the "New issue" button.

**Comment by marcusau** [comment]
just filled in the template as you said. Thanks

**Comment by piskvorky** [comment]
Thanks. I see you're using a wrapper around Facebook's fastText, not the native Gensim model.

I'm not sure what the guarantees and interface contracts are – @mpenkov?

**Comment by marcusau** [comment]
The pretrained model i use is just the Chinese pretrained model downloaded from fasttext official website: https://fasttext.cc/docs/en/crawl-vectors.html

I saw other people in this community can load the file by gensim wrapper and retrain it with build_vocab easily.

![image](https://user-images.githubusercontent.com/31444195/64111947-790bbe00-cdb8-11e9-95c6-fd22a365b26e.png)

**Comment by mpenkov** [comment]
@marcusau Sorry for the delay in looking into this. Could you please:

- reduce your example, leaving only the relevant parts? Most of the imports you listed are irrelevant (and some are unavailable).
- provide all relevant data (or at least links to it).

In its current shape, I cannot run your example and reproduce the problem.

It looks like this is the only part that matters:

```python
pretrained_model_file = ... # this value is unknown
token_df = ...  # this value is unknown

from gensim.models.wrappers import FastText  as FastText_gensim
sent=token_df['token'].values.tolist()
pretrained_model=FastText_gensim.load(pretrained_model_file)
pretrained_model.build_vocab(sent,update=True)  # this causes the crash
```

Please review and update your example.

**Comment by vasilevs2011** [comment]
I have the same problem.
I changed the import statement from 
`from gensim.models.wrappers import FastText  as FastText_gensim`
to 
`from gensim.models.fasttext import FastText  as FastText_gensim`
and problem was solved.

**Comment by mpenkov** [comment]
@vasilevs2011 Thank you for the suggestion. @marcusau Does that work for you?

**Comment by Nilanjan96** [comment]
I am having the same problem. I am trying this on google colab. Unfortunately @vasilevs2011 's solution it is not working for me.

**Comment by Nilanjan96** [comment]
This is my code
`from gensim.models.fasttext import FastText as FastText_gensim
model = FastText_gensim.load_fasttext_format("drive/My Drive/wiki-simple.bin")
sent = [['lord', 'of', 'the', 'rings'], ['lord', 'of', 'the', 'semi-groups']]
model.build_vocab(sent, update=True)`

And I am getting this error:

 AttributeError: 'FastTextTrainables' object has no attribute 'syn1neg'
