### ISSUE TITLE
out of memory issue in PyLDAV visulization

### ISSUE THREAD

**Issue by gauravkoradiya** [RaRe-Technologies/gensim#2590]
#### Problem description

What are you trying to achieve?

Visualization of topic model having 8.5L document and 25L vocab size ang 8gb of memory

What is the expected result? 

Create a visualization file.

What are you seeing instead?

We are getting a Memory out of error while programme is preparing a data for pylda vis.

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

```
`C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\past\translation\__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\past\translation\__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\past\translation\__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\past\translation\__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\past\translation\__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\past\translation\__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\past\translation\__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\past\translation\__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\externals\loky\process_executor.py", line 418, in _process_worker
    r = call_item()
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\externals\loky\process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyLDAvis\_prepare.py", line 213, in _find_relevance_chunks
    return pd.concat([_find_relevance(log_ttd, log_lift, R, l) for l in lambda_seq])
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyLDAvis\_prepare.py", line 213, in <listcomp>
    return pd.concat([_find_relevance(log_ttd, log_lift, R, l) for l in lambda_seq])
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyLDAvis\_prepare.py", line 208, in _find_relevance
    relevance = lambda_ * log_ttd + (1 - lambda_) * log_lift
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\__init__.py", line 1506, in f
    return self._combine_const(other, op)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 5396, in _combine_const
    return ops.dispatch_to_series(self, other, func)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\__init__.py", line 596, in dispatch_to_series
    new_data = expressions.evaluate(column_op, str_rep, left, right)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 220, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 126, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 70, in _evaluate_standard
    return op(a, b)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\__init__.py", line 570, in column_op
    return {i: func(a.iloc[:, i], b) for i in range(len(a.columns))}
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\__init__.py", line 570, in <dictcomp>
    return {i: func(a.iloc[:, i], b) for i in range(len(a.columns))}
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\roperator.py", line 17, in rmul
    return right * left
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\series.py", line 810, in __array_ufunc__
    self, ufunc, method, *inputs, **kwargs
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\__init__.py", line 1743, in maybe_dispatch_ufunc_to_dunder_op
    return getattr(self, name, not_implemented)(inputs[0])
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\__init__.py", line 1048, in wrapper
    result = na_op(lvalues, rvalues)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\__init__.py", line 968, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 220, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 126, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 70, in _evaluate_standard
    return op(a, b)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops\roperator.py", line 17, in rmul
    return right * left
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (100,) and data type float32
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/Projects/docs_handler/lsi_experiment.py", line 47, in <module>
    visulize_topic_model(model,corpus,dictionary)
  File "D:/Projects/docs_handler/lsi_experiment.py", line 29, in visulize_topic_model
    viz = pyLDAvis.gensim.prepare(topic_model=model,corpus=corpus,dictionary=dictionary)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyLDAvis\gensim.py", line 119, in prepare
    return vis_prepare(**opts)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyLDAvis\_prepare.py", line 398, in prepare
    topic_info         = _topic_info(topic_term_dists, topic_proportion, term_frequency, term_topic_freq, vocab, lambda_step, R, n_jobs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyLDAvis\_prepare.py", line 255, in _topic_info
    for ls in _job_chunks(lambda_seq, n_jobs)))
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\parallel.py", line 934, in __call__
    self.retrieve()
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\joblib\_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pattern\text\en\..\..\..\..\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\pattern\text\en\..\..\..\..\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (100,) and data type float32

Process finished with exit code 1
`
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```
Windows-10-10.0.17763-SP0
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
NumPy 1.17.0
SciPy 1.3.0
gensim 3.8.0
FAST_VERSION 0

**Comment by mpenkov** [comment]
Thank you for providing the stack trace. Could you provide a minimum reproducible example? Without it, I cannot reproduce your problem and investigate it.

> Visualization of topic model having 8.5L document and 25L vocab size ang 8gb of memory

What unit does the L in 8.5L and 25L refer to? I'm not familiar with this notation.

**Comment by gauravkoradiya** [comment]
L is refer to Lakh.

**Comment by mpenkov** [comment]
I see. 

https://en.wikipedia.org/wiki/Lakh

So your topic model has 850,000 documents and your vocab size is 2,500,000.

Have you tried adjusting these parameters or trying on better hardware? It's likely you are genuinely running out of memory.

**Comment by mpenkov** [comment]
@gauravkoradiya Could you please provide a minimum reproducible example? Reproducing the problem would help us resolve it.
