### ISSUE TITLE
ImportError: cannot import name 'WikiCorpus'

### ISSUE THREAD

**Issue by gauravkoradiya** [RaRe-Technologies/gensim#2594]
```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
import gensim
Traceback (most recent call last):
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e70e92d32c6e>", line 1, in <module>
    import gensim
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\corpora\__init__.py", line 14, in <module>
    from .wikicorpus import WikiCorpus  # noqa:F401
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\corpora\wikicorpus.py", line 29, in <module>
    from gensim.scripts import make_wiki
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\scripts\make_wiki.py", line 45, in <module>
    from gensim.corpora import Dictionary, HashDictionary, MmCorpus,WikiCorpus
ImportError: cannot import name 'WikiCorpus'
```
``
how to resolve it?

_Originally posted by @gauravkoradiya in https://github.com/RaRe-Technologies/gensim/issues/2169#issuecomment-527799066_

**Comment by piskvorky** [comment]
@gauravkoradiya you need to fill in the issue template fully (incl. the versions).
