### ISSUE TITLE
Having issue with load vocabulary built in HashDictionary()

### ISSUE THREAD

**Issue by gauravkoradiya** [RaRe-Technologies/gensim#2595]
#### Problem description

What are you trying to achieve? 
:-Build a vocab on wiki corpus online.
What is the expected result?
:- It should able to save and load a dict sucessfully.
 What are you seeing instead?
:- It is showing error while load a hash dict via load().

#### Steps/code/corpus to reproduce

```
dictionary = gensim.corpora.HashDictionary.load('dictionary/results_wordids.txt.bz2')
2019-09-04 14:46:59,356 : INFO : loading HashDictionary object from dictionary/results_wordids.txt.bz2
Traceback (most recent call last):
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-f4a49c9d73de>", line 1, in <module>
    dictionary = gensim.corpora.HashDictionary.load('dictionary/results_wordids.txt.bz2')
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\utils.py", line 426, in load
    obj = unpickle(fname)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\utils.py", line 1384, in unpickle
    return _pickle.load(f,encoding='latin1')
_pickle.UnpicklingError: invalid load key, '6'.
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by mpenkov** [comment]
@gauravkoradiya Where did you get dictionary/results_wordids.txt.bz2 from? We need it to reproduce the problem.

**Comment by piskvorky** [comment]
Yeah, `results_wordids.txt.bz2` doesn't look hopeful – who would name a binary model pickle `.txt`?

It's probably some I/O mismatch on user side. @gauravkoradiya how did you generate and save this file?
