### ISSUE TITLE
Can't import gensim.models.KeyedVectors with -OO

### ISSUE THREAD

**Issue by paul-tqh-nguyen** [RaRe-Technologies/gensim#2680]
#### Problem description

I'm trying to use `gensim.models.KeyedVectors` in a Python3 program. 

My non-gensim code has `assert` calls in it that I'd like to have removed as they're taking up too much time. 

Disabling the assert calls via `-OO` seems to cause problems.

#### Steps/code/corpus to reproduce

I'm using `Python 3.7.3`.

I'm using gensim version `3.8.1`.

```
puser@pusermachine:~/$ python3
Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gensim
>>> gensim.__version__
'3.8.1'
>>> 
```
It seems to work with `-O` but not `-OO`.
```
puser@pusermachine:~/$ python3 -c "from gensim.models import KeyedVectors"
puser@pusermachine:~/$ python3 -Oc "from gensim.models import KeyedVectors"
puser@pusermachine:~/$ python3 -OOc "from gensim.models import KeyedVectors"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/puser/.local/lib/python3.7/site-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/home/puser/.local/lib/python3.7/site-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/home/puser/.local/lib/python3.7/site-packages/gensim/parsing/preprocessing.py", line 42, in <module>
    from gensim import utils
  File "/home/puser/.local/lib/python3.7/site-packages/gensim/utils.py", line 45, in <module>
    from smart_open import open
  File "/home/puser/.local/lib/python3.7/site-packages/smart_open/__init__.py", line 28, in <module>
    from .smart_open_lib import open, smart_open, register_compressor
  File "/home/puser/.local/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 364, in <module>
    doctools.extract_kwargs(smart_open_s3.open.__doc__),
  File "/home/puser/.local/lib/python3.7/site-packages/smart_open/doctools.py", line 66, in extract_kwargs
    lines = inspect.cleandoc(docstring).split('\n')
  File "/usr/lib/python3.7/inspect.py", line 619, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'NoneType' object has no attribute 'expandtabs'
puser@pusermachine:~/$ 
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```
Here's my output of the above:
```

puser@pusermachine:~/$ python3
Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.0.0-32-generic-x86_64-with-Ubuntu-19.04-disco
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.0
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.8.1
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
>>> 
```

I pre-emptively apologize if I've missed something obvious in the documentation.

**Comment by gojomo** [comment]
Though triggered via `gensim`, this actually looks to be an issue in `smart_open` - specifically its `extract_kwargs()` method, which seems to be counting on a docstring being present.

That code should be made robust – but from my reading of the [`python` docs](https://docs.python.org/3/using/cmdline.html#cmdoption-oo), the `-OO` option **only** removes docstrings, so isn't necessary for your needs (disabling `assert`s, which `-O` is sufficient to do). So that should be a suitable workaround until `smart_open` might be updated – and you may not need `-OO` at all.

**Comment by piskvorky** [comment]
Fixed in https://github.com/RaRe-Technologies/smart_open/pull/406.
