### ISSUE TITLE
Can't get attribute 'Word2VecKeyedVectors' during model.load() when using `hashfxn`

### ISSUE THREAD

**Issue by onlyphantom** [RaRe-Technologies/gensim#2742]
#### Problem description

Created a model using very straightforward code with a hash function to improve reproducibility (used in an academic setting):

```
MODEL_DIR = '.../somepath'
hash =
model = Word2Vec(
        corpus,
        size=SIZE,
        window=WINDOW,
        min_count=1,
        workers=WORKERS,
        iter=ITER,
        seed=100,
        hashfxn=hash
    )

model.save(MODEL_DIR)
```

The code above runs without problem. However, when trying to load using `Word2Vec.load(MODEL_PATH)` it would throw a large trace stack. To narrow it down and save everyone some reading, I isolated it down to this line:

> AttributeError: Can't get attribute 'hash' on <module '__main__' from 'plot/demo/embedding.py'>

I've saved multiple models in my project, none of which require the use of a hashing function. The same code can load those other models without a problem. This is the only one model so it's quite clearly something to do with the hashing.

#### Steps/code/corpus to reproduce

When trying to load the same model:

```
model = Word2Vec.load(MODEL_PATH)
```

Returns the following Traceback:
```
Traceback (most recent call last):
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1330, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 1244, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 603, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/utils.py", line 426, in load
    obj = unpickle(fname)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/utils.py", line 1384, in unpickle
    return _pickle.load(f, encoding='latin1')
AttributeError: Can't get attribute 'hash' on <module '__main__' from 'plot/demo/embedding.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "plot/demo/embedding.py", line 11, in <module>
    model = Word2Vec.load(MODEL_PATH)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1341, in load
    return load_old_word2vec(*args, **kwargs)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/deprecated/word2vec.py", line 172, in load_old_word2vec
    old_model = Word2Vec.load(*args, **kwargs)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/deprecated/word2vec.py", line 1641, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/deprecated/old_saveload.py", line 87, in load
    obj = unpickle(fname)
  File "/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/deprecated/old_saveload.py", line 379, in unpickle
    return _pickle.loads(file_bytes, encoding='latin1')
AttributeError: Can't get attribute 'Word2VecKeyedVectors' on <module 'gensim.models.deprecated.keyedvectors' from '/Users/samuel/anaconda3/envs/deeplearning/lib/python3.6/site-packages/gensim/models/deprecated/keyedvectors.py'>
```

Removing the hashing function will see the `Word2Vec.load()` function works again. I'm not using any keyed vectors helper function, just a straight up Word2Vec save and load. I hope it's easy to reproduce given how it only affects model created with a hash function. 

#### Versions

```
# Platform
Darwin-19.2.0-x86_64-i386-64bit
# Python
Python 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:20:05) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
# numpy version
NumPy 1.15.4
# SciPy version
SciPy 1.1.0
# gensim version
gensim 3.8.1
# word2vec
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
Your report doesn't say what `hash` is, but it seems it's not pickleable.

If you want to be able to save/load a function, it must be pickleable. This means it must be [named and importable](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled).

`Can't get attribute 'hash' on <module '__main__' from 'plot/demo/embedding.py'>`

Your `hash` is being imported from the `__main__` module because you ran `embedding.py` as a script. Try defining `hash` in a module that you're able to import at the time of `load`.
