### ISSUE TITLE
code run in gensim3.7 'Word2VecKeyedVectors' object has no attribute 'vocab'  

### ISSUE THREAD

**Issue by greenary-John** [RaRe-Technologies/gensim#3147]
Errors will occur in the **embed_table** in the code, 
When I use gensim versions 3.7 and 3.8, I encountered the following error
'Word2VecKeyedVectors' object has no attribute'vocab'
In order to fix this problem I tried to use the latest 4.0 version of gensim. Similar errors
TypeError:'Word2Vec' object is not subscriptable

source code detail:
the type of **embed_table** is <class 'gensim.models.word2vec.Word2Vec'>

```python
class TextDataset(Dataset):
    def __init__(self, args,df):
        self.label=df['label'].values
        self.text_features=df[[x[1] for x in args.text_features]].values
        self.text_features_1=df[[x[1] for x in args.text_features_1]].values
        self.dense_features=df[args.dense_features].values
        self.embeddings_tables=[]
        for x in args.text_features:
            self.embeddings_tables.append(args.embeddings_tables[x[0]] if x[0] is not None else None)
        self.embeddings_tables_1=[]
        for x in args.text_features_1:
            self.embeddings_tables_1.append(args.embeddings_tables_1[x[0]] if x[0] is not None else None)            
        self.args=args
        self.df=df

    def __len__(self):
        return len(self.label)

    def __getitem__(self, i):  
        #lable 
        label=self.label[i]
        #BERT input
        if len(self.args.text_features)==0:
            text_features=0
            text_masks=0
            text_ids=0
        else:
            text_features=np.zeros((self.args.max_len_text,self.args.text_dim))
            text_masks=np.zeros(self.args.max_len_text)
            text_ids=np.zeros((self.args.max_len_text,len(self.args.text_features)),dtype=np.int64)
            begin_dim=0
            for idx,(embed_table,x) in enumerate(zip(self.embeddings_tables,self.text_features[i])):
                end_dim=begin_dim+self.args.text_features[idx][-1]              
                for w_idx,word in enumerate(x.split()[:self.args.max_len_text]):
                    text_features[w_idx,begin_dim:end_dim]=embed_table[word]
                    text_masks[w_idx]=1
                    _try:_
                        text_ids[w_idx,idx]=self.args.vocab[self.args.text_features[idx][1],word]
                    except:
                        text_ids[w_idx,idx]=self.args.vocab['unk']
                begin_dim=end_dim
```

Environment python3.6 torch-cpu

#------------------------error in  gensim versions 3.7 and 3.8---------------------------------------#
05/16/2021 09:58:35 - INFO - models.ctrNet -   ***** Running training *****
05/16/2021 09:58:35 - INFO - models.ctrNet -     Num examples = 720000
05/16/2021 09:58:35 - INFO - models.ctrNet -     Num Epochs = 5
05/16/2021 09:58:35 - INFO - models.ctrNet -     Total train batch size (w. parallel, distributed & accumulation) = 64
05/16/2021 09:58:35 - INFO - models.ctrNet -     Total optimization steps = 56250
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    model.train(train_dataset,dev_dataset)
  File "/mnt/usb/data/gg/competetion/tt/models/ctrNet.py", line 76, in train
    for step, batch in enumerate(train_dataloader):
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/usb/data/gg/competetion/tt/src/data_loader.py", line 66, in __getitem__
    text_features_1[w_idx,begin_dim:end_dim]=embed_table[word]
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 353, in __getitem__
    return self.get_vector(entities)
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 471, in get_vector
    return self.word_vec(word)
  File "/home/hp/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 459, in word_vec
    if word in self.vocab:
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'vocab'

**Comment by piskvorky** [comment]
AFAIR `Word2VecKeyedVectors` no longer exists. Did you follow the [migration instructions](https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4)? Hard to say what's happening without seeing your code.

**Comment by greenary-John** [comment]
Thank you very much for your attention, I have posted the context of the error code

**Comment by piskvorky** [comment]
Please post the code & traceback from the latest Gensim (v4.0.1), and after applying the migration notes.
