### ISSUE TITLE
Error with older wiki dumps

### ISSUE THREAD

**Issue by santoshbs** [RaRe-Technologies/gensim#3168]
#### Problem description

I am trying to load wiki dump and extract articles for word2vec training. This works well for more recent dumps. But for older dumps (e.g., 2010 dump), it fails. 

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

If your problem is with a specific Gensim model (word2vec, lsimodel, doc2vec, fasttext, ldamodel etc), include the following:

```python
import multiprocessing
from gensim.corpora.wikicorpus import WikiCorpus
from gensim.models.word2vec import Word2Vec
import logging

logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
logging.root.setLevel(level=logging.INFO)

wiki_dump= './enwiki-20100312-pages-articles.xml.bz2'
wiki= WikiCorpus(fname= wiki_dump, 
                lower= False, 
                 lemmatize=False, 
                 dictionary={}, #not needed for word2vec (https://groups.google.com/u/1/g/gensim/c/aI7vbNCxhb8)
                 processes= max(1, multiprocessing.cpu_count() - 1), 
                 token_min_len=1, 
                 token_max_len=50) 

txt_file = './enwiki_20100312_extracted_articles_v1.txt'
with open(txt_file, 'w') as f:
    for i, text in enumerate(wiki.get_texts()):
        f.write(" ".join(text) + "\n")
        if i % 50000 == 0:
            logging.info("Saved %d articles" % i)
logging.info("Finished extract wiki, Saved in %s" % txt_file) 
```
`Process InputQueue-24:
Traceback (most recent call last):
  File "/anaconda/envs/spacy_v3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/user-sas01/.local/lib/python3.8/site-packages/gensim-4.0.0b0-py3.8-linux-x86_64.egg/gensim/utils.py", line 1215, in run
    wrapped_chunk = [list(chunk)]
  File "/home/user-sas01/.local/lib/python3.8/site-packages/gensim-4.0.0b0-py3.8-linux-x86_64.egg/gensim/corpora/wikicorpus.py", line 679, in <genexpr>
    texts = (
  File "/home/user-sas01/.local/lib/python3.8/site-packages/gensim-4.0.0b0-py3.8-linux-x86_64.egg/gensim/corpora/wikicorpus.py", line 430, in extract_pages
    ns = elem.find(ns_path).text
AttributeError: 'NoneType' object has no attribute 'text'
`

#### Versions

Please provide the output of:

```python
Linux-5.4.0-1047-azure-x86_64-with-glibc2.10
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
Bits 64
NumPy 1.19.2
SciPy 1.6.0
gensim 4.0.0beta
FAST_VERSION 1

```

**Comment by piskvorky** [comment]
Looks like the old wiki dumps have a different XML (Media Wiki) structure, so the parsing fails.

Why do you need these older (10 years+) dumps?

If you manage to implement support for both formats, and the fix doesn't add too much complexity, and we could accept it as a PR. Thanks!

**Comment by santoshbs** [comment]
Thank you, @piskvorky. I am studying how semantic spaces evolve in Wiki over time using word2vec. That is the reason for using year dumps (those available) from 2007 onwards.

**Comment by piskvorky** [comment]
I see. That's a very direct and clear (if narrow) use case :)

We don't need a PR then, I doubt other people have the same need. Still, if you manage to parse the older format, feel free to post your solution here. Just in case someone stumbles on it in the future.
