### ISSUE TITLE
Possible bug in WmdSimilarity

### ISSUE THREAD

**Issue by tvrbanec** [RaRe-Technologies/gensim#3269]
#### Problem description

I wanted to check if WmdSimilarity is any better (it should not be) from multiprocessing wmdistance, but it did not work at all. 
So, I made a little example and the result was exactly the same: AttributeError: 'WmdSimilarity' object has no attribute 'w2v_model'

#### Steps/code/corpus to reproduce

from gensim.models import Word2Vec
from gensim.similarities import WmdSimilarity

a = "Trump’s decision not to join the Trans-Pacific Partnership (TPP) came as little surprise. During his election campaign he railed against international trade deals, blaming them for job losses and focusing anger in the industrial heartland. Obama had argued that this deal would provide an effective counterweight to China in the region."
b = "Trump's decision to withdraw the US from TPP is also a first step in the administration's efforts to amass a governing coalition to push the new President's agenda, one that includes the blue-collar workers who defected from Democrats and flocked to Trump's candidacy in November."
c = "Although the Trans-Pacific Partnership had not been approved by Congress, Mr. Trump’s decision to withdraw not only doomed former President Barack Obama’s signature trade achievement, but also carried broad geopolitical implications in a fast-growing region. The deal, which was to link a dozen nations from Canada and Chile to Australia and Japan in a complex web of trade rules, was sold as a way to permanently tie the United States to East Asia and create an economic bulwark against a rising China."

def w2v(corpus):
    w2v_model = Word2Vec(corpus, alpha=0.025, vector_size=50,
         window=5, min_count=1, workers=2, epochs=50, sg = 0)
    return w2v_model

corpus = "\n".join([a,b,c])
model = w2v(corpus)
print(model, type(model))
print(WmdSimilarity([a,b,c], model))

RESULTS:
Word2Vec(vocab=47, vector_size=50, alpha=0.025) <class 'gensim.models.word2vec.Word2Vec'>
Traceback (most recent call last):
  File "/home/tedo/diagnose/proba.py", line 18, in <module>
    print(WmdSimilarity([a,b,c], model))
  File "/usr/local/lib/python3.9/dist-packages/gensim/similarities/docsim.py", line 1099, in __str__
    return "%s<%i docs, %i features>" % (self.__class__.__name__, len(self), self.w2v_model.wv.syn0.shape[1])
AttributeError: 'WmdSimilarity' object has no attribute 'w2v_model'

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import struct; print("Bits", 8 * struct.calcsize("P"))
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```
Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Bits 64
NumPy 1.21.2
SciPy 1.7.1
gensim 4.1.1
FAST_VERSION 1

**Comment by piskvorky** [comment]
Thanks for reporting Tedo!

Seems like an omission during the WmdDistance refactoring in #2698, where `self.w2v_model` was renamed to `self.wv`. And `__str__` is not covered by CI tests so this wasn't caught automatically.

**Comment by mpenkov** [comment]
@tvrbanec Thank you for reporting this. Are you interested in making a PR to fix the problem?

**Comment by tvrbanec** [comment]
@mpenkov I'd like to, but I do not know how to use Github. It has not come to my agenda yet. :(

**Comment by DingQK** [comment]
@mpenkov  Hi! I am a new user of gensim and I am eager to contribute to the community. Do you still need people to fix this problem? Thank you so much!

**Comment by mpenkov** [comment]
Sure, @DingQK , just make sure you have tests that demonstrate the correctness of your solution

**Comment by DingQK** [comment]
> Sure, @DingQK , just make sure you have tests that demonstrate the correctness of your solution

Hi @mpenkov !

I have submitted my PR and attach my test results with it. Thank you so much!
