### ISSUE TITLE
AttributeError: 'KeyedVectors' object has no attribute 'add'

### ISSUE THREAD

**Issue by GitHubBoys** [RaRe-Technologies/gensim#3325]
#### Problem description

```
Using backend: pytorch
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    main(config)
  File "train.py", line 17, in main
    train_data_loader = config.initialize('train_data_loader', module_data, "train")
  File "/gpfs/home/chenzhiqiang_stu/taxoE/parse_config.py", line 64, in initialize
    return getattr(module, module_cfg['type'])(*args, **module_cfg['args'])
  File "/gpfs/home/chenzhiqiang_stu/taxoE/data_loader/data_loaders.py", line 91, in __init__
    msk_graph_dataset = MaskedGraphDataset(raw_graph_dataset, mode=mode, sampling_mode=sampling_mode, negative_size=negative_size, expand_factor=expand_factor, cache_refresh_time=cache_refresh_time, normalize_embed=normalize_embed, test_topk=test_topk)
  File "/gpfs/home/chenzhiqiang_stu/taxoE/data_loader/dataset.py", line 229, in __init__
    self.kv.add([str(i) for i in range(len(self.vocab))], self.node_features.numpy())
AttributeError: 'KeyedVectors' object has no attribute 'add'
```
#### Steps/code/corpus to reproduce

I
```
 # add node feature vector
        self.kv = KeyedVectors(vector_size=self.node_features.shape[1])
        self.kv.add([str(i) for i in range(len(self.vocab))], self.node_features.numpy())
```

#### Versions

Please provide the output of:

```
python 3.6
gensim 4.1.2

```

**Comment by piskvorky** [comment]
That's right, `KeyedVectors` has no `add()` method. See the API reference: 
https://radimrehurek.com/gensim/models/keyedvectors.html

**Comment by GitHubBoys** [comment]
> That's right, `KeyedVectors` has no `add()` method. See the API reference: https://radimrehurek.com/gensim/models/keyedvectors.html

THANKS
