### ISSUE TITLE
Problem with numpy=1.21.5 and gensim

### ISSUE THREAD

**Issue by GuillemGSubies** [RaRe-Technologies/gensim#3337]
#### Problem description

Followup of: https://github.com/RaRe-Technologies/gensim/issues/3226#issuecomment-1086732442 (sorry for the late response) Looks like it is using the right numpy version, but it won't work anyway. I tried installing gensim from develop and got the same error. I could change the numpy version to solve the problem, however I have other internal dependencies that requiere that specific version (not being shown because I'm trying a minimal reproducible example).

I get an error when using gensim:

#### Steps/code/corpus to reproduce

`conda create -n replicate python=3.10 -y ; conda activate replicate ; pip install gensim==4.1.2 numpy==1.21.5 ; python -c "import gensim"`

```
(base) guillem.garcia@a:~$ conda create -n replicate python=3.10 -y ; conda activate replicate ; pip install gensim==4.1.2 numpy==1.21.5 ; python -c "import gensim"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/guillem.garcia/miniconda3/envs/replicate

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.3.29  |       h06a4308_1         122 KB
    setuptools-61.2.0          |  py310h06a4308_0        1019 KB
    zlib-1.2.12                |       h7f8727e_2         106 KB
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.3.29-h06a4308_1
  certifi            pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
  libuuid            pkgs/main/linux-64::libuuid-1.0.3-h7f8727e_2
  ncurses            pkgs/main/linux-64::ncurses-6.3-h7f8727e_2
  openssl            pkgs/main/linux-64::openssl-1.1.1n-h7f8727e_0
  pip                pkgs/main/linux-64::pip-21.2.4-py310h06a4308_0
  python             pkgs/main/linux-64::python-3.10.4-h12debd9_0
  readline           pkgs/main/linux-64::readline-8.1.2-h7f8727e_1
  setuptools         pkgs/main/linux-64::setuptools-61.2.0-py310h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.38.2-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.11-h1ccaba5_0
  tzdata             pkgs/main/noarch::tzdata-2022a-hda174b7_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.12-h7f8727e_2



Downloading and Extracting Packages
setuptools-61.2.0    | 1019 KB   | ##################################### | 100% 
ca-certificates-2022 | 122 KB    | ##################################### | 100% 
zlib-1.2.12          | 106 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate replicate
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting gensim==4.1.2
  Using cached gensim-4.1.2-cp310-cp310-linux_x86_64.whl
Collecting numpy==1.21.5
  Using cached numpy-1.21.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
Collecting smart-open>=1.8.1
  Downloading smart_open-6.0.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 1.6 MB/s 
Collecting scipy>=0.18.1
  Using cached scipy-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.3 MB)
Installing collected packages: numpy, smart-open, scipy, gensim
Successfully installed gensim-4.1.2 numpy-1.21.5 scipy-1.8.0 smart-open-6.0.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/__init__.py", line 11, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/corpora/indexedcorpus.py", line 14, in <module>
    from gensim import interfaces, utils
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/interfaces.py", line 19, in <module>
    from gensim import utils, matutils
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/matutils.py", line 1024, in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File "gensim/_matutils.pyx", line 1, in init gensim._matutils
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

```

#### Versions

Please provide the output of:

```python
(replicate) guillem.garcia@a:~$ python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.11.0-49-generic-x86_64-with-glibc2.33
>>> import sys; print("Python", sys.version)
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
>>> import struct; print("Bits", 8 * struct.calcsize("P"))
Bits 64
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.21.5
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.8.0
>>> import gensim; print("gensim", gensim.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/__init__.py", line 11, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
  File "/home/guillem.garcia/miniconda3/envs/r[mattip](https://github.com/mattip)eplicate/lib/python3.10/site-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/corpora/indexedcorpus.py", line 14, in <module>
    from gensim import interfaces, utils
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/interfaces.py", line 19, in <module>
    from gensim import utils, matutils
  File "/home/guillem.garcia/miniconda3/envs/replicate/lib/python3.10/site-packages/gensim/matutils.py", line 1024, in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File "gensim/_matutils.pyx", line 1, in init gensim._matutils
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

@mattip

**Comment by mattip** [comment]
As can be seen in the [dependencies for python3.10](https://github.com/RaRe-Technologies/gensim/blob/93ed2fbe27dab41b459bd09bd5b19ed5d7e01908/.github/workflows/build-wheels.yml#L95), gensim on that python requirese numpy 1.22.2. This means you cannot use numpy 1.21 with gensim on python 3.10.

**Comment by GuillemGSubies** [comment]
Ok, that makes sense. Thank you!
