### ISSUE TITLE
save model error

### ISSUE THREAD

**Issue by Alohalt** [RaRe-Technologies/gensim#3404]
genism=3.4.0
numpy=1.14.5
when i try to word2vec.save() 
Traceback (most recent call last):
  File "C:\Users\DELL\.conda\envs\name_dis\lib\site-packages\gensim\utils.py", line 688, in save
    _pickle.dump(self, fname_or_handle, protocol=pickle_protocol)
TypeError: file must have a 'write' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\disambiguation\GAT+GHAC\train_word2vec.py", line 78, in <module>
    train_word2vec()
  File "E:\disambiguation\GAT+GHAC\train_word2vec.py", line 68, in train_word2vec
    model.save('D:\\word2vec.model')
  File "C:\Users\DELL\.conda\envs\name_dis\lib\site-packages\gensim\models\word2vec.py", line 930, in save
    super(Word2Vec, self).save(*args, **kwargs)
  File "C:\Users\DELL\.conda\envs\name_dis\lib\site-packages\gensim\models\base_any2vec.py", line 281, in save
    super(BaseAny2VecModel, self).save(fname_or_handle, **kwargs)
  File "C:\Users\DELL\.conda\envs\name_dis\lib\site-packages\gensim\utils.py", line 691, in save
    self._smart_save(fname_or_handle, separately, sep_limit, ignore, pickle_protocol=pickle_protocol)
  File "C:\Users\DELL\.conda\envs\name_dis\lib\site-packages\gensim\utils.py", line 550, in _smart_save
    pickle(self, fname, protocol=pickle_protocol)
  File "C:\Users\DELL\.conda\envs\name_dis\lib\site-packages\gensim\utils.py", line 1312, in pickle
    _pickle.dump(obj, fout, protocol=protocol)
_pickle.PicklingError: Can't pickle <function __RandomState_ctor at 0x000001CEB07FB510>: it's not the same object as numpy.random.__RandomState_ctor

**Comment by piskvorky** [comment]
Sorry, such old versions of Gensim are not supported any more. See the [migration guide](https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4) for how to upgrade.
