### ISSUE TITLE
Out of bound error when doing lda_mode.update()

### ISSUE THREAD

**Issue by adamcavendish** [RaRe-Technologies/gensim#757]
I got an error when calling `LdaModel.update(corpus)`.

My code's logic is:

```
words = preprocess(document)
corpus.append(id2word.doc2bow(words, allow_update=True))
retrain_tfidf()
corpus_new = corpus[-1:]
lda_model.update(tfidf_model[corpus_new])
```

But I got the following error. I wonder what is the correct way of updating LDA model. Is it because that I might have update my id2word dictionary?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/files/Nutstore/School/Graduate/20160322Silu/SilkRoadProject/python_modules/LatentDirichletAllocation.py", line 168, in add_documents
    self.lda_model.update(self.tfidf_model[corpus_new])
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/ldamodel.py", line 634, in update
    self.log_perplexity(chunk, total_docs=lencorpus)
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/ldamodel.py", line 525, in log_perplexity
    perwordbound = self.bound(chunk, subsample_ratio=subsample_ratio) / (subsample_ratio * corpus_words)
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/ldamodel.py", line 726, in bound
    gammad, _ = self.inference([doc])
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/ldamodel.py", line 433, in inference
    expElogbetad = self.expElogbeta[:, ids]
IndexError: index 35758 is out of bounds for axis 1 with size 35758
```

**Comment by tmylk** [comment]
Please see a [similar issue](https://groups.google.com/d/msg/gensim/T0GMxE7YZqM/7rY-sxwaMAAJ) raised on our mailing list.
If you have any more questions then please reply to that mailing list thread.
Hope it clarifies your concern!
