### ISSUE TITLE
TypeError: don't know how to handle uri True

### ISSUE THREAD

**Issue by loretoparisi** [RaRe-Technologies/gensim#975]
I get this error when saving to binary word2vec format my model:

```
[2016-10-21 15:28:31] Saving trained model and vocabulary word2vec format...
Traceback (most recent call last):
  File "lyricsmodel.py", line 88, in <module>
    model.save_word2vec_format(model_name, fvocab=True, binary=True)
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 1009, in save_word2vec_format
    with utils.smart_open(fvocab, 'wb') as vout:
  File "/Library/Python/2.7/site-packages/smart_open/smart_open_lib.py", line 160, in smart_open
    raise TypeError('don\'t know how to handle uri %s' % repr(uri))
TypeError: don't know how to handle uri True
```

My script is like:

```
    corpus_iterator = LyricsCorpus( corpora_filepath, deaccent=True, tokenize=True, maxFiles=30 )

    min_count = 1
    size = 100
    window = 4
    model = Word2Vec(corpus_iterator, min_count=min_count, size=size, window=window)

    model_name = model_filepath+'mdl_'+corpora_language
    logger.info( "Saving trained model..." )
    model.save( model_name )
    logger.info( "Model saved to %s" % (model_name) )

    model_name = model_filepath+'mdl_vectors_'+corpora_language+'.bin'
    logger.info( "Saving trained model and vocabulary word2vec format..." )
   # <---- this causes the error!
    model.save_word2vec_format(model_name, fvocab=True, binary=True)
```

The `model.save` works ok.

**Comment by gojomo** [comment]
`fvocab` is a filename, not a boolean like the `True` you are supplying. See the doc comment:

https://github.com/RaRe-Technologies/gensim/blob/3b9bb59dac0d55a1cd6ca8f984cead38b9cb0860/gensim/models/word2vec.py#L1108

Please use the project forum, https://groups.google.com/forum/#!forum/gensim, for questions/troubleshooting discussion – Github issues are for bugs and enhancements.

**Comment by loretoparisi** [comment]
@gojomo sorry typo in the code that was `fvocab= model_name` thank you.

**Comment by gojomo** [comment]
If you use `fvocab=model_name`, you're supplying the same filename for two different files – the later step (vector dump) will clobber the former (vocabulary dump).
